# -----------------------------------------
# Child template — expects an object list
# -----------------------------------------
parameters:
  - name: workspaces
    type: object
    default: [] # Parent will supply the list
  - name: CapacityIdNonProd
    type: string
  - name: CapacityIdProd
    type: string

jobs:
  - job: AssignFabricCapacityToWorkspaces
    displayName: Assign Fabric Capacity To Workspaces
    steps:
      - checkout: self

      # Loop over each workspace entry
      - ${{ each ws in parameters.workspaces }}:
          - task: AzureCLI@2
            displayName: "Assign Fabric Capacity To ${{ ws.name }} Workspace "
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -euo pipefail
                chmod +x devops-pipelines/templates/scripts/assigncap.sh
                source devops-pipelines/templates/scripts/assigncap.sh

                WS_NAME="${WS_NAME:-"${{ ws.name }}"}"
                env_prefix="${WS_NAME%%-*}"
                env_prefix="${env_prefix,,}"
                env_prefix="${env_prefix//[[:space:]]/}"

                if [[ "${env_prefix}" == "prod" ]]; then
                  CAPACITY_ID="${{ parameters.CapacityIdProd }}"
                else
                  CAPACITY_ID="${{ parameters.CapacityIdNonProd }}"
                fi

                assign_workspace_to_capacity "${{ ws.name }}" "${CAPACITY_ID}"
