{
  "compatibilityLevel": 1604,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.139.7496.1 (Main)+061188de2d27b556d0c15d8f70c4426f68783390"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"DatabaseQuery\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"WebModelingEdit\"]"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":false,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Perspectives\",\"Relationships\",\"Roles\",\"Shared Expressions\",\"Tables\",\"Tables/Calculation Items\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\"],\"IgnoreLineageTags\":true}"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ],
    "collation": "Latin1_General_100_BIN2_UTF8",
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "DatabaseQuery",
        "annotations": [
          {
            "name": "PBI_IncludeFutureArtifacts",
            "value": "False"
          },
          {
            "name": "PBI_RemovedChildren",
            "value": "[{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"[dbo].[curated_f_bubudgets]\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"[dbo].[curated_d_territory]\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"[dbo].[curated_d_processingstatus]\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"[dbo].[curated_d_linestatus]\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"[dbo].[curated_l_customerbusalesteam]\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"[dbo].[curated_d_salesteam]\"}},\"objectType\":\"Table\"},{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"[dbo].[curated_d_comahsubcategory]\"}},\"objectType\":\"Table\"}]"
          }
        ],
        "expression": [
          "let",
          "    database = Sql.Database(\"TZVK5NQY63UUNNMWQVLZZWHS3Y-HBB5SDEMLK2UREP2YMOBIWR6XU.datawarehouse.fabric.microsoft.com\", \"1eb650e3-7819-4a9c-b947-43b42af5c1f1\")",
          "in",
          "    database"
        ],
        "kind": "m",
        "lineageTag": "5cb0cb96-633c-4945-9dbc-d703113cb0a0"
      }
    ],
    "relationships": [
      {
        "name": "0c085408-66f8-45ac-e903-f819eb30d32e",
        "fromColumn": "LegalEntityID",
        "fromTable": "d_legalentity",
        "toCardinality": "many",
        "toColumn": "FK_LegalEntityID",
        "toTable": "b_userlegalentity"
      },
      {
        "name": "5d8aadab-ea86-22e2-132d-c7cd63eca437",
        "fromColumn": "FK_UserID",
        "fromTable": "b_userlegalentity",
        "relyOnReferentialIntegrity": true,
        "toColumn": "UserID",
        "toTable": "d_user"
      },
      {
        "name": "55538d23-364e-4104-af28-8ea5f4283735",
        "fromColumn": "FK_SalesAreaID",
        "fromTable": "f_salesinvoices",
        "toColumn": "SalesAreaID",
        "toTable": "d_salesarea"
      },
      {
        "name": "591adaf6-7233-8c72-aeb0-4109b11d5727",
        "fromColumn": "FK_OperationalSiteID",
        "fromTable": "f_pricelist",
        "toColumn": "OperationalSiteID",
        "toTable": "d_operationalsite"
      },
      {
        "name": "5928a213-9bd6-0c74-bf1f-4c042bb6547e",
        "fromColumn": "FK_WarehouseID",
        "fromTable": "f_pricelist",
        "toColumn": "WarehouseID",
        "toTable": "d_warehouse"
      },
      {
        "name": "b768178c-9c64-6dd4-59bf-cf2eea03acd0",
        "fromColumn": "FK_UnitID",
        "fromTable": "f_pricelist",
        "toColumn": "UnitID",
        "toTable": "d_unit"
      },
      {
        "name": "5c57ebb5-8a65-d28a-d1c3-c7fd295774d1",
        "fromColumn": "FK_ProductID",
        "fromTable": "f_pricelist",
        "toColumn": "ProductID",
        "toTable": "d_product"
      },
      {
        "name": "0aee2b2b-00d0-ad79-a9e5-4b04ad74b9e1",
        "fromColumn": "FK_LegalEntityID",
        "fromTable": "f_pricelist",
        "toColumn": "LegalEntityID",
        "toTable": "d_legalentity"
      },
      {
        "name": "bd9457b4-115b-b074-cdc9-3cc62daa17f8",
        "fromColumn": "FK_DateID",
        "fromTable": "f_pricelist",
        "toColumn": "DateID",
        "toTable": "d_date"
      },
      {
        "name": "be107e9b-63dc-fc7f-de5a-1a4f649845c2",
        "fromColumn": "FK_CustomerID",
        "fromTable": "f_pricelist",
        "toColumn": "CustomerID",
        "toTable": "d_customer"
      },
      {
        "name": "b563baec-2f99-cbbc-7ed2-18d69cac557f",
        "fromColumn": "FK_CurrencyID",
        "fromTable": "f_pricelist",
        "toColumn": "CurrencyID",
        "toTable": "d_currency"
      },
      {
        "name": "41378d2b-0d39-ab2d-09fe-f08bcd843278",
        "fromColumn": "FK_DateID",
        "fromTable": "f_budgets",
        "toColumn": "DateID",
        "toTable": "d_date"
      },
      {
        "name": "1ef8b550-8f9a-d5f3-f35a-784bf4431948",
        "fromColumn": "FK_InvoiceAddressID",
        "fromTable": "f_salesinvoices",
        "toColumn": "PostalAddressID",
        "toTable": "d_invoiceaddress"
      },
      {
        "name": "c2709512-1fae-f938-1ad8-8558e04901b6",
        "fromColumn": "FK_DateID",
        "fromTable": "f_tankreadings",
        "toColumn": "DateID",
        "toTable": "d_date"
      },
      {
        "name": "507ede61-d62f-3258-e960-2c372441d2e8",
        "fromColumn": "FK_DateID",
        "fromTable": "f_salesinvoices",
        "toColumn": "DateID",
        "toTable": "d_date"
      },
      {
        "name": "dd7ab436-307f-ae43-9771-7c0e99fefba5",
        "fromColumn": "FK_FromCurrencyID",
        "fromTable": "f_exchangerates",
        "toColumn": "CurrencyID",
        "toTable": "d_fromcurrency"
      },
      {
        "name": "634a66d1-908d-caf9-b351-4d850320daf6",
        "fromColumn": "FK_ToCurrencyID",
        "fromTable": "f_exchangerates",
        "toColumn": "CurrencyID",
        "toTable": "d_currency"
      },
      {
        "name": "2f1b1c9f-a60b-1479-c852-616e14f8ffdf",
        "fromColumn": "FK_SalesAreaID",
        "fromTable": "f_budgets",
        "toColumn": "SalesAreaID",
        "toTable": "d_salesarea"
      },
      {
        "name": "06390d2e-8d6d-025f-f871-dbb810450373",
        "fromColumn": "FK_ComahCategoryID",
        "fromTable": "f_comahsnapshot",
        "toColumn": "ComahCategoryID",
        "toTable": "d_comahcategory"
      },
      {
        "name": "7a77977e-b306-70bd-83fb-f62ab1c6a430",
        "fromColumn": "FK_LegalEntityID",
        "fromTable": "f_comahsnapshot",
        "toColumn": "LegalEntityID",
        "toTable": "d_legalentity"
      },
      {
        "name": "28f45ddf-39d1-c555-91f7-0594b48c040d",
        "fromColumn": "FK_OperationalSiteID",
        "fromTable": "f_comahsnapshot",
        "toColumn": "OperationalSiteID",
        "toTable": "d_operationalsite"
      },
      {
        "name": "14ea1b8a-d6b5-10eb-5a40-14cce08bce1e",
        "fromColumn": "FK_WarehouseID",
        "fromTable": "f_salesorders",
        "toColumn": "WarehouseID",
        "toTable": "d_warehouse"
      },
      {
        "name": "d697bbeb-23d7-861b-b1c0-8c8588f1f1f9",
        "fromColumn": "FK_UnitID",
        "fromTable": "f_salesorders",
        "toColumn": "UnitID",
        "toTable": "d_unit"
      },
      {
        "name": "4c4af75b-4407-3410-cbf2-1bb2a8ec9a2e",
        "fromColumn": "FK_ProductID",
        "fromTable": "f_salesorders",
        "toColumn": "ProductID",
        "toTable": "d_product"
      },
      {
        "name": "5ba083f6-55e6-f9fa-22b1-4acbfa581087",
        "fromColumn": "FK_LegalEntityID",
        "fromTable": "f_salesorders",
        "toColumn": "LegalEntityID",
        "toTable": "d_legalentity"
      },
      {
        "name": "a8e2f280-7ba8-8cc3-347f-efd7d3220f51",
        "fromColumn": "FK_DocumentStatusID",
        "fromTable": "f_salesorders",
        "toColumn": "DocumentStatusID",
        "toTable": "d_documentstatus"
      },
      {
        "name": "4285215e-533b-f6d9-f01e-9baaab0281ef",
        "fromColumn": "FK_DeliveryAddressID",
        "fromTable": "f_salesorders",
        "toColumn": "PostalAddressID",
        "toTable": "d_postaladdress"
      },
      {
        "name": "c1e47160-3ebc-15ee-d336-c3fb1fd09bce",
        "fromColumn": "FK_LegalEntityID",
        "fromTable": "f_inventorysnapshot",
        "toColumn": "LegalEntityID",
        "toTable": "d_legalentity"
      },
      {
        "name": "279efba6-e72b-17be-66c3-8701ba7f7e9d",
        "fromColumn": "FK_UnitID",
        "fromTable": "f_salesinvoices",
        "toColumn": "UnitID",
        "toTable": "d_unit"
      },
      {
        "name": "860eed45-4539-6c60-7745-a3cded92d81d",
        "fromColumn": "FK_DeliveryAddressID",
        "fromTable": "f_salesinvoices",
        "toColumn": "PostalAddressID",
        "toTable": "d_postaladdress"
      },
      {
        "name": "4a4c4006-5c0d-7b8c-11c6-266f2f670c88",
        "fromColumn": "FK_PostalAddressID",
        "fromTable": "f_purchaseorders",
        "toColumn": "PostalAddressID",
        "toTable": "d_postaladdress"
      },
      {
        "name": "d978d9f0-6f43-c3fe-4d3f-6d56f9d8205c",
        "fromColumn": "FK_BusinessUnitID",
        "fromTable": "f_salesinvoices",
        "toColumn": "BusinessUnitID",
        "toTable": "d_businessunit"
      },
      {
        "name": "ab2efc8e-9d6e-9052-867a-18c2f7da7f55",
        "fromColumn": "FK_WarehouseID",
        "fromTable": "f_purchaseorders",
        "toColumn": "WarehouseID",
        "toTable": "d_warehouse"
      },
      {
        "name": "8efa06e4-c08e-8920-1eec-56261de43311",
        "fromColumn": "FK_SnapshotDateID",
        "fromTable": "f_inventorysnapshot",
        "toColumn": "DateID",
        "toTable": "d_date"
      },
      {
        "name": "b7f8fc1c-d079-a925-f30e-801d2adf3ecd",
        "fromColumn": "FK_DateID",
        "fromTable": "f_exchangerates",
        "toColumn": "DateID",
        "toTable": "d_date"
      },
      {
        "name": "f7405d0a-f717-5fb1-6adc-3d6a97e7313f",
        "fromColumn": "FK_DateID",
        "fromTable": "f_purchaseorders",
        "toColumn": "DateID",
        "toTable": "d_date"
      },
      {
        "name": "e6e54882-5674-aeba-cf2f-6accb9029859",
        "fromColumn": "FK_DateID",
        "fromTable": "f_comahsnapshot",
        "toColumn": "DateID",
        "toTable": "d_date"
      },
      {
        "name": "c108dc7b-4d0e-519f-da1f-4b6cb0d75abb",
        "fromColumn": "FK_LegalEntityID",
        "fromTable": "f_budgets",
        "toColumn": "LegalEntityID",
        "toTable": "d_legalentity"
      },
      {
        "name": "276d6524-2447-795d-1777-84023a0f253a",
        "fromColumn": "FK_LegalEntityID",
        "fromTable": "f_purchaseorders",
        "toColumn": "LegalEntityID",
        "toTable": "d_legalentity"
      },
      {
        "name": "99774949-c175-2aec-382c-42d2068a22c4",
        "fromColumn": "FK_LegalEntityID",
        "fromTable": "f_salesinvoices",
        "toColumn": "LegalEntityID",
        "toTable": "d_legalentity"
      },
      {
        "name": "ff954ffe-209d-93aa-cb00-1b83986fdd1d",
        "fromColumn": "FK_ProductID",
        "fromTable": "f_tankreadings",
        "toColumn": "ProductID",
        "toTable": "d_product"
      },
      {
        "name": "b72d23c0-08a1-d562-323a-0abe79e79d67",
        "fromColumn": "FK_SupplierID",
        "fromTable": "f_salesinvoices",
        "toColumn": "SupplierID",
        "toTable": "d_supplier"
      },
      {
        "name": "d1a46856-6f0d-aa6c-3db5-3df5f79b5412",
        "fromColumn": "FK_WarehouseID",
        "fromTable": "f_inventorysnapshot",
        "toColumn": "WarehouseID",
        "toTable": "d_warehouse"
      },
      {
        "name": "568d7e6d-572f-f74e-6abe-9d6d7b8e0ac1",
        "fromColumn": "FK_TankID",
        "fromTable": "f_tankreadings",
        "toColumn": "TankID",
        "toTable": "d_tank"
      },
      {
        "name": "11b91a52-0c05-460f-0ef1-3b5f562aa0be",
        "fromColumn": "FK_ProductID",
        "fromTable": "f_inventorysnapshot",
        "toColumn": "ProductID",
        "toTable": "d_product"
      },
      {
        "name": "a92609eb-6ea7-8f84-51c7-0d8aee448c10",
        "fromColumn": "FK_PurchaseOrderStatusID",
        "fromTable": "f_purchaseorders",
        "toColumn": "PurchaseOrderStatusID",
        "toTable": "d_purchaseorderstatus"
      },
      {
        "name": "bd0a0bfc-ca4d-e068-773b-6c5ab3e254c2",
        "fromColumn": "FK_SupplierID",
        "fromTable": "f_purchaseorders",
        "toColumn": "SupplierID",
        "toTable": "d_supplier"
      },
      {
        "name": "b75afcde-05a5-8f8e-0fe5-b01bf674eb7a",
        "fromColumn": "FK_ProductID",
        "fromTable": "f_purchaseorders",
        "toColumn": "ProductID",
        "toTable": "d_product"
      },
      {
        "name": "c7e83ded-6613-4710-9d19-1e82c21541e2",
        "fromColumn": "FK_CustomerID",
        "fromTable": "f_salesorders",
        "toColumn": "CustomerID",
        "toTable": "d_customer"
      },
      {
        "name": "fc9a47e4-c085-9420-d338-1537abb45af7",
        "fromColumn": "FK_CustomerID",
        "fromTable": "f_salesinvoices",
        "toColumn": "CustomerID",
        "toTable": "d_customer"
      },
      {
        "name": "d5c7fea4-4c2c-9303-d37d-099c852afc88",
        "fromColumn": "FK_SalesOrderStatusID",
        "fromTable": "f_salesorders",
        "toColumn": "SalesOrderStatusID",
        "toTable": "d_salesorderstatus"
      },
      {
        "name": "22447c58-157d-824a-627d-2e224cd7b05f",
        "fromColumn": "FK_ProductID",
        "fromTable": "f_salesinvoices",
        "toColumn": "ProductID",
        "toTable": "d_product"
      },
      {
        "name": "fabd458c-23b3-97fa-75be-1ec195d89cc4",
        "fromColumn": "FK_DateID",
        "fromTable": "f_salesorders",
        "toColumn": "DateID",
        "toTable": "d_date"
      },
      {
        "name": "e01ee57e-d65e-44e2-55a7-aa6ecee6e558",
        "fromColumn": "FK_SalesTeamID",
        "fromTable": "f_salesinvoices",
        "toColumn": "UserID",
        "toTable": "d_salesteam"
      },
      {
        "name": "7f7ece46-c2a6-e523-665d-30267b6a783f",
        "fromColumn": "FK_BusinessUnitID",
        "fromTable": "f_salesorders",
        "toColumn": "BusinessUnitID",
        "toTable": "d_businessunit"
      },
      {
        "name": "440d22db-d0f4-a99a-5fc1-0f7649b18519",
        "fromColumn": "FK_BusinessUnitID",
        "fromTable": "f_purchaseorders",
        "toColumn": "BusinessUnitID",
        "toTable": "d_businessunit"
      },
      {
        "name": "977f7b9b-a61f-4624-94ae-82efdbbd2834",
        "fromColumn": "FK_SupplierID",
        "fromTable": "f_pricelist",
        "toColumn": "SupplierID",
        "toTable": "d_supplier"
      },
      {
        "name": "060c2458-7c8f-67a5-7639-67cf0fcef416",
        "fromColumn": "FK_BusinessUnitID",
        "fromTable": "f_budgets",
        "toColumn": "BusinessUnitID",
        "toTable": "d_businessunit"
      },
      {
        "name": "9c037f1a-5318-7aa2-d0c7-deea80000037",
        "fromColumn": "FK_CurrencyID",
        "fromTable": "f_salesinvoices",
        "toColumn": "CurrencyID",
        "toTable": "d_currency"
      },
      {
        "name": "17348ff1-42db-9f0b-c40b-535f70e5de30",
        "fromColumn": "FK_ShippingDateID",
        "fromTable": "f_salesorders",
        "toColumn": "DateID",
        "toTable": "d_shippingdate"
      },
      {
        "name": "c6297985-5420-8082-6614-2e2a7c08f717",
        "fromColumn": "FK_CustomerID",
        "fromTable": "f_inventorysnapshot",
        "toColumn": "CustomerID",
        "toTable": "d_customer"
      },
      {
        "name": "d3fb7f87-0efb-f87c-2648-b2803c8bc049",
        "fromColumn": "FK_SalesTeamID",
        "fromTable": "f_pricelist",
        "toColumn": "UserID",
        "toTable": "d_salesteam"
      },
      {
        "name": "9a262e98-d84a-87d9-c7b2-acaeee986d31",
        "fromColumn": "FK_SalesAreaID",
        "fromTable": "f_pricelist",
        "toColumn": "SalesAreaID",
        "toTable": "d_salesarea"
      },
      {
        "name": "d595a4bb-aef3-fc7a-0131-ce03e5f9588f",
        "fromColumn": "FK_ComahSubstanceID",
        "fromTable": "f_comahsnapshot",
        "toColumn": "ComahSubstanceID",
        "toTable": "d_comahsubstance"
      },
      {
        "name": "ad11016b-4c05-87ee-24da-2fe6048694d5",
        "fromColumn": "FK_ProductID",
        "fromTable": "f_comahsnapshot",
        "toColumn": "ProductID",
        "toTable": "d_product"
      },
      {
        "name": "2deec301-888d-50d2-9cff-6bf5852ce62f",
        "fromColumn": "FK_BusinessUnitID",
        "fromTable": "f_inventorysnapshot",
        "toColumn": "BusinessUnitID",
        "toTable": "d_businessunit"
      },
      {
        "name": "a28243b1-9241-ed93-6db1-6753c42b5b8e",
        "fromColumn": "FK_UnitID",
        "fromTable": "f_inventorysnapshot",
        "toColumn": "UnitID",
        "toTable": "d_unit"
      },
      {
        "name": "6480e293-a841-c75d-005b-a8bce59e4464",
        "fromColumn": "FK_ComahSubCategoryID",
        "fromTable": "f_comahsnapshot",
        "toColumn": "ComahSubCategoryID",
        "toTable": "d_comahsubcategory"
      },
      {
        "name": "5ab0dd92-4386-eb44-3896-dd727ae7a00e",
        "fromColumn": "FK_LimitsComahSubcategoryID",
        "fromTable": "f_comahlimits",
        "relyOnReferentialIntegrity": true,
        "toColumn": "ComahSubCategoryID",
        "toTable": "d_comahsubcategory"
      },
      {
        "name": "ffbb23fc-3bc2-e71a-1e05-8e4379b3a0aa",
        "fromColumn": "FK_LimitsComahSubstanceID",
        "fromTable": "f_comahlimits",
        "relyOnReferentialIntegrity": true,
        "toColumn": "ComahSubstanceID",
        "toTable": "d_comahsubstance"
      },
      {
        "name": "4e8aafb8-7621-154a-c8db-1e698b9c571d",
        "fromColumn": "FK_SalesTeamID",
        "fromTable": "f_salesorders",
        "toColumn": "UserID",
        "toTable": "d_salesteam"
      },
      {
        "name": "f048367f-9a58-80be-0983-5026c67ee3d9",
        "fromColumn": "FK_ProductID",
        "fromTable": "f_consignmentstock",
        "toColumn": "ProductID",
        "toTable": "d_product"
      },
      {
        "name": "e9be628a-4112-5b21-f63d-bf7852031d75",
        "fromColumn": "ProductID",
        "fromTable": "d_product",
        "toCardinality": "many",
        "toColumn": "FK_ProductID",
        "toTable": "b_externalitem"
      },
      {
        "name": "3a76b6ee-58a6-ac8b-cf84-012fd0e66e8b",
        "fromColumn": "FK_SupplierID",
        "fromTable": "b_externalitem",
        "toColumn": "SupplierID",
        "toTable": "d_supplier"
      }
    ],
    "roles": [
      {
        "name": "Admin",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "866f311060664ab5a458ac2667990ce8"
          }
        ],
        "modelPermission": "read"
      },
      {
        "name": "LegalEntity",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c587e347aa9f4684bcf423b21261ef2c"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "d_user",
            "filterExpression": "UPPER([Email]) == UPPER(USERPRINCIPALNAME())"
          }
        ]
      },
      {
        "name": "SalesHierarchy",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "d0a5670aa0fa47099ef26305275035bc"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "d_salesteam",
            "filterExpression": [
              "[Account Manager Flag] == TRUE() &&",
              "(UPPER([Email]) == UPPER(USERPRINCIPALNAME()) ||",
              "UPPER([Reports To Email]) == UPPER(USERPRINCIPALNAME()) ||",
              "Upper([Director Email]) == Upper(USERPRINCIPALNAME()))"
            ]
          }
        ]
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "f_exchangerates",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Exchange Rate Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "25f4fdb2-c03e-4598-8f2d-35238d6e62a7",
            "sourceColumn": "ExchangeRateType",
            "sourceLineageTag": "ExchangeRateType",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Exchange Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "0.0000",
            "lineageTag": "5018f892-85a6-4527-a760-c01967a37fa9",
            "sourceColumn": "ExchangeRate",
            "sourceLineageTag": "ExchangeRate",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Valid From",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "449fecc5-7f16-4ad8-a007-d5e95bac41f3",
            "sourceColumn": "ValidFrom",
            "sourceLineageTag": "ValidFrom",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "Valid To",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "6f9fc0ac-8e54-4c23-80d5-66f97e436292",
            "sourceColumn": "ValidTo",
            "sourceLineageTag": "ValidTo",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "FK_FromCurrencyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ab66ea97-b4dd-420a-8211-ad84bfc75636",
            "sourceColumn": "FK_FromCurrencyID",
            "sourceLineageTag": "FK_FromCurrencyID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_ToCurrencyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "13b24671-97de-4d48-bc6c-6dda9f865cea",
            "sourceColumn": "FK_ToCurrencyID",
            "sourceLineageTag": "FK_ToCurrencyID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8c827e4d-4e3e-434a-8fe1-4161622e8c65",
            "sourceColumn": "FK_DateID",
            "sourceLineageTag": "FK_DateID",
            "sourceProviderType": "bigint",
            "summarizeBy": "none"
          },
          {
            "name": "ExchangeRateNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3026c2cc-7161-4145-b657-106e8fa9a083",
            "sourceColumn": "ExchangeRateNaturalID",
            "sourceLineageTag": "ExchangeRateNaturalID",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "dd0c56d5-d420-49b7-9c68-865f60426893",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          },
          {
            "name": "IsHistory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "074f7082-ef50-441d-b186-c15309b7b910",
            "sourceColumn": "IsHistory",
            "sourceLineageTag": "IsHistory",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3a1375e8-e448-4077-bef9-149e71a9dcdf",
        "measures": [
          {
            "name": "Exchange Rate Value",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "AVERAGE('f_exchangerates'[Exchange Rate] )",
            "formatString": "#,0.0000",
            "lineageTag": "84255b7a-80e5-42a2-819a-6552fbe0b573"
          },
          {
            "name": "Exchange Rate Value (Today)",
            "description": "This measure is a derivative of Exchange Rate Value.",
            "displayFolder": "Exchange Rate Value",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "RETURN",
              "    CALCULATE (",
              "        [Exchange Rate Value],",
              "        'd_date'[Date] = CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "4f738ffe-7060-466e-882d-cba61743980f"
          },
          {
            "name": "Exchange Rate Value (Yesterday)",
            "description": "This measure is a derivative of Exchange Rate Value.",
            "displayFolder": "Exchange Rate Value",
            "expression": [
              "VAR YesterdayDate =",
              "    TODAY () - 1",
              "RETURN",
              "    CALCULATE (",
              "        [Exchange Rate Value],",
              "        'd_date'[Date] = YesterdayDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "dd54cd85-c0a6-4718-9cbb-1cc564b8997c"
          },
          {
            "name": "Exchange Rate Value (Today vs Yesterday) ARROW",
            "description": "This measure is a derivative of Exchange Rate Value.",
            "displayFolder": "Exchange Rate Value",
            "expression": "IF(f_exchangerates[Exchange Rate Value (Today)] > f_exchangerates[Exchange Rate Value (Yesterday)], UNICHAR(8593), IF(f_exchangerates[Exchange Rate Value (Today)] < f_exchangerates[Exchange Rate Value (Yesterday)], UNICHAR(8595), UNICHAR(45)))",
            "lineageTag": "21c17036-d9cf-4004-bb00-95474e9105ed"
          }
        ],
        "partitions": [
          {
            "name": "curated_f_exchangerates",
            "mode": "directLake",
            "source": {
              "entityName": "curated_f_exchangerates",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_f_exchangerates]"
      },
      {
        "name": "d_currency",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CurrencyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95d5f502-a02d-4e0a-b963-6d707c515cdb",
            "sourceColumn": "CurrencyID",
            "sourceLineageTag": "CurrencyID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Currency Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ac78e04-59ed-4799-9312-14260907227c",
            "sourceColumn": "CurrencyName",
            "sourceLineageTag": "CurrencyName",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Currency Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "05bc1d26-35f4-4481-a673-ea68f2411064",
            "sourceColumn": "CurrencyCode",
            "sourceLineageTag": "CurrencyCode",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Currency Symbol",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "321f4596-9422-44b4-bb93-76f68e1602a0",
            "sourceColumn": "CurrencySymbol",
            "sourceLineageTag": "CurrencySymbol",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "CurrencyNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fdf93206-cee9-435e-acb4-4f1168cdc414",
            "sourceColumn": "CurrencyNaturalID",
            "sourceLineageTag": "CurrencyNaturalID",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "f42fdc8e-86df-4125-a05c-895a0d1d9be5",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ddf917b5-18ed-4a5c-86c7-05fb6e939e28",
        "partitions": [
          {
            "name": "curated_d_currency",
            "mode": "directLake",
            "source": {
              "entityName": "curated_d_currency",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_currency]"
      },
      {
        "name": "d_salesarea",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SalesAreaID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0a0cc8c5-dbfa-4809-aad7-a4cabd418793",
            "sourceColumn": "SalesAreaID",
            "sourceLineageTag": "SalesAreaID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b14d73b-f540-491d-bbe1-e8e29cebad85",
            "sourceColumn": "SalesArea",
            "sourceLineageTag": "SalesArea",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "c4ed179d-3604-4851-a16d-4b6aaa12bcb2",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          },
          {
            "name": "SalesAreaNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b508fd1-ed6a-4110-92b4-f2de17d00d4e",
            "sourceColumn": "SalesAreaNaturalID",
            "sourceLineageTag": "SalesAreaNaturalID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cf64dc20-09b5-4182-a4ee-266bdb6ffffa",
        "partitions": [
          {
            "name": "curated_d_salesarea",
            "mode": "directLake",
            "source": {
              "entityName": "curated_d_salesarea",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_salesarea]"
      },
      {
        "name": "d_user",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "UserID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65ec96f4-db76-4e81-a8c8-a6d77a851d36",
            "sourceColumn": "UserID",
            "sourceLineageTag": "UserID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Full Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1502cd53-419f-4d0a-8891-38a564ede3b6",
            "sourceColumn": "FullName",
            "sourceLineageTag": "FullName",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac7534e1-f98a-46db-8abc-3118ce7e2bc7",
            "sourceColumn": "Email",
            "sourceLineageTag": "Email",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Account Manager Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "d5bdbc7d-a9f5-41c0-9fe2-f75631bf5841",
            "sourceColumn": "AccountManagerFlag",
            "sourceLineageTag": "AccountManagerFlag",
            "sourceProviderType": "bit",
            "summarizeBy": "none"
          },
          {
            "name": "Reports To",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c79b143-ade7-47ef-9486-571813dbcd33",
            "sourceColumn": "ReportsTo",
            "sourceLineageTag": "ReportsTo",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Reports To Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b8515ae3-6c8a-4b79-b631-b65e64025de2",
            "sourceColumn": "ReportsToEmail",
            "sourceLineageTag": "ReportsToEmail",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Director",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ee1d766-1a38-4f29-93dd-30da861c65c1",
            "sourceColumn": "Director",
            "sourceLineageTag": "Director",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Director Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d917573-e94a-498b-8719-4aa17dd675d7",
            "sourceColumn": "DirectorEmail",
            "sourceLineageTag": "DirectorEmail",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "38197c58-91af-40b2-9baa-0881c4406461",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          },
          {
            "name": "UserNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "df844619-3bf0-48c7-8700-12e81138e36f",
            "sourceColumn": "UserNaturalID",
            "sourceLineageTag": "UserNaturalID",
            "summarizeBy": "none"
          },
          {
            "name": "WorkerNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6840781e-3a90-47c4-ba22-df4889c3a639",
            "sourceColumn": "WorkerNaturalID",
            "sourceLineageTag": "WorkerNaturalID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9e6758c7-9a97-4734-afaa-67dcaa6f092d",
        "partitions": [
          {
            "name": "curated_d_user",
            "mode": "directLake",
            "source": {
              "entityName": "curated_d_user",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_user]"
      },
      {
        "name": "d_comahcategory",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ComahCategoryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3029bd4f-4422-49b7-b836-7c2e71c0befd",
            "sourceColumn": "ComahCategoryID",
            "sourceLineageTag": "ComahCategoryID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Comah Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "847c710e-d4ed-422d-91ac-79818262e913",
            "sourceColumn": "ComahCategory",
            "sourceLineageTag": "ComahCategory",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c0955ca7-364b-46f9-b444-0f061efc1ff7",
        "partitions": [
          {
            "name": "curated_d_comahcategory",
            "mode": "directLake",
            "source": {
              "entityName": "curated_d_comahcategory",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_comahcategory]"
      },
      {
        "name": "f_salesinvoices",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SalesInvoiceID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f41ff8c-c2b9-43c3-91e2-59450a2d2770",
            "sourceColumn": "SalesInvoiceID",
            "sourceLineageTag": "SalesInvoiceID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "369bab4a-48bd-484b-a882-a59f17d217e4",
            "sourceColumn": "Quantity",
            "sourceLineageTag": "Quantity",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "41858abe-56a2-4981-aff5-f57b6f29c3fa",
            "sourceColumn": "TotalAmount",
            "sourceLineageTag": "TotalAmount",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost Per Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "dd78c5d0-f547-4712-8aec-baba91ed4915",
            "sourceColumn": "CostPerUnit",
            "sourceLineageTag": "CostPerUnit",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Product Weight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "87d0028a-d2b9-4138-9430-c68e27f0c123",
            "sourceColumn": "ProductWeight",
            "sourceLineageTag": "ProductWeight",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "FK_ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "68bc5eed-ca41-4b5a-a6a9-3695247180e7",
            "sourceColumn": "FK_ProductID",
            "sourceLineageTag": "FK_ProductID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_UnitID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "01b77955-d31a-4ea5-a2df-212645237e04",
            "sourceColumn": "FK_UnitID",
            "sourceLineageTag": "FK_UnitID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "12608579-7548-4120-bcfa-e3871cb7994b",
            "sourceColumn": "FK_CustomerID",
            "sourceLineageTag": "FK_CustomerID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_LegalEntityID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "41aba450-d7ad-4242-b4f5-edf7c201974b",
            "sourceColumn": "FK_LegalEntityID",
            "sourceLineageTag": "FK_LegalEntityID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ead60349-aa01-411d-ad73-508128decffc",
            "sourceColumn": "FK_DateID",
            "sourceLineageTag": "FK_DateID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_BusinessUnitID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "96ad5316-d742-4ad7-aa92-eef23581ab59",
            "sourceColumn": "FK_BusinessUnitID",
            "sourceLineageTag": "FK_BusinessUnitID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_SalesTeamID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1825bfeb-a3e5-404d-b0bc-d3ff098d641a",
            "sourceColumn": "FK_SalesTeamID",
            "sourceLineageTag": "FK_SalesTeamID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_DeliveryAddressID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b5dfccf9-711a-45b0-b15d-96f291853e40",
            "sourceColumn": "FK_DeliveryAddressID",
            "sourceLineageTag": "FK_DeliveryAddressID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_SupplierID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0e9a6951-9e0f-4bfb-af9f-0faee2b3a884",
            "sourceColumn": "FK_SupplierID",
            "sourceLineageTag": "FK_SupplierID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_InvoiceAddressID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7548b9f5-f122-4622-a22c-c14b103a020c",
            "sourceColumn": "FK_InvoiceAddressID",
            "sourceLineageTag": "FK_InvoiceAddressID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "59413244-87e2-4c48-9068-b2ff1249eac4",
            "sourceColumn": "Volume",
            "sourceLineageTag": "Volume",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Margin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "5a286499-e85d-4bdf-92a3-cfdef632a37b",
            "sourceColumn": "TotalMargin",
            "sourceLineageTag": "TotalMargin",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Amount_ G B P",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "71d15053-88f3-41c9-a49d-d02863c73177",
            "sourceColumn": "TotalAmount_GBP",
            "sourceLineageTag": "TotalAmount_GBP",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Margin_ G B P",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "df36aa1c-60de-47cb-b954-feef06ece779",
            "sourceColumn": "TotalMargin_GBP",
            "sourceLineageTag": "TotalMargin_GBP",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Amount_ E U R",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "60655eb5-1841-4a8d-a648-221480565c24",
            "sourceColumn": "TotalAmount_EUR",
            "sourceLineageTag": "TotalAmount_EUR",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Margin_ E U R",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "1b07dd2e-3202-4faa-84fe-4d29f5b7c712",
            "sourceColumn": "TotalMargin_EUR",
            "sourceLineageTag": "TotalMargin_EUR",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Amount_ U S D",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "16acbcf1-346a-4190-9ee8-643fd5c36efe",
            "sourceColumn": "TotalAmount_USD",
            "sourceLineageTag": "TotalAmount_USD",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Margin_ U S D",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "e66e04d2-3a57-4892-b25f-300e289c7682",
            "sourceColumn": "TotalMargin_USD",
            "sourceLineageTag": "TotalMargin_USD",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "FK_SalesAreaID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f81a1152-2aee-45c8-abb7-04fe40439022",
            "sourceColumn": "FK_SalesAreaID",
            "sourceLineageTag": "FK_SalesAreaID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_CurrencyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "67c53ae0-9a09-42ad-a9b2-78627cbd2aff",
            "sourceColumn": "FK_CurrencyID",
            "sourceLineageTag": "FK_CurrencyID",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "0a347624-b4d8-46f2-be03-eb6b084524b1",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          },
          {
            "name": "SalesInvoiceLineNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bebadc9f-480a-4f97-b22c-94b0923b169f",
            "sourceColumn": "SalesInvoiceLineNaturalID",
            "sourceLineageTag": "SalesInvoiceLineNaturalID",
            "summarizeBy": "none"
          },
          {
            "name": "TotalCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "fba3a6e3-93e8-4e3b-86a5-432a1e3fc2e8",
            "sourceColumn": "TotalCost",
            "sourceLineageTag": "TotalCost",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalCost_EUR",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "ac22cea0-ac79-43a8-a5ec-cc30bae11e32",
            "sourceColumn": "TotalCost_EUR",
            "sourceLineageTag": "TotalCost_EUR",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalCost_GBP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "0aa223c6-09bd-45cc-b26e-f46bf4160d15",
            "sourceColumn": "TotalCost_GBP",
            "sourceLineageTag": "TotalCost_GBP",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalCost_USD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "4ebfbdd8-3d99-4751-8d1d-cf9fcca2f4b4",
            "sourceColumn": "TotalCost_USD",
            "sourceLineageTag": "TotalCost_USD",
            "summarizeBy": "sum"
          },
          {
            "name": "VolumeKG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "888fbf9b-f5aa-45e3-aa0b-04c2c1216dea",
            "sourceColumn": "VolumeKG",
            "sourceLineageTag": "VolumeKG",
            "sourceProviderType": "real",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrderID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b220497f-289c-4dd2-801f-224ec100c057",
            "sourceColumn": "SalesOrderID",
            "sourceLineageTag": "SalesOrderID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "ModifiedOn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "lineageTag": "5b901a6a-f425-406d-979d-fb654ba4aacf",
            "sourceColumn": "ModifiedOn",
            "sourceLineageTag": "ModifiedOn",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "751220dd-b060-4d03-8910-b7b5ca081173",
        "measures": [
          {
            "name": "Average Invoice Value",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'S_Currency'[Currency], \"None\" ),",
              "    \"GBP\", AVERAGE ( f_salesinvoices[Total Amount_ G B P] ),",
              "    \"EUR\", AVERAGE ( f_salesinvoices[Total Amount_ E U R] ),",
              "    \"USD\", AVERAGE ( f_salesinvoices[Total Amount_ U S D] ),",
              "    AVERAGE ( f_salesinvoices[Total Amount] )",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "a974a75f-49b0-4b6e-97a2-25457a3d9e3b"
          },
          {
            "name": "Average Invoice Volume",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(AVERAGE ( f_salesinvoices[Volume] ), FILTER(d_unit, d_unit[Unit] <> \"EACH\"))",
            "formatString": "#,0.00",
            "lineageTag": "adc99e9c-a16d-4e65-8331-34cc8ab16f6f"
          },
          {
            "name": "Average Margin Value",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'S_Currency'[Currency], \"None\" ),",
              "    \"GBP\", AVERAGE ( f_salesinvoices[Total Margin_ G B P] ),",
              "    \"EUR\", AVERAGE ( f_salesinvoices[Total Margin_ E U R] ),",
              "    \"USD\", AVERAGE ( f_salesinvoices[Total Margin_ U S D] ),",
              "    AVERAGE ( f_salesinvoices[Total Margin] )",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "7ed8c7c1-91a2-4e57-8df1-217c622881f2"
          },
          {
            "name": "Margin %",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE ( f_salesinvoices[Sales Margin], f_salesinvoices[Sales Invoiced] ) * 100",
            "formatString": "#,0.00",
            "lineageTag": "b73ee800-853e-4fbb-af53-6572d3035932"
          },
          {
            "name": "No. Invoices",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DISTINCTCOUNT ( f_salesinvoices[SalesInvoiceID] )",
            "formatString": "#,0",
            "lineageTag": "90a79684-26f4-4fc7-ab9c-55831ddbaffb"
          },
          {
            "name": "Sales Invoiced",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'S_Currency'[Currency], \"None\" ),",
              "    \"GBP\", SUM ( f_salesinvoices[Total Amount_ G B P] ),",
              "    \"EUR\", SUM ( f_salesinvoices[Total Amount_ E U R] ),",
              "    \"USD\", SUM ( f_salesinvoices[Total Amount_ U S D] ),",
              "    SUM ( f_salesinvoices[Total Amount] )",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "11abb2dd-1f41-4063-ab84-0a21719393a9"
          },
          {
            "name": "Sales Margin",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'S_Currency'[Currency], \"None\" ),",
              "    \"GBP\", SUM ( f_salesinvoices[Total Margin_ G B P] ),",
              "    \"EUR\", SUM ( f_salesinvoices[Total Margin_ E U R] ),",
              "    \"USD\", SUM ( f_salesinvoices[Total Margin_ U S D] ),",
              "    SUM ( f_salesinvoices[Total Margin] )",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "0456a4fe-a120-495f-b699-a1548f6e37ed"
          },
          {
            "name": "Sales Volume",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(SUM ( f_salesinvoices[Volume] ), FILTER(d_unit, d_unit[Unit] <> \"EACH\"))",
            "formatString": "#,0.00",
            "lineageTag": "80654108-a240-4341-a2b8-8d4ff75be656"
          },
          {
            "name": "Total Cost",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'S_Currency'[Currency], \"None\" ),",
              "    \"GBP\", SUM ( f_salesinvoices[TotalCost_GBP] ),",
              "    \"EUR\", SUM ( f_salesinvoices[TotalCost_EUR] ),",
              "    \"USD\", SUM ( f_salesinvoices[TotalCost_USD] ),",
              "    SUM ( f_salesinvoices[TotalCost] )",
              ")",
              " ",
              ""
            ],
            "formatString": "#,0.00",
            "lineageTag": "a197932f-d619-4c16-8265-412fcdfb2206"
          },
          {
            "name": "No. Customers By Country",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE (",
              "    DISTINCTCOUNT ( f_salesinvoices[FK_CustomerID] ),",
              "    ALLEXCEPT ( d_invoiceaddress, d_invoiceaddress[Country] )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "368ac97a-7fe2-491d-9443-e0c428c36eed"
          },
          {
            "name": "No. Customers By Sales Area",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE (",
              "    DISTINCTCOUNT ( f_salesinvoices[FK_SalesTeamID] ),",
              "    ALLEXCEPT ( d_invoiceaddress, d_invoiceaddress[Country] )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "65dd4f70-9c1a-4438-90ae-5a9d15b10074"
          },
          {
            "name": "Cost Per Unit (Today)",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "RETURN",
              "    CALCULATE (",
              "        SUM ( f_salesinvoices[Cost Per Unit] ),",
              "        'd_date'[Date] = CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatString": "#,0.00",
            "lineageTag": "1e4723aa-dc6b-4dc1-968a-44f2a446b11e"
          },
          {
            "name": "Cost Per Unit (MTD)",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR StartdateMonth =",
              "    DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 )",
              "RETURN",
              "    CALCULATE (",
              "        SUM ( f_salesinvoices[Cost Per Unit] ),",
              "        'd_date'[Date] >= StartdateMonth",
              "            && 'd_date'[Date] <= CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatString": "#,0.00",
            "lineageTag": "9457e3f3-9639-4d4b-bd1c-48fc429971f6"
          },
          {
            "name": "Sum of Total Cost_GBP",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-GB\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM ( f_salesinvoices[TotalCost_GBP] )",
            "formatString": "\"£\"#,0;-\"£\"#,0;\"£\"#,0",
            "lineageTag": "9584cdb4-99b7-4ba4-9f16-2f9a4fefa973"
          },
          {
            "name": "Sum of Quantity",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM ( f_salesinvoices[Quantity] )",
            "formatString": "#,0",
            "lineageTag": "3b3714b0-e2a4-4fb5-8a65-1b5ea9ed5c26"
          },
          {
            "name": "Sum of Product Weight",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM ( f_salesinvoices[Product Weight] )",
            "formatString": "#,0.00",
            "lineageTag": "a4a9f601-352d-4e50-97b0-e52414e14e14"
          },
          {
            "name": "Sum of Total Amount_GBP",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-GB\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM ( f_salesinvoices[Total Amount_ G B P] )",
            "formatString": "\"£\"#,0;-\"£\"#,0;\"£\"#,0",
            "lineageTag": "8a7a7fda-f0e8-4e65-a03f-9b10d5266947"
          },
          {
            "name": "Sum of Total Margin_GBP",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-GB\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM ( f_salesinvoices[Total Margin_ G B P] )",
            "formatString": "\"£\"#,0;-\"£\"#,0;\"£\"#,0",
            "lineageTag": "6cffc4d5-9140-4126-99dc-3d96afefc6ca"
          },
          {
            "name": "Sum of Total Amount_USD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM ( f_salesinvoices[Total Amount_ U S D] )",
            "formatString": "\"$\"#,0;-\"$\"#,0;\"$\"#,0",
            "lineageTag": "be07a45d-b1ad-4742-8336-ff60f9b9f1e2"
          },
          {
            "name": "Sum of Total Cost_USD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM ( f_salesinvoices[TotalCost_USD] )",
            "formatString": "\"$\"#,0;-\"$\"#,0;\"$\"#,0",
            "lineageTag": "40a7b69a-5213-46e8-abda-c0249f171bf8"
          },
          {
            "name": "Sum of Total Margin_EUR",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM ( f_salesinvoices[Total Margin_ E U R] )",
            "formatString": "\"€\"#,0;-\"€\"#,0;\"€\"#,0",
            "lineageTag": "4e62408c-f2a1-439d-8bc0-4a7567f1e2fc"
          },
          {
            "name": "Margin % GBP",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE ( [Sum of Total Margin_GBP], [Sum of Total Amount_GBP] )",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "bbdc9dfd-de7c-45f6-a292-ebd51dacf6ab"
          },
          {
            "name": "SP/T_GBP",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE ( [Sum of Total Amount_GBP], [Volume T (SI)] )",
            "formatString": "\"£\"#,0;-\"£\"#,0;\"£\"#,0",
            "lineageTag": "5f7570ce-e22c-42b5-9003-b1ea0c2698ab"
          },
          {
            "name": "SP/T_USD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE ( [Sum of Total Amount_USD], [Volume T (SI)] )",
            "formatString": "\"$\"#,0;-\"$\"#,0;\"$\"#,0",
            "lineageTag": "587abd65-5a57-4957-a6ea-b37a0fad35ec"
          },
          {
            "name": "Sum of Total Amount_EUR",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM ( f_salesinvoices[Total Amount_ E U R] )",
            "formatString": "\"€\"#,0;-\"€\"#,0;\"€\"#,0",
            "lineageTag": "3fa6e632-71e5-44c2-95a7-70e479dd6620"
          },
          {
            "name": "Sum of Total Cost_EUR",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM ( f_salesinvoices[TotalCost_EUR] )",
            "formatString": "\"€\"#,0;-\"€\"#,0;\"€\"#,0",
            "lineageTag": "7806f6d8-7d6e-4c42-a32b-93ca7720a450"
          },
          {
            "name": "Sum of Total Margin_USD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM ( f_salesinvoices[Total Margin_ U S D] )",
            "formatString": "\"$\"#,0;-\"$\"#,0;\"$\"#,0",
            "lineageTag": "2c7c84dc-f383-4a3b-aff1-e2ce00f6a611"
          },
          {
            "name": "SP/T_EUR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE ( [Sum of Total Amount_EUR], [Volume T (SI)] )",
            "formatString": "\"€\"#,0;-\"€\"#,0;\"€\"#,0",
            "lineageTag": "73ca0f84-5795-4dc9-ba93-c8ecc3239330"
          },
          {
            "name": "Cost/T_GBP",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE ( [Sum of Total Cost_GBP], [Volume T (SI)] )",
            "formatString": "\"£\"#,0;-\"£\"#,0;\"£\"#,0",
            "lineageTag": "26e64127-cc99-4f1b-aa0c-1b704a985b27"
          },
          {
            "name": "Cost/T_USD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE ( [Sum of Total Cost_USD], [Volume T (SI)] )",
            "formatString": "\"$\"#,0;-\"$\"#,0;\"$\"#,0",
            "lineageTag": "53428cee-b33c-4e75-a522-21a3a65da91d"
          },
          {
            "name": "Cost/T_EUR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE ( [Sum of Total Cost_EUR], [Volume T (SI)] )",
            "formatString": "\"€\"#,0;-\"€\"#,0;\"€\"#,0",
            "lineageTag": "57b5df36-9e72-40b9-9e13-5d2e1ca7fe75"
          },
          {
            "name": "Margin/T_GBP",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE ( [Sum of Total Margin_GBP], [Volume T (SI)] )",
            "formatString": "\"£\"#,0;-\"£\"#,0;\"£\"#,0",
            "lineageTag": "24644eb3-364f-4723-9f10-61e8fd4eff51"
          },
          {
            "name": "Margin/T_USD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE ( [Sum of Total Margin_USD], [Volume T (SI)] )",
            "formatString": "\"$\"#,0;-\"$\"#,0;\"$\"#,0",
            "lineageTag": "35ce07a6-1c19-4091-b225-69c828231465"
          },
          {
            "name": "Margin/T_EUR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE ( [Sum of Total Margin_EUR], [Volume T (SI)] )",
            "formatString": "\"€\"#,0;-\"€\"#,0;\"€\"#,0",
            "lineageTag": "69f30bd5-7fc3-4065-b78d-2c8961f68f84"
          },
          {
            "name": "No. Customers By Product (Invoices)",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE (",
              "    DISTINCTCOUNT ( f_salesinvoices[FK_CustomerID] ),",
              "    ALLEXCEPT ( d_product, d_product[Product] )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "0dae3741-eb44-4c17-a8ab-27e41860b7c0"
          },
          {
            "name": "12-Month Average Sales",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "VAR Last12Months =",
              "    DATESINPERIOD ( D_Date[Date], TODAY (), -12, MONTH )",
              "VAR TotalSalesLast12Months =",
              "    CALCULATE (",
              "        [Sales Invoiced],",
              "        Last12Months,",
              "        REMOVEFILTERS ( D_Date[Year], D_Date[Financial Year] )",
              "    )",
              "RETURN",
              "    DIVIDE ( TotalSalesLast12Months, 12 )"
            ],
            "formatString": "#,0.00",
            "lineageTag": "c4817aa0-6e00-4b8e-be4c-3bcd71e0bb1f"
          },
          {
            "name": "12-Month Average Sales per Sales Area",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE ( [12-Month Average Sales], DISTINCTCOUNT ( d_salesarea[Sales Area] ) )",
            "formatString": "#,0.00",
            "lineageTag": "1b86e171-3b95-4660-b828-b80ef69c5277"
          },
          {
            "name": "Sales Area Performance",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "DIVIDE (",
              "    [12-Month Average Sales per Sales Area] - [12-Month Average Sales],",
              "    [12-Month Average Sales]",
              ") * 100"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b33e7a6c-c5f3-4c1f-8e62-944d6a708af3"
          },
          {
            "name": "12-Month Average Sales (No Area Filter)",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "VAR Last12Months =",
              "    DATESINPERIOD ( D_Date[Date], TODAY (), -12, MONTH )",
              "VAR TotalSalesLast12Months =",
              "    CALCULATE (",
              "        [Sales Invoiced],",
              "        Last12Months,",
              "        REMOVEFILTERS ( D_Date[Year], D_Date[Financial Year] ),",
              "        REMOVEFILTERS ( d_salesarea[Sales Area] )",
              "    )",
              "VAR DistinctSalesAreas =",
              "    CALCULATE (",
              "        DISTINCTCOUNT ( d_salesarea[Sales Area] ),",
              "        REMOVEFILTERS ( d_salesarea[Sales Area] )",
              "    )",
              "RETURN",
              "    DIVIDE ( TotalSalesLast12Months, 12 * DistinctSalesAreas )"
            ],
            "formatString": "#,0.00",
            "lineageTag": "3f78db87-04ff-4da6-961b-4b11c6cb7634"
          },
          {
            "name": "12-Month Average Sales (No Rep Filter)",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "VAR Last12Months =",
              "    DATESINPERIOD ( D_Date[Date], TODAY (), -12, MONTH )",
              "VAR TotalSalesLast12Months =",
              "    CALCULATE (",
              "        [Sales Invoiced],",
              "        Last12Months,",
              "        REMOVEFILTERS ( D_Date[Year], D_Date[Financial Year] ),",
              "        REMOVEFILTERS ( d_salesteam[Full Name] )",
              "    )",
              "VAR DistinctSalesReps =",
              "    CALCULATE (",
              "        DISTINCTCOUNT ( d_salesteam[Full Name] ),",
              "        REMOVEFILTERS ( d_salesteam[Full Name] )",
              "    )",
              "RETURN",
              "    DIVIDE ( TotalSalesLast12Months, 12 * DistinctSalesReps )"
            ],
            "formatString": "#,0.00",
            "lineageTag": "2ca3f32f-b73f-48f0-ad7c-407844678222"
          },
          {
            "name": "12-Month Average Sales per Sales Rep",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE ( [12-Month Average Sales], DISTINCTCOUNT ( d_salesteam[UserID] ) )",
            "formatString": "#,0.00",
            "lineageTag": "2f590478-db57-4bf7-bbc0-0f85e3bea7a6"
          },
          {
            "name": "Sales Area Performance Against Total Avg.",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "DIVIDE (",
              "    [12-Month Average Sales] - [12-Month Average Sales (No Area Filter)],",
              "    [12-Month Average Sales (No Area Filter)]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8ce6dcb0-0a23-4623-a2a8-3dfc79a0edbe"
          },
          {
            "name": "Sales Rep Performance Against Total Avg.",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "DIVIDE (",
              "    [12-Month Average Sales] - [12-Month Average Sales (No Rep Filter)],",
              "    [12-Month Average Sales (No Rep Filter)]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "174c35d5-88fc-4fa8-89a5-f3c9176714f1"
          },
          {
            "name": "Volume T (Today)",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE ( [Sales Volume (Today)], 1000 )",
            "formatString": "#,0.00",
            "lineageTag": "1fae7d55-9a22-4b13-bb59-573c24075bc1"
          },
          {
            "name": "Volume T (MTD)",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE ( [Sales Volume (MTD)], 1000 )",
            "formatString": "#,0.00",
            "lineageTag": "0e28d4d7-9540-487c-bacb-fa9a88fe5752"
          },
          {
            "name": "Volume T (SI)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": "CALCULATE(DIVIDE(SUM(f_salesinvoices[Volume]), 1000), FILTER(d_unit, d_unit[Unit] <> \"EACH\"))",
            "lineageTag": "b0e8917b-28be-4c03-8e35-2364f441414d"
          },
          {
            "name": "($)Rate",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE([Sum of Total Amount_USD],[Sum of Total Amount_GBP])",
            "formatString": "0.0000",
            "lineageTag": "bf02f389-1f79-4350-beb0-5988d0d42210"
          },
          {
            "name": "(€)Rate",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE([Sum of Total Amount_EUR],[Sum of Total Amount_GBP])",
            "formatString": "0.0000",
            "lineageTag": "c2b0b7a3-e107-4bc3-8399-d4e0f4679bbc"
          },
          {
            "name": "Sales Invoiced (Today)",
            "description": "This measure is a derivative of Sales Invoiced.",
            "displayFolder": "Sales Invoiced",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "RETURN",
              "    CALCULATE (",
              "        [Sales Invoiced],",
              "        'd_date'[Date] = CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "04af343a-1525-4fdf-a810-a8724bacc7e4"
          },
          {
            "name": "Sales Invoiced (Yesterday)",
            "description": "This measure is a derivative of Sales Invoiced.",
            "displayFolder": "Sales Invoiced",
            "expression": [
              "VAR YesterdayDate =",
              "    TODAY () - 1",
              "RETURN",
              "    CALCULATE (",
              "        [Sales Invoiced],",
              "        'd_date'[Date] = YesterdayDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "5e76ff8f-db26-49ff-9cdc-3569e66e0aa9"
          },
          {
            "name": "Sales Invoiced (MTD)",
            "description": "This measure is a derivative of Sales Invoiced.",
            "displayFolder": "Sales Invoiced",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR StartdateMonth =",
              "    DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 )",
              "RETURN",
              "    CALCULATE (",
              "        [Sales Invoiced],",
              "        'd_date'[Date] >= StartdateMonth",
              "            && 'd_date'[Date] <= CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "2f6449da-3988-4522-9dfd-a061734967b8"
          },
          {
            "name": "Sales Invoiced (PMTD)",
            "description": "This measure is a derivative of Sales Invoiced.",
            "displayFolder": "Sales Invoiced",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR DaysInMonthSoFar =",
              "    DAY ( CurrentDate )",
              "VAR StartOfPriorMonth =",
              "    EDATE ( DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 ), -1 )",
              "VAR EndOfPriorMonth = StartOfPriorMonth + DaysInMonthSoFar - 1",
              "RETURN",
              "    CALCULATE (",
              "        [Sales Invoiced],",
              "        'd_date'[Date] >= StartOfPriorMonth",
              "            && 'd_date'[Date] <= EndOfPriorMonth,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "171e8e10-ea8c-475f-a8e3-ecc4028ab9fb"
          },
          {
            "name": "Sales Invoiced (YTD)",
            "description": "This measure is a derivative of Sales Invoiced.",
            "displayFolder": "Sales Invoiced",
            "expression": "[Sales Invoiced]",
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "f3cbd7ab-2b6c-42ff-9098-c96365061914"
          },
          {
            "name": "Sales Invoiced (PYTD)",
            "description": "This measure is a derivative of Sales Invoiced.",
            "displayFolder": "Sales Invoiced",
            "expression": [
              "CALCULATE (",
              "    [Sales Invoiced],",
              "    REMOVEFILTERS ( d_date ),",
              "    FILTER (",
              "        DATEADD ( d_date[Date], -1, YEAR ),",
              "        d_date[Date]",
              "            <= DATE ( YEAR ( TODAY () - 1 ), MONTH ( TODAY () ), DAY ( TODAY () ) )",
              "    )",
              ")"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "8370f5e9-7b3a-4671-bf21-e390fbfc1375"
          },
          {
            "name": "Sales Invoiced (Last Month)",
            "description": "This measure is a derivative of Sales Invoiced.",
            "displayFolder": "Sales Invoiced",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR StartOfLastMonth =",
              "    EOMONTH ( CurrentDate, -2 ) + 1",
              "VAR EndOfLastMonth =",
              "    EOMONTH ( CurrentDate, -1 )",
              "RETURN",
              "    CALCULATE (",
              "        [Sales Invoiced],",
              "        'd_date'[Date] >= StartOfLastMonth",
              "            && 'd_date'[Date] <= EndOfLastMonth,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "e8e7ec96-8610-4952-88af-c2b1311b4368"
          },
          {
            "name": "Sales Margin (Today)",
            "description": "This measure is a derivative of Sales Margin.",
            "displayFolder": "Sales Margin",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "RETURN",
              "    CALCULATE (",
              "        [Sales Margin],",
              "        'd_date'[Date] = CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "4b48ebda-224a-4058-b8f3-4ad21d6de9dd"
          },
          {
            "name": "Sales Margin (Yesterday)",
            "description": "This measure is a derivative of Sales Margin.",
            "displayFolder": "Sales Margin",
            "expression": [
              "VAR YesterdayDate =",
              "    TODAY () - 1",
              "RETURN",
              "    CALCULATE (",
              "        [Sales Margin],",
              "        'd_date'[Date] = YesterdayDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "ad26624f-cf74-4646-a018-2dddef36ba07"
          },
          {
            "name": "Sales Margin (MTD)",
            "description": "This measure is a derivative of Sales Margin.",
            "displayFolder": "Sales Margin",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR StartdateMonth =",
              "    DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 )",
              "RETURN",
              "    CALCULATE (",
              "        [Sales Margin],",
              "        'd_date'[Date] >= StartdateMonth",
              "            && 'd_date'[Date] <= CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "9006b1a9-32d4-44a9-867f-d2f88e6c0a7a"
          },
          {
            "name": "Sales Margin (PMTD)",
            "description": "This measure is a derivative of Sales Margin.",
            "displayFolder": "Sales Margin",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR DaysInMonthSoFar =",
              "    DAY ( CurrentDate )",
              "VAR StartOfPriorMonth =",
              "    EDATE ( DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 ), -1 )",
              "VAR EndOfPriorMonth = StartOfPriorMonth + DaysInMonthSoFar - 1",
              "RETURN",
              "    CALCULATE (",
              "        [Sales Margin],",
              "        'd_date'[Date] >= StartOfPriorMonth",
              "            && 'd_date'[Date] <= EndOfPriorMonth,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "c3c38f1b-b219-4e84-997a-de720f5d34cf"
          },
          {
            "name": "Sales Margin (YTD)",
            "description": "This measure is a derivative of Sales Margin.",
            "displayFolder": "Sales Margin",
            "expression": "[Sales Margin]",
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "4c904e31-9ffc-478d-8e54-0c6559f825f0"
          },
          {
            "name": "Sales Margin (PYTD)",
            "description": "This measure is a derivative of Sales Margin.",
            "displayFolder": "Sales Margin",
            "expression": [
              "CALCULATE (",
              "    [Sales Margin],",
              "    REMOVEFILTERS ( d_date ),",
              "    FILTER (",
              "        DATEADD ( d_date[Date], -1, YEAR ),",
              "        d_date[Date]",
              "            <= DATE ( YEAR ( TODAY () - 1 ), MONTH ( TODAY () ), DAY ( TODAY () ) )",
              "    )",
              ")"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "9490034a-4d4a-4449-ab4e-bd68bdeeea6d"
          },
          {
            "name": "Sales Volume (Today)",
            "description": "This measure is a derivative of Sales Volume.",
            "displayFolder": "Sales Volume",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "RETURN",
              "    CALCULATE (",
              "        [Sales Volume],",
              "        'd_date'[Date] = CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "d0c03442-fa55-4a91-995f-5626e630f157"
          },
          {
            "name": "Sales Volume (MTD)",
            "description": "This measure is a derivative of Sales Volume.",
            "displayFolder": "Sales Volume",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR StartdateMonth =",
              "    DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 )",
              "RETURN",
              "    CALCULATE (",
              "        [Sales Volume],",
              "        'd_date'[Date] >= StartdateMonth",
              "            && 'd_date'[Date] <= CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "d02f2f01-3f68-4524-9d24-1275055fb546"
          },
          {
            "name": "Sales Volume (YTD)",
            "description": "This measure is a derivative of Sales Volume.",
            "displayFolder": "Sales Volume",
            "expression": "[Sales Volume]",
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "995d98c7-58dd-4f2d-93b3-b7027ce8f7b3"
          },
          {
            "name": "Sales Volume (PYTD)",
            "description": "This measure is a derivative of Sales Volume.",
            "displayFolder": "Sales Volume",
            "expression": [
              "CALCULATE (",
              "    [Sales Volume],",
              "    REMOVEFILTERS ( d_date ),",
              "    FILTER (",
              "        DATEADD ( d_date[Date], -1, YEAR ),",
              "        d_date[Date]",
              "            <= DATE ( YEAR ( TODAY () - 1 ), MONTH ( TODAY () ), DAY ( TODAY () ) )",
              "    )",
              ")"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "87939f9f-85d2-461d-9479-2d2111fe9f90"
          },
          {
            "name": "No. Invoices (Today)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "This measure is a derivative of No. Invoices.",
            "displayFolder": "No. Invoices",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "RETURN",
              "    CALCULATE (",
              "        [No. Invoices],",
              "        'd_date'[Date] = CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "8cb0603c-38f7-4a9d-895e-70e6ee70c3e9"
          },
          {
            "name": "No. Invoices (MTD)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "This measure is a derivative of No. Invoices.",
            "displayFolder": "No. Invoices",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR StartdateMonth =",
              "    DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 )",
              "RETURN",
              "    CALCULATE (",
              "        [No. Invoices],",
              "        'd_date'[Date] >= StartdateMonth",
              "            && 'd_date'[Date] <= CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "9da54e3e-1012-40ee-aa7b-a168148f385c"
          },
          {
            "name": "Total Cost (Today)",
            "description": "This measure is a derivative of Total Cost.",
            "displayFolder": "Total Cost",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "RETURN",
              "    CALCULATE (",
              "        [Total Cost],",
              "        'd_date'[Date] = CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "cb78cc37-42ca-46e6-8f64-b83ce13a3f8e"
          },
          {
            "name": "Total Cost (MTD)",
            "description": "This measure is a derivative of Total Cost.",
            "displayFolder": "Total Cost",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR StartdateMonth =",
              "    DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 )",
              "RETURN",
              "    CALCULATE (",
              "        [Total Cost],",
              "        'd_date'[Date] >= StartdateMonth",
              "            && 'd_date'[Date] <= CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "7b66ca7a-5327-408d-a754-ff7e6ca9fd81"
          },
          {
            "name": "Margin % (Today)",
            "description": "This measure is a derivative of Margin %.",
            "displayFolder": "Margin %",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "RETURN",
              "    CALCULATE (",
              "        [Margin %],",
              "        'd_date'[Date] = CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "5fc42121-393d-4523-aa9e-2b5b8b419258"
          },
          {
            "name": "Margin % (MTD)",
            "description": "This measure is a derivative of Margin %.",
            "displayFolder": "Margin %",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR StartdateMonth =",
              "    DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 )",
              "RETURN",
              "    CALCULATE (",
              "        [Margin %],",
              "        'd_date'[Date] >= StartdateMonth",
              "            && 'd_date'[Date] <= CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "602c31bd-c70d-4eda-991d-00c765c5ffc0"
          },
          {
            "name": "Sales Invoiced (Today vs Yesterday)",
            "displayFolder": "Sales Invoiced",
            "expression": [
              "IF (",
              "    ISBLANK ( [Sales Invoiced (Yesterday)] ),",
              "    BLANK (),",
              "    DIVIDE (",
              "        [Sales Invoiced (Today)] - [Sales Invoiced (Yesterday)],",
              "        [Sales Invoiced (Yesterday)],",
              "        0",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "ad939800-a48f-43a7-bd5a-15b6b7a80492"
          },
          {
            "name": "Sales Invoiced (Today vs Yesterday) ARROW",
            "description": "This measure is a derivative of Sales Invoiced.",
            "displayFolder": "Sales Invoiced",
            "expression": [
              "IF (",
              "    [Sales Invoiced (Today vs Yesterday)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF (",
              "        [Sales Invoiced (Today vs Yesterday)] = 0,",
              "        UNICHAR ( 45 ),",
              "        UNICHAR ( 8595 )",
              "    )",
              ")"
            ],
            "lineageTag": "af4a0409-4c59-4050-9a9c-5c93a5c5e96a"
          },
          {
            "name": "Sales Invoiced (MTD vs PMTD)",
            "displayFolder": "Sales Invoiced",
            "expression": [
              "IF (",
              "    ISBLANK ( [Sales Invoiced (PMTD)] ),",
              "    BLANK (),",
              "    DIVIDE (",
              "        [Sales Invoiced (MTD)] - [Sales Invoiced (PMTD)],",
              "        [Sales Invoiced (PMTD)],",
              "        0",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "54f95122-05ad-453f-a32d-d9b6207aab0c"
          },
          {
            "name": "Sales Invoiced (MTD vs PMTD) ARROW",
            "description": "This measure is a derivative of Sales Invoiced.",
            "displayFolder": "Sales Invoiced",
            "expression": [
              "IF (",
              "    [Sales Invoiced (MTD vs PMTD)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF ( [Sales Invoiced (MTD vs PMTD)] = 0, UNICHAR ( 45 ), UNICHAR ( 8595 ) )",
              ")"
            ],
            "lineageTag": "e2615b5e-8885-485b-a7ec-5798a2dec267"
          },
          {
            "name": "Sales Invoiced (YTD vs PYTD)",
            "displayFolder": "Sales Invoiced",
            "expression": [
              "IF (",
              "    ISBLANK ( [Sales Invoiced (PYTD)] ),",
              "    BLANK (),",
              "    DIVIDE (",
              "        [Sales Invoiced (YTD)] - [Sales Invoiced (PYTD)],",
              "        [Sales Invoiced (PYTD)],",
              "        0",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "854b41b4-63d6-47e2-96d1-e2a5c56cb1b2"
          },
          {
            "name": "Sales Invoiced (YTD vs PYTD) ARROW",
            "description": "This measure is a derivative of Sales Invoiced.",
            "displayFolder": "Sales Invoiced",
            "expression": [
              "IF (",
              "    [Sales Invoiced (YTD vs PYTD)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF ( [Sales Invoiced (YTD vs PYTD)] = 0, UNICHAR ( 45 ), UNICHAR ( 8595 ) )",
              ")"
            ],
            "lineageTag": "fc6b1d13-3693-43b0-9639-f0747275fff7"
          },
          {
            "name": "Sales Margin (Today vs Yesterday)",
            "displayFolder": "Sales Margin",
            "expression": [
              "IF (",
              "    ISBLANK ( [Sales Margin (Yesterday)] ),",
              "    BLANK (),",
              "    DIVIDE (",
              "        [Sales Margin (Today)] - [Sales Margin (Yesterday)],",
              "        [Sales Margin (Yesterday)],",
              "        0",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "24ef713b-f3b1-4afb-ac26-a0580cc2673f"
          },
          {
            "name": "Sales Margin (Today vs Yesterday) ARROW",
            "description": "This measure is a derivative of Sales Margin.",
            "displayFolder": "Sales Margin",
            "expression": [
              "IF (",
              "    [Sales Margin (Today vs Yesterday)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF ( [Sales Margin (Today vs Yesterday)] = 0, UNICHAR ( 45 ), UNICHAR ( 8595 ) )",
              ")"
            ],
            "lineageTag": "c197c97f-0428-42a7-ba0f-8d929a81fd50"
          },
          {
            "name": "Sales Margin (MTD vs PMTD)",
            "displayFolder": "Sales Margin",
            "expression": [
              "IF (",
              "    ISBLANK ( [Sales Margin (PMTD)] ),",
              "    BLANK (),",
              "    DIVIDE (",
              "        [Sales Margin (MTD)] - [Sales Margin (PMTD)],",
              "        [Sales Margin (PMTD)],",
              "        0",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "defb6585-5513-401e-b6fe-a22dbdd30312"
          },
          {
            "name": "Sales Margin (MTD vs PMTD) ARROW",
            "description": "This measure is a derivative of Sales Margin.",
            "displayFolder": "Sales Margin",
            "expression": [
              "IF (",
              "    [Sales Margin (MTD vs PMTD)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF ( [Sales Margin (MTD vs PMTD)] = 0, UNICHAR ( 45 ), UNICHAR ( 8595 ) )",
              ")"
            ],
            "lineageTag": "32f5d263-c727-4835-889d-ca2c8b6f7287"
          },
          {
            "name": "Sales Margin (YTD vs PYTD)",
            "displayFolder": "Sales Margin",
            "expression": [
              "IF (",
              "    ISBLANK ( [Sales Margin (PYTD)] ),",
              "    BLANK (),",
              "    DIVIDE (",
              "        [Sales Margin (YTD)] - [Sales Margin (PYTD)],",
              "        [Sales Margin (PYTD)],",
              "        0",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "f7d246ed-60c8-4ced-9664-945904d8b592"
          },
          {
            "name": "Sales Margin (YTD vs PYTD) ARROW",
            "description": "This measure is a derivative of Sales Margin.",
            "displayFolder": "Sales Margin",
            "expression": [
              "IF (",
              "    [Sales Margin (YTD vs PYTD)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF ( [Sales Margin (YTD vs PYTD)] = 0, UNICHAR ( 45 ), UNICHAR ( 8595 ) )",
              ")"
            ],
            "lineageTag": "adc57365-0a2e-46b5-a5f0-58df91af137b"
          },
          {
            "name": "Sales Invoiced (MTD vs Budget) ARROW",
            "description": "This measure shows the arrow indicator for the Sales Invoiced vs Sales Budget comparison for MTD.",
            "displayFolder": "Sales Invoiced",
            "expression": [
              "IF (",
              "    f_salesinvoices[Sales Invoiced (MTD)] > f_budgets[Sales Budget (MTD)],",
              "    UNICHAR ( 8593 ),",
              "    IF (",
              "        f_salesinvoices[Sales Invoiced (MTD)] < f_budgets[Sales Budget (MTD)],",
              "        UNICHAR ( 8595 ),",
              "        UNICHAR ( 45 )",
              "    )",
              ")"
            ],
            "lineageTag": "8926401c-719f-44d7-8510-dbf9af9ca815"
          },
          {
            "name": "Sales Invoiced (MTD vs Budget) TEXT",
            "description": "This measure shows the text comparison (Positive, Negative, No Change) for the Sales Invoiced vs Sales Budget for MTD.",
            "displayFolder": "Sales Invoiced",
            "expression": [
              "IF (",
              "    f_salesinvoices[Sales Invoiced (MTD)] > f_budgets[Sales Budget (MTD)],",
              "    \"Positive\",",
              "    IF (",
              "        f_salesinvoices[Sales Invoiced (MTD)] < f_budgets[Sales Budget (MTD)],",
              "        \"Negative\",",
              "        \"No Change\"",
              "    )",
              ")"
            ],
            "lineageTag": "ce3b7a56-cd4e-4e76-85eb-b8ed836c96c5"
          },
          {
            "name": "Sales Invoiced (YTD vs Budget) ARROW",
            "description": "This measure shows the arrow indicator for the Sales Invoiced vs Sales Budget comparison for YTD.",
            "displayFolder": "Sales Invoiced",
            "expression": [
              "IF (",
              "    f_salesinvoices[Sales Invoiced (YTD)] > f_budgets[Sales Budget (YTD)],",
              "    UNICHAR ( 8593 ),",
              "    IF (",
              "        f_salesinvoices[Sales Invoiced (YTD)] < f_budgets[Sales Budget (YTD)],",
              "        UNICHAR ( 8595 ),",
              "        UNICHAR ( 45 )",
              "    )",
              ")"
            ],
            "lineageTag": "5912dd0e-0de7-4b4f-bfd8-cd7ad993314d"
          },
          {
            "name": "Sales Invoiced (YTD vs Budget) TEXT",
            "description": "This measure shows the text comparison (Positive, Negative, No Change) for the Sales Invoiced vs Sales Budget for YTD.",
            "displayFolder": "Sales Invoiced",
            "expression": [
              "IF (",
              "    f_salesinvoices[Sales Invoiced (YTD)] > f_budgets[Sales Budget (YTD)],",
              "    \"Positive\",",
              "    IF (",
              "        f_salesinvoices[Sales Invoiced (YTD)] < f_budgets[Sales Budget (YTD)],",
              "        \"Negative\",",
              "        \"No Change\"",
              "    )",
              ")"
            ],
            "lineageTag": "b2be7d2a-ecf8-4c29-9def-3334fe364f4e"
          },
          {
            "name": "Sales Margin (MTD vs Budget) ARROW",
            "description": "This measure shows the arrow indicator for the Sales Margin vs Budget Margin comparison for MTD.",
            "displayFolder": "Sales Margin",
            "expression": [
              "IF (",
              "    f_salesinvoices[Sales Margin (MTD)] > f_budgets[Budget Margin (MTD)],",
              "    UNICHAR ( 8593 ),",
              "    IF (",
              "        f_salesinvoices[Sales Margin (MTD)] < f_budgets[Budget Margin (MTD)],",
              "        UNICHAR ( 8595 ),",
              "        UNICHAR ( 45 )",
              "    )",
              ")"
            ],
            "lineageTag": "123665cd-079c-4f04-a642-85a1063d3573"
          },
          {
            "name": "Sales Margin (MTD vs Budget) TEXT",
            "description": "This measure shows the text comparison (Positive, Negative, No Change) for the Sales Margin vs Budget Margin for MTD.",
            "displayFolder": "Sales Margin",
            "expression": [
              "IF (",
              "    f_salesinvoices[Sales Margin (MTD)] > f_budgets[Budget Margin (MTD)],",
              "    \"Positive\",",
              "    IF (",
              "        f_salesinvoices[Sales Margin (MTD)] < f_budgets[Budget Margin (MTD)],",
              "        \"Negative\",",
              "        \"No Change\"",
              "    )",
              ")"
            ],
            "lineageTag": "c2a2219c-401a-4f42-82ac-6006132827a2"
          },
          {
            "name": "Sales Margin (YTD vs Budget) ARROW",
            "description": "This measure shows the arrow indicator for the Sales Margin vs Budget Margin comparison for YTD.",
            "displayFolder": "Sales Margin",
            "expression": [
              "IF (",
              "    f_salesinvoices[Sales Margin (YTD)] > f_budgets[Budget Margin (YTD)],",
              "    UNICHAR ( 8593 ),",
              "    IF (",
              "        f_salesinvoices[Sales Margin (YTD)] < f_budgets[Budget Margin (YTD)],",
              "        UNICHAR ( 8595 ),",
              "        UNICHAR ( 45 )",
              "    )",
              ")"
            ],
            "lineageTag": "750bf0ce-98e4-4615-852d-adea931d13cc"
          },
          {
            "name": "Sales Margin (YTD vs Budget) TEXT",
            "description": "This measure shows the text comparison (Positive, Negative, No Change) for the Sales Margin vs Budget Margin for YTD.",
            "displayFolder": "Sales Margin",
            "expression": [
              "IF (",
              "    f_salesinvoices[Sales Margin (YTD)] > f_budgets[Budget Margin (YTD)],",
              "    \"Positive\",",
              "    IF (",
              "        f_salesinvoices[Sales Margin (YTD)] < f_budgets[Budget Margin (YTD)],",
              "        \"Negative\",",
              "        \"No Change\"",
              "    )",
              ")"
            ],
            "lineageTag": "a40c56b6-98a9-43af-8373-814972dda77f"
          },
          {
            "name": "Sales Volume (MTD vs Budget) ARROW",
            "description": "This measure shows the arrow indicator for the Sales Volume vs Budget Volume comparison for MTD.",
            "displayFolder": "Sales Volume",
            "expression": [
              "IF (",
              "    f_salesinvoices[Sales Volume (MTD)] > f_budgets[Budget Volume (MTD)],",
              "    UNICHAR ( 8593 ),",
              "    IF (",
              "        f_salesinvoices[Sales Volume (MTD)] < f_budgets[Budget Volume (MTD)],",
              "        UNICHAR ( 8595 ),",
              "        UNICHAR ( 45 )",
              "    )",
              ")"
            ],
            "lineageTag": "24d6703e-35c1-4f6a-829e-c95d3a3b9af1"
          },
          {
            "name": "Sales Volume (MTD vs Budget) TEXT",
            "description": "This measure shows the text comparison (Positive, Negative, No Change) for the Sales Volume vs Budget Volume for MTD.",
            "displayFolder": "Sales Volume",
            "expression": [
              "IF (",
              "    f_salesinvoices[Sales Volume (MTD)] > f_budgets[Budget Volume (MTD)],",
              "    \"Positive\",",
              "    IF (",
              "        f_salesinvoices[Sales Volume (MTD)] < f_budgets[Budget Volume (MTD)],",
              "        \"Negative\",",
              "        \"No Change\"",
              "    )",
              ")"
            ],
            "lineageTag": "30a47bab-3935-476d-8e56-94f3246d5aa4"
          },
          {
            "name": "Sales Volume (YTD vs Budget) ARROW",
            "description": "This measure shows the arrow indicator for the Sales Volume vs Budget Volume comparison for YTD.",
            "displayFolder": "Sales Volume",
            "expression": [
              "IF (",
              "    f_salesinvoices[Sales Volume (YTD)] > f_budgets[Budget Volume (YTD)],",
              "    UNICHAR ( 8593 ),",
              "    IF (",
              "        f_salesinvoices[Sales Volume (YTD)] < f_budgets[Budget Volume (YTD)],",
              "        UNICHAR ( 8595 ),",
              "        UNICHAR ( 45 )",
              "    )",
              ")"
            ],
            "lineageTag": "ce6d2ce5-2c66-4caa-9951-36910fd7407e"
          },
          {
            "name": "Sales Volume (YTD vs Budget) TEXT",
            "description": "This measure shows the text comparison (Positive, Negative, No Change) for the Sales Volume vs Budget Volume for YTD.",
            "displayFolder": "Sales Volume",
            "expression": [
              "IF (",
              "    f_salesinvoices[Sales Volume (YTD)] > f_budgets[Budget Volume (YTD)],",
              "    \"Positive\",",
              "    IF (",
              "        f_salesinvoices[Sales Volume (YTD)] < f_budgets[Budget Volume (YTD)],",
              "        \"Negative\",",
              "        \"No Change\"",
              "    )",
              ")"
            ],
            "lineageTag": "78ea83dc-a91b-40b2-8b85-d55c3b96f7a8"
          }
        ],
        "partitions": [
          {
            "name": "curated_f_salesinvoices",
            "mode": "directLake",
            "source": {
              "entityName": "curated_f_salesinvoices",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_f_salesinvoices]"
      },
      {
        "name": "d_date",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f50a4c0e-51d4-47dd-a7f3-33161e433ab9",
            "sourceColumn": "DateID",
            "sourceLineageTag": "DateID",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "1c7e0e0a-4846-4de7-aebe-526bcf96ce79",
            "sourceColumn": "Date",
            "sourceLineageTag": "Date",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc980a17-60e3-481d-b66e-d9bfc1eabf57",
            "sourceColumn": "Day",
            "sourceLineageTag": "Day",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Day Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "634dc409-70fc-4bc7-b570-95b98388815e",
            "sourceColumn": "DayShort",
            "sourceLineageTag": "DayShort",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Day Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "054d3865-67dd-42d2-82fc-04dd122df0cd",
            "sourceColumn": "DayNumber",
            "sourceLineageTag": "DayNumber",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "Weekday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1a3660e8-8548-4248-be44-041f068b2586",
            "sourceColumn": "Weekday",
            "sourceLineageTag": "Weekday",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b1c1205-3dbf-488c-9b0e-509a59232653",
            "sourceColumn": "Week",
            "sourceLineageTag": "Week",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Week Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "41ab677d-3c66-4c7b-aedb-7e301eb1df33",
            "sourceColumn": "WeekNumber",
            "sourceLineageTag": "WeekNumber",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61265f15-5675-4c43-a327-bc21ed1512a7",
            "sortByColumn": "Month Number",
            "sourceColumn": "Month",
            "sourceLineageTag": "Month",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Month Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ada6fcf-c104-4f7a-b7f6-1203feed1cc6",
            "sourceColumn": "MonthShort",
            "sourceLineageTag": "MonthShort",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "94e3ceeb-1edb-4f82-a61d-619a7b54b2ec",
            "sourceColumn": "MonthNumber",
            "sourceLineageTag": "MonthNumber",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aedeaee8-7164-4e67-87ea-6d97747779ac",
            "sourceColumn": "MonthDay",
            "sourceLineageTag": "MonthDay",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce84be60-1efa-4cb8-8220-3e9d5955289a",
            "sourceColumn": "Quarter",
            "sourceLineageTag": "Quarter",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "84ebdf2b-c55e-44b2-8eab-55603e76c826",
            "sourceColumn": "QuarterNumber",
            "sourceLineageTag": "QuarterNumber",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7c5290a4-3f8d-4ae5-b341-11f79f3e76f0",
            "sourceColumn": "Year",
            "sourceLineageTag": "Year",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "Year Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0cc80c2a-930e-4962-8901-9111b5a2a7e6",
            "sourceColumn": "YearQuarter",
            "sourceLineageTag": "YearQuarter",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Year Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c9c450b-aa9d-4ce3-8608-b70f5f76e6dd",
            "sourceColumn": "YearMonthName",
            "sourceLineageTag": "YearMonthName",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Year Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c33582e1-7f84-4474-b370-26377cf3f875",
            "sourceColumn": "YearMonth",
            "sourceLineageTag": "YearMonth",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "First Of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "3ed81e2f-00c0-48e0-a817-565a4fac3c7e",
            "sourceColumn": "FirstOfMonth",
            "sourceLineageTag": "FirstOfMonth",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "First Of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "5aa350ba-8b55-425c-88c5-29614e3e050e",
            "sourceColumn": "FirstOfWeek",
            "sourceLineageTag": "FirstOfWeek",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "808c28d2-67b0-445b-b68d-3b508f3f5dd0",
            "sourceColumn": "Period",
            "sourceLineageTag": "Period",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "Financial Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0df324db-fa9c-43d7-b635-7d820bf2d638",
            "sourceColumn": "FinancialYear",
            "sourceLineageTag": "FinancialYear",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "Financial Year Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a8a688f0-c6ff-4569-9386-7f541dfa1ac0",
            "sourceColumn": "FinancialYearPeriod",
            "sourceLineageTag": "FinancialYearPeriod",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "Financial Year Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a624ddc-bf73-4b46-8b00-700860ded013",
            "sourceColumn": "FinancialYearMonthName",
            "sourceLineageTag": "FinancialYearMonthName",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Financial Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "769370b4-bd93-4294-8d05-d04eab3f14fa",
            "sourceColumn": "FinancialQuarter",
            "sourceLineageTag": "FinancialQuarter",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Financial Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9ea01f70-2395-41b8-8b07-2fda19ae878d",
            "sourceColumn": "FinancialQuarterNumber",
            "sourceLineageTag": "FinancialQuarterNumber",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "Financial Year Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a59d4120-9639-42c6-be73-2e3cd0a16350",
            "sourceColumn": "FinancialYearQuarter",
            "sourceLineageTag": "FinancialYearQuarter",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "DateNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "lineageTag": "4fb1bfed-148f-4859-ada9-99155d467837",
            "sourceColumn": "DateNaturalID",
            "sourceLineageTag": "DateNaturalID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5df49cd4-cfcc-4423-ad70-3830cd0dba60",
        "partitions": [
          {
            "name": "curated_d_date",
            "mode": "directLake",
            "source": {
              "entityName": "curated_d_date",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_date]"
      },
      {
        "name": "d_legalentity",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "LegalEntityID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "66d1cd25-08df-44a9-bf61-1b1bc2806dca",
            "sourceColumn": "LegalEntityID",
            "sourceLineageTag": "LegalEntityID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Legal Entity Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "181fbf87-4b09-44ec-a162-607369dfc27a",
            "sourceColumn": "LegalEntityCode",
            "sourceLineageTag": "LegalEntityCode",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Legal Entity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "639214eb-5dd7-40e8-bfa1-d9b145b5d735",
            "sourceColumn": "LegalEntity",
            "sourceLineageTag": "LegalEntity",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Accounting Currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d74449d-39b0-4f6e-9a48-0a9daf0c6834",
            "sourceColumn": "AccountingCurrency",
            "sourceLineageTag": "AccountingCurrency",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "f7ba8e8f-bb90-4958-a696-2a36635709bb",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          },
          {
            "name": "LegalEntityNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8350c244-eb1f-4bca-b851-2f4556edbfd0",
            "sourceColumn": "LegalEntityNaturalID",
            "sourceLineageTag": "LegalEntityNaturalID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f08acf98-3f70-46ba-9616-a05d73ec111e",
        "partitions": [
          {
            "name": "curated_d_legalentity",
            "mode": "directLake",
            "source": {
              "entityName": "curated_d_legalentity",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_legalentity]"
      },
      {
        "name": "f_purchaseorders",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "FK_DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9e8b05fb-64b4-411e-a900-9116f522808b",
            "sourceColumn": "FK_DateID",
            "sourceLineageTag": "FK_DateID",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "FK_WarehouseID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9113b30a-eb98-480c-b493-484be1f238da",
            "sourceColumn": "FK_WarehouseID",
            "sourceLineageTag": "FK_WarehouseID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_PurchaseOrderStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9a399cdc-9982-43c8-8dd9-225f14240a11",
            "sourceColumn": "FK_PurchaseOrderStatusID",
            "sourceLineageTag": "FK_PurchaseOrderStatusID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_LegalEntityID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d807dc62-1dc3-4a3b-85c0-781e13786ef8",
            "sourceColumn": "FK_LegalEntityID",
            "sourceLineageTag": "FK_LegalEntityID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_SupplierID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e8db18e2-022b-4543-97f6-5ab21a33f07e",
            "sourceColumn": "FK_SupplierID",
            "sourceLineageTag": "FK_SupplierID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_PostalAddressID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "863c6a6f-e02b-4550-adcb-20183a25f31b",
            "sourceColumn": "FK_PostalAddressID",
            "sourceLineageTag": "FK_PostalAddressID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e6adb055-4ed6-4993-9e13-3077ea4fca30",
            "sourceColumn": "FK_ProductID",
            "sourceLineageTag": "FK_ProductID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "d2e67f13-4e97-4462-9917-e7152e010ed4",
            "sourceColumn": "Volume",
            "sourceLineageTag": "Volume",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Amount_ G B P",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "5258be0d-d9c9-4f5d-a4db-e8fa2cd8d890",
            "sourceColumn": "TotalAmount_GBP",
            "sourceLineageTag": "TotalAmount_GBP",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Amount_ E U R",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "63635350-dcfd-4f43-9d85-39dd194756ad",
            "sourceColumn": "TotalAmount_EUR",
            "sourceLineageTag": "TotalAmount_EUR",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Amount_ U S D",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "70cca2ec-7608-4036-9fd7-4da8c97c9b6d",
            "sourceColumn": "TotalAmount_USD",
            "sourceLineageTag": "TotalAmount_USD",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Price Per Unit_ G B P",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0cdc17c8-ad8f-438e-b06b-19008e0717a9",
            "sourceColumn": "PricePerUnit_GBP",
            "sourceLineageTag": "PricePerUnit_GBP",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Price Per Unit_ E U R",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cf12f2d3-cafc-4299-92d2-a7562827f4f8",
            "sourceColumn": "PricePerUnit_EUR",
            "sourceLineageTag": "PricePerUnit_EUR",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Price Per Unit_ U S D",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "019ddb58-332b-42ca-bd34-7b9397e0222e",
            "sourceColumn": "PricePerUnit_USD",
            "sourceLineageTag": "PricePerUnit_USD",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0",
            "lineageTag": "1321be6a-1fb7-4af8-b06d-5b10f0f99620",
            "sourceColumn": "Quantity",
            "sourceLineageTag": "Quantity",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "FK_BusinessUnitID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "fb30f308-b88a-4073-9720-3eb6f7bac959",
            "sourceColumn": "FK_BusinessUnitID",
            "sourceLineageTag": "FK_BusinessUnitID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "PurchaseOrderID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "string",
            "lineageTag": "716d45d0-7283-4bad-9401-c928bab2ecc1",
            "sourceColumn": "PurchaseOrderID",
            "sourceLineageTag": "PurchaseOrderID",
            "sourceProviderType": "real",
            "summarizeBy": "none"
          },
          {
            "name": "VolumeKG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "e920a9a5-f285-46d8-ae2c-7e9869a6ac0a",
            "sourceColumn": "VolumeKG",
            "sourceLineageTag": "VolumeKG",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "45b34233-a7ea-4787-b741-24e8939368f9",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "sourceProviderType": "real",
            "summarizeBy": "none"
          },
          {
            "name": "Line Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "lineageTag": "6f5249fe-25c6-4e67-845d-8dcaf5bc79f8",
            "sourceColumn": "LineNumber",
            "sourceLineageTag": "LineNumber",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "ModifiedOn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "lineageTag": "06a79885-37c6-4411-afcc-53d80e424175",
            "sourceColumn": "ModifiedOn",
            "sourceLineageTag": "ModifiedOn",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b6a045f3-a9ba-4336-8895-188fc202c310",
        "measures": [
          {
            "name": "Average Price Per Unit",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'S_Currency'[Currency] ),",
              "    \"GBP\", AVERAGE ( f_purchaseorders[Price Per Unit_ G B P] ),",
              "    \"EUR\", AVERAGE ( f_purchaseorders[Price Per Unit_ E U R] ),",
              "    \"USD\", AVERAGE ( f_purchaseorders[Price Per Unit_ U S D] )",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "c6ada620-c0cd-40f6-a5ac-77e44d15a91e"
          },
          {
            "name": "Average Purchase Order Value",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'S_Currency'[Currency] ),",
              "    \"GBP\", AVERAGE ( f_purchaseorders[Total Amount_ G B P] ),",
              "    \"EUR\", AVERAGE ( f_purchaseorders[Total Amount_ E U R] ),",
              "    \"USD\", AVERAGE ( f_purchaseorders[Total Amount_ U S D] )",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "48dd00d6-acdf-4500-996a-c8e0b2665395"
          },
          {
            "name": "Spend Volume",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(SUM( f_purchaseorders[Volume] ), FILTER(d_unit, d_unit[Unit] <> \"EACH\"))",
            "formatString": "#,0.00",
            "lineageTag": "c50c285b-427c-4df5-9ee1-f0f4a2dadf2b"
          },
          {
            "name": "No. Purchase Orders",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "COUNTROWS ( f_purchaseorders )",
            "formatString": "#,0",
            "lineageTag": "3667cb23-b296-44d6-9631-e548fbf2405a"
          },
          {
            "name": "Total Spend",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'S_Currency'[Currency], \"None\" ),",
              "    \"GBP\", SUM ( f_purchaseorders[Total Amount_ G B P] ),",
              "    \"EUR\", SUM ( f_purchaseorders[Total Amount_ E U R] ),",
              "    \"USD\", SUM ( f_purchaseorders[Total Amount_ U S D] )",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "f18dcecf-faa1-4e88-933b-eff89f8193f6"
          },
          {
            "name": "Purchase Order Volume",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(SUM ( f_purchaseorders[Volume] ), FILTER(d_unit, d_unit[Unit] <> \"EACH\"))",
            "formatString": "#,0.00",
            "lineageTag": "1f159211-45dd-42ce-967c-6e33426f1312"
          },
          {
            "name": "Cost Per Unit",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( S_Currency[Currency] ),",
              "    \"GBP\", SUM ( f_purchaseorders[Price Per Unit_ G B P] ),",
              "    \"EUR\", SUM ( f_purchaseorders[Price Per Unit_ E U R] ),",
              "    \"USD\", SUM ( f_purchaseorders[Price Per Unit_ U S D] ),",
              "    BLANK ()",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "24b4f2fb-6cea-447f-b3fe-e651b1527e92"
          },
          {
            "name": "No. Products Per Supplier",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE (",
              "    DISTINCTCOUNT ( f_purchaseorders[FK_ProductID] ),",
              "    ALLEXCEPT ( D_Supplier, d_supplier[Supplier] )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "92dc5153-9d31-44f6-9570-91b963c1ab82"
          },
          {
            "name": "Total Spend (Today)",
            "description": "This measure is a derivative of Total Spend.",
            "displayFolder": "Total Spend",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "RETURN",
              "    CALCULATE (",
              "        [Total Spend],",
              "        'd_date'[Date] = CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "c9c4a140-8536-4c64-9be0-729003ccad37"
          },
          {
            "name": "Total Spend (Yesterday)",
            "description": "This measure is a derivative of Total Spend.",
            "displayFolder": "Total Spend",
            "expression": [
              "VAR YesterdayDate =",
              "    TODAY () - 1",
              "RETURN",
              "    CALCULATE (",
              "        [Total Spend],",
              "        'd_date'[Date] = YesterdayDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "82ad8d0d-351d-49c8-9cc0-2090f35af337"
          },
          {
            "name": "Total Spend (MTD)",
            "description": "This measure is a derivative of Total Spend.",
            "displayFolder": "Total Spend",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR StartdateMonth =",
              "    DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 )",
              "RETURN",
              "    CALCULATE (",
              "        [Total Spend],",
              "        'd_date'[Date] >= StartdateMonth",
              "            && 'd_date'[Date] <= CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "c22dfc2f-0d5f-4269-96b2-8c8276280967"
          },
          {
            "name": "Total Spend (PMTD)",
            "description": "This measure is a derivative of Total Spend.",
            "displayFolder": "Total Spend",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR DaysInMonthSoFar =",
              "    DAY ( CurrentDate )",
              "VAR StartOfPriorMonth =",
              "    EDATE ( DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 ), -1 )",
              "VAR EndOfPriorMonth = StartOfPriorMonth + DaysInMonthSoFar - 1",
              "RETURN",
              "    CALCULATE (",
              "        [Total Spend],",
              "        'd_date'[Date] >= StartOfPriorMonth",
              "            && 'd_date'[Date] <= EndOfPriorMonth,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "a2bcaafa-639c-4de9-ba3e-5954acacbb55"
          },
          {
            "name": "Total Spend (YTD)",
            "description": "This measure is a derivative of Total Spend.",
            "displayFolder": "Total Spend",
            "expression": "[Total Spend]",
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "fbbf4f1f-dc22-48fe-94f6-afed9449ead6"
          },
          {
            "name": "Total Spend (PYTD)",
            "description": "This measure is a derivative of Total Spend.",
            "displayFolder": "Total Spend",
            "expression": [
              "CALCULATE (",
              "    [Total Spend],",
              "    REMOVEFILTERS ( d_date ),",
              "    FILTER (",
              "        DATEADD ( d_date[Date], -1, YEAR ),",
              "        d_date[Date]",
              "            <= DATE ( YEAR ( TODAY () - 1 ), MONTH ( TODAY () ), DAY ( TODAY () ) )",
              "    )",
              ")"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "b8546498-ca12-45f7-bc4d-39d3c0839ca1"
          },
          {
            "name": "No. Purchase Orders (Today)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "This measure is a derivative of No. Purchase Orders.",
            "displayFolder": "No. Purchase Orders",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "RETURN",
              "    CALCULATE (",
              "        [No. Purchase Orders],",
              "        'd_date'[Date] = CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "5523d717-c42f-49b4-aecb-fa96c0f17e84"
          },
          {
            "name": "No. Purchase Orders (Yesterday)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "This measure is a derivative of No. Purchase Orders.",
            "displayFolder": "No. Purchase Orders",
            "expression": [
              "VAR YesterdayDate =",
              "    TODAY () - 1",
              "RETURN",
              "    CALCULATE (",
              "        [No. Purchase Orders],",
              "        'd_date'[Date] = YesterdayDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "5f39759f-f49e-4ff0-8a7a-5f69727dabb5"
          },
          {
            "name": "No. Purchase Orders (MTD)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "This measure is a derivative of No. Purchase Orders.",
            "displayFolder": "No. Purchase Orders",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR StartdateMonth =",
              "    DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 )",
              "RETURN",
              "    CALCULATE (",
              "        [No. Purchase Orders],",
              "        'd_date'[Date] >= StartdateMonth",
              "            && 'd_date'[Date] <= CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "d53b6dd8-a8fc-45db-af65-dd7b22bd9497"
          },
          {
            "name": "No. Purchase Orders (PMTD)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "This measure is a derivative of No. Purchase Orders.",
            "displayFolder": "No. Purchase Orders",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR DaysInMonthSoFar =",
              "    DAY ( CurrentDate )",
              "VAR StartOfPriorMonth =",
              "    EDATE ( DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 ), -1 )",
              "VAR EndOfPriorMonth = StartOfPriorMonth + DaysInMonthSoFar - 1",
              "RETURN",
              "    CALCULATE (",
              "        [No. Purchase Orders],",
              "        'd_date'[Date] >= StartOfPriorMonth",
              "            && 'd_date'[Date] <= EndOfPriorMonth,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "933bdbc6-fbf7-4ccb-8f6f-cb0447003425"
          },
          {
            "name": "No. Purchase Orders (YTD)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "This measure is a derivative of No. Purchase Orders.",
            "displayFolder": "No. Purchase Orders",
            "expression": "[No. Purchase Orders]",
            "formatString": "#,0",
            "lineageTag": "33d57377-f659-4201-9365-81052b82306c"
          },
          {
            "name": "No. Purchase Orders (PYTD)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "This measure is a derivative of No. Purchase Orders.",
            "displayFolder": "No. Purchase Orders",
            "expression": [
              "CALCULATE (",
              "    [No. Purchase Orders],",
              "    REMOVEFILTERS ( d_date ),",
              "    FILTER (",
              "        DATEADD ( d_date[Date], -1, YEAR ),",
              "        d_date[Date]",
              "            <= DATE ( YEAR ( TODAY () - 1 ), MONTH ( TODAY () ), DAY ( TODAY () ) )",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "e8851989-d6a8-43e3-8e22-ba54fd2664b9"
          },
          {
            "name": "Spend Volume (YTD)",
            "description": "This measure is a derivative of Spend Volume.",
            "displayFolder": "Spend Volume",
            "expression": "[Spend Volume]",
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "ef43f896-6a02-49f4-acdd-c02d0fb2b216"
          },
          {
            "name": "Spend Volume (PYTD)",
            "description": "This measure is a derivative of Spend Volume.",
            "displayFolder": "Spend Volume",
            "expression": [
              "CALCULATE (",
              "    [Spend Volume],",
              "    REMOVEFILTERS ( d_date ),",
              "    FILTER (",
              "        DATEADD ( d_date[Date], -1, YEAR ),",
              "        d_date[Date]",
              "            <= DATE ( YEAR ( TODAY () - 1 ), MONTH ( TODAY () ), DAY ( TODAY () ) )",
              "    )",
              ")"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "a007ddac-c32c-4479-88ca-149349f37f10"
          },
          {
            "name": "Total Spend (Today vs Yesterday)",
            "displayFolder": "Total Spend",
            "expression": [
              "IF (",
              "    ISBLANK ( [Total Spend (Yesterday)] ),",
              "    BLANK (),",
              "    IF (",
              "        ISBLANK ( [Total Spend (Today)] ),",
              "        BLANK (),",
              "        DIVIDE (",
              "            [Total Spend (Today)] - [Total Spend (Yesterday)],",
              "            [Total Spend (Yesterday)],",
              "            0",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "62054220-d7f6-4134-8fed-c28b3210d72a"
          },
          {
            "name": "Total Spend (Today vs Yesterday) ARROW",
            "description": "This measure is a derivative of Total Spend.",
            "displayFolder": "Total Spend",
            "expression": [
              "IF (",
              "    [Total Spend (Today vs Yesterday)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF (",
              "        [Total Spend (Today vs Yesterday)] = 0,",
              "        UNICHAR ( 45 ),",
              "        IF (",
              "            [Total Spend (Today vs Yesterday)] = BLANK (),",
              "            UNICHAR ( 45 ),",
              "            UNICHAR ( 8595 )",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "d8ede7dd-7050-4950-a68b-8d00f2e77314"
          },
          {
            "name": "Total Spend (MTD vs PMTD)",
            "displayFolder": "Total Spend",
            "expression": [
              "IF (",
              "    ISBLANK ( [Total Spend (PMTD)] ),",
              "    BLANK (),",
              "    IF (",
              "        ISBLANK ( [Total Spend (MTD)] ),",
              "        BLANK (),",
              "        DIVIDE ( [Total Spend (MTD)] - [Total Spend (PMTD)], [Total Spend (PMTD)], 0 )",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "b330cc2f-942e-4b85-9f81-e3e57be3ba76"
          },
          {
            "name": "Total Spend (MTD vs PMTD) ARROW",
            "description": "This measure is a derivative of Total Spend.",
            "displayFolder": "Total Spend",
            "expression": [
              "IF (",
              "    [Total Spend (MTD vs PMTD)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF (",
              "        [Total Spend (MTD vs PMTD)] = 0,",
              "        UNICHAR ( 45 ),",
              "        IF ( [Total Spend (MTD vs PMTD)] = BLANK (), UNICHAR ( 45 ), UNICHAR ( 8595 ) )",
              "    )",
              ")"
            ],
            "lineageTag": "0533a098-6406-4210-999b-d2e3ed83de79"
          },
          {
            "name": "Total Spend (YTD vs PYTD)",
            "displayFolder": "Total Spend",
            "expression": [
              "IF (",
              "    ISBLANK ( [Total Spend (PYTD)] ),",
              "    BLANK (),",
              "    IF (",
              "        ISBLANK ( [Total Spend (MTD)] ),",
              "        BLANK (),",
              "        DIVIDE ( [Total Spend (YTD)] - [Total Spend (PYTD)], [Total Spend (PYTD)], 0 )",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "ac8503ab-631b-45a7-bbf9-983069ec975c"
          },
          {
            "name": "Total Spend (YTD vs PYTD) ARROW",
            "description": "This measure is a derivative of Total Spend.",
            "displayFolder": "Total Spend",
            "expression": [
              "IF (",
              "    [Total Spend (YTD vs PYTD)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF (",
              "        [Total Spend (YTD vs PYTD)] = 0,",
              "        UNICHAR ( 45 ),",
              "        IF ( [Total Spend (YTD vs PYTD)] = BLANK (), UNICHAR ( 45 ), UNICHAR ( 8595 ) )",
              "    )",
              ")"
            ],
            "lineageTag": "d32323c3-2b01-4df2-a34e-288ddc7ecc58"
          },
          {
            "name": "No. Purchase Orders (Today vs Yesterday)",
            "displayFolder": "No. Purchase Orders",
            "expression": [
              "IF (",
              "    ISBLANK ( [No. Purchase Orders (Yesterday)] ),",
              "    BLANK (),",
              "    IF (",
              "        ISBLANK ( [No. Purchase Orders (Today)] ),",
              "        BLANK (),",
              "        DIVIDE (",
              "            [No. Purchase Orders (Today)] - [No. Purchase Orders (Yesterday)],",
              "            [No. Purchase Orders (Yesterday)],",
              "            0",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "1d0544a7-d95e-465a-b609-f8103df6bac3"
          },
          {
            "name": "No. Purchase Orders (Today vs Yesterday) ARROW",
            "description": "This measure is a derivative of No. Purchase Orders.",
            "displayFolder": "No. Purchase Orders",
            "expression": [
              "IF (",
              "    [No. Purchase Orders (Today vs Yesterday)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF (",
              "        [No. Purchase Orders (Today vs Yesterday)] = 0,",
              "        UNICHAR ( 45 ),",
              "        IF (",
              "            [No. Purchase Orders (Today vs Yesterday)] = BLANK (),",
              "            UNICHAR ( 45 ),",
              "            UNICHAR ( 8595 )",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "50ba10d6-170d-4945-a5ac-dcd8be599019"
          },
          {
            "name": "No. Purchase Orders (MTD vs PMTD)",
            "displayFolder": "No. Purchase Orders",
            "expression": [
              "IF (",
              "    ISBLANK ( [No. Purchase Orders (PMTD)] ),",
              "    BLANK (),",
              "    IF (",
              "        ISBLANK ( [No. Purchase Orders (MTD)] ),",
              "        BLANK (),",
              "        DIVIDE (",
              "            [No. Purchase Orders (MTD)] - [No. Purchase Orders (PMTD)],",
              "            [No. Purchase Orders (PMTD)],",
              "            0",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "55f96ab2-9408-4abd-9131-b61f99aa78b1"
          },
          {
            "name": "No. Purchase Orders (MTD vs PMTD) ARROW",
            "description": "This measure is a derivative of No. Purchase Orders.",
            "displayFolder": "No. Purchase Orders",
            "expression": [
              "IF (",
              "    [No. Purchase Orders (MTD vs PMTD)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF (",
              "        [No. Purchase Orders (MTD vs PMTD)] = 0,",
              "        UNICHAR ( 45 ),",
              "        IF (",
              "            [No. Purchase Orders (MTD vs PMTD)] = BLANK (),",
              "            UNICHAR ( 45 ),",
              "            UNICHAR ( 8595 )",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "e25369f3-c32a-403a-87c3-138ec673370c"
          },
          {
            "name": "No. Purchase Orders (YTD vs PYTD)",
            "displayFolder": "No. Purchase Orders",
            "expression": [
              "IF (",
              "    ISBLANK ( [No. Purchase Orders (PYTD)] ),",
              "    BLANK (),",
              "    IF (",
              "        ISBLANK ( [No. Purchase Orders (MTD)] ),",
              "        BLANK (),",
              "        DIVIDE (",
              "            [No. Purchase Orders (YTD)] - [No. Purchase Orders (PYTD)],",
              "            [No. Purchase Orders (PYTD)],",
              "            0",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "12814f0a-81b8-4e28-95f4-9a5b5df459b3"
          },
          {
            "name": "No. Purchase Orders (YTD vs PYTD) ARROW",
            "description": "This measure is a derivative of No. Purchase Orders.",
            "displayFolder": "No. Purchase Orders",
            "expression": [
              "IF (",
              "    [No. Purchase Orders (YTD vs PYTD)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF (",
              "        [No. Purchase Orders (YTD vs PYTD)] = 0,",
              "        UNICHAR ( 45 ),",
              "        IF (",
              "            [No. Purchase Orders (YTD vs PYTD)] = BLANK (),",
              "            UNICHAR ( 45 ),",
              "            UNICHAR ( 8595 )",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "2afc5032-7490-44f2-a72a-1b7dbb8cf412"
          },
          {
            "name": "Purchase Quantity",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM ( f_purchaseorders[Quantity] )",
            "formatString": "#,0",
            "lineageTag": "9de7cef4-8faf-4b0d-a55e-26633e21d688"
          },
          {
            "name": "Volume T (PO)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": "CALCULATE(DIVIDE(SUM(f_purchaseorders[Volume]), 1000), FILTER(d_unit, d_unit[Unit] <> \"EACH\"))",
            "lineageTag": "59a17fad-b04d-46d1-b2fe-640097cf4727"
          },
          {
            "name": "Purchase Quantity Backorder",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": "CALCULATE(SUM(f_purchaseorders[Quantity]), d_purchaseorderstatus[Purchase Order Status] = \"Backorder\")",
            "lineageTag": "274c6a7d-630f-4515-b6f4-e44bad4e0866"
          }
        ],
        "partitions": [
          {
            "name": "curated_f_purchaseorders",
            "mode": "directLake",
            "source": {
              "entityName": "curated_f_purchaseorders",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_f_purchaseorders]"
      },
      {
        "name": "d_operationalsite",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "OperationalSiteID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eff128d9-0dd3-4ac9-8413-f635f1e40119",
            "sourceColumn": "OperationalSiteID",
            "sourceLineageTag": "OperationalSiteID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Operational Site",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9dab03c0-bdbb-49b3-841e-7c6d70da1b31",
            "sourceColumn": "OperationalSite",
            "sourceLineageTag": "OperationalSite",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Operational Site Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "785ec1e8-a5c9-4f4b-953d-75c90061c17c",
            "sourceColumn": "OperationalSiteType",
            "sourceLineageTag": "OperationalSiteType",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "de0316ba-1298-46f0-b1db-d353fb9f5a71",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          },
          {
            "name": "OperationalSiteNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "228409b7-df1d-4187-b536-84165318202c",
            "sourceColumn": "OperationalSiteNaturalID",
            "sourceLineageTag": "OperationalSiteNaturalID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "21a82c30-dfef-4b72-86f4-a7e2ce470c0d",
        "measures": [
          {
            "name": "Selected Operational Site",
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": "SELECTEDVALUE ( 'd_operationalsite'[Operational Site] )",
            "lineageTag": "ad1aa563-e6f9-4969-8efe-b321d9ecfa94"
          }
        ],
        "partitions": [
          {
            "name": "curated_d_operationalsite",
            "mode": "directLake",
            "source": {
              "entityName": "curated_d_operationalsite",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_operationalsite]"
      },
      {
        "name": "d_supplier",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SupplierID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3619bed5-849d-47d6-9a75-8003f5eba683",
            "sourceColumn": "SupplierID",
            "sourceLineageTag": "SupplierID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Supplier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50e5ca42-b0f9-45cf-b900-e322a2b5c39d",
            "sourceColumn": "Supplier",
            "sourceLineageTag": "Supplier",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Supplier Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3bfdcee-a16c-4bbe-9660-6a403d185c93",
            "sourceColumn": "SupplierCode",
            "sourceLineageTag": "SupplierCode",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "b56c66c3-2838-4a53-8126-d20f0a8ab92f",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          },
          {
            "name": "IsHistory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "b4cea7bb-f00a-4767-8a30-b1f2151425e4",
            "sourceColumn": "IsHistory",
            "sourceLineageTag": "IsHistory",
            "summarizeBy": "none"
          },
          {
            "name": "SupplierNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f359a63-ecf4-4546-9079-989ddef13215",
            "sourceColumn": "SupplierNaturalID",
            "sourceLineageTag": "SupplierNaturalID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b5901aa4-cce7-4ec2-820b-e4361e48ce9a",
        "partitions": [
          {
            "name": "curated_d_supplier",
            "mode": "directLake",
            "source": {
              "entityName": "curated_d_supplier",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_supplier]"
      },
      {
        "name": "d_salesorderstatus",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SalesOrderStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f3da0d4-6455-43dd-ae63-2eaa16a37461",
            "sourceColumn": "SalesOrderStatusID",
            "sourceLineageTag": "SalesOrderStatusID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Order Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd646790-80b0-4901-afe0-5fccf8b86d7a",
            "sourceColumn": "SalesOrderStatus",
            "sourceLineageTag": "SalesOrderStatus",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "e9a15cb2-a115-4bba-aa47-266df5683e15",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrderStatusNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "lineageTag": "ad14adc0-b9ec-4cec-a2f0-7dafecea080e",
            "sourceColumn": "SalesOrderStatusNaturalID",
            "sourceLineageTag": "SalesOrderStatusNaturalID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f8387243-3565-49d7-b4a9-73d6fa452890",
        "partitions": [
          {
            "name": "curated_d_salesorderstatus",
            "mode": "directLake",
            "source": {
              "entityName": "curated_d_salesorderstatus",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_salesorderstatus]"
      },
      {
        "name": "f_inventorysnapshot",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "FK_SnapshotDateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b59200ce-c41d-4f7c-8ac7-8e0095fdd2ea",
            "sourceColumn": "FK_SnapshotDateID",
            "sourceLineageTag": "FK_SnapshotDateID",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0",
            "lineageTag": "3ef1d569-e53b-4141-8f6d-989586a13bf4",
            "sourceColumn": "Quantity",
            "sourceLineageTag": "Quantity",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "7b438607-0070-46fa-829a-47d71ae84512",
            "sourceColumn": "Value",
            "sourceLineageTag": "Value",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Value_ G B P",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "6be4e573-6d75-466b-9287-44e7ff96516d",
            "sourceColumn": "Value_GBP",
            "sourceLineageTag": "Value_GBP",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Value_ E U R",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "64a7d8fb-ba52-424a-8fe9-f2530cb2bd2e",
            "sourceColumn": "Value_EUR",
            "sourceLineageTag": "Value_EUR",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Value_ U S D",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "856b8607-bdb6-4a18-a022-a6ab89aa3b0a",
            "sourceColumn": "Value_USD",
            "sourceLineageTag": "Value_USD",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "b07b7cf8-3de8-4e28-9734-74170da5f616",
            "sourceColumn": "Volume",
            "sourceLineageTag": "Volume",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "FK_LegalEntityID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "12f5ffb0-9d01-498a-981c-8aabfc6b0f20",
            "sourceColumn": "FK_LegalEntityID",
            "sourceLineageTag": "FK_LegalEntityID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_WarehouseID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "371f36fe-0ac8-465a-9820-50b00ec6c08b",
            "sourceColumn": "FK_WarehouseID",
            "sourceLineageTag": "FK_WarehouseID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c17e3a5d-141f-4038-b84f-72634a97c9d9",
            "sourceColumn": "FK_ProductID",
            "sourceLineageTag": "FK_ProductID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Batch",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "lineageTag": "36afc9f9-c617-4865-b411-816a97d71799",
            "sourceColumn": "Batch",
            "sourceLineageTag": "Batch",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "FK_BusinessUnitID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0994b1c8-290b-43d7-a07f-bdcee2f461ff",
            "sourceColumn": "FK_BusinessUnitID",
            "sourceLineageTag": "FK_BusinessUnitID",
            "summarizeBy": "none"
          },
          {
            "name": "FK_CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4d10041c-3535-4a98-abb1-e49153309a64",
            "sourceColumn": "FK_CustomerID",
            "sourceLineageTag": "FK_CustomerID",
            "summarizeBy": "none"
          },
          {
            "name": "InventorySnapshotNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e18fffe-895a-4f5e-ac69-144bdbc99670",
            "sourceColumn": "InventorySnapshotNaturalID",
            "sourceLineageTag": "InventorySnapshotNaturalID",
            "summarizeBy": "none"
          },
          {
            "name": "VolumeKG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DataType"
              }
            ],
            "dataType": "double",
            "formatString": "#,0",
            "lineageTag": "df036707-0f8e-42a1-9301-098c622f531b",
            "sourceColumn": "VolumeKG",
            "sourceLineageTag": "VolumeKG",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "FK_UnitID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "555e865d-161f-4297-910f-c87c9606a229",
            "sourceColumn": "FK_UnitID",
            "sourceLineageTag": "FK_UnitID",
            "summarizeBy": "none"
          },
          {
            "name": "PhysicalStock",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DataType"
              }
            ],
            "dataType": "double",
            "formatString": "#,0",
            "lineageTag": "5e42a29e-c040-40e6-b8ec-14619e3fd3c4",
            "sourceColumn": "PhysicalStock",
            "sourceLineageTag": "PhysicalStock",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "OnOrder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DataType"
              }
            ],
            "dataType": "double",
            "formatString": "#,0",
            "lineageTag": "74990cc3-7f16-4059-86ea-a963632c6861",
            "sourceColumn": "OnOrder",
            "sourceLineageTag": "OnOrder",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8b71497a-572e-47df-9370-ec98e0414efa",
        "measures": [
          {
            "name": "Stock Value",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "AVERAGEX (",
              "    KEEPFILTERS ( VALUES ( 'd_date'[Date] ) ),",
              "    CALCULATE (",
              "        SWITCH (",
              "            SELECTEDVALUE ( S_Currency[Currency], \"None\" ),",
              "            \"GBP\", SUM ( 'f_inventorysnapshot'[Value_ G B P] ),",
              "            \"EUR\", SUM ( 'f_inventorysnapshot'[Value_ E U R] ),",
              "            \"USD\", SUM ( 'f_inventorysnapshot'[Value_ U S D] ),",
              "            BLANK ()",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "71077796-10df-49d9-840a-7d647f0ebc81"
          },
          {
            "name": "Stock Volume",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "AVERAGEX(",
              "    KEEPFILTERS(VALUES('d_date'[Date])),",
              "    CALCULATE(",
              "        SUM('f_inventorysnapshot'[Volume]),",
              "        FILTER(d_unit, d_unit[Unit] <> \"EACH\")",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "ea49cbe0-0a82-4711-9573-481794dc0139"
          },
          {
            "name": "F_IS Date",
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": "TODAY ()",
            "formatString": "General Date",
            "lineageTag": "90060ae8-4cbd-4aee-bdb9-d04c06de8d43"
          },
          {
            "name": "Sum Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM ( f_inventorysnapshot[Quantity] )",
            "lineageTag": "2b4ad2cb-e314-4971-a2f1-ae5da48be074"
          },
          {
            "name": "Sum Volume",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(SUM ( f_inventorysnapshot[Volume] ), FILTER(d_unit, d_unit[Unit] <> \"EACH\"))",
            "lineageTag": "42783b67-1912-4ee6-9fec-260e91eb5f38"
          },
          {
            "name": "Free Stock",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "IF ( [Forward Order Quantity] > 0, [Stock Quantity (Today)] + f_purchaseorders[Purchase Quantity Backorder] - [Forward Order Quantity],",
              "    (  [Stock Quantity (Today)] + f_purchaseorders[Purchase Quantity Backorder] - [Sales Quantity Backorder] ) )"
            ],
            "lineageTag": "2bae5d9c-f3b0-459e-83d4-477dd6747063"
          },
          {
            "name": "Stock Volume T (Today)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": "DIVIDE ( [Stock Volume (Today)], 1000 )",
            "lineageTag": "b528e771-4065-44b3-8251-def130185750"
          },
          {
            "name": "Stock Value (Today)",
            "description": "This measure is a derivative of Stock Value.",
            "displayFolder": "Stock Value",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "RETURN",
              "    CALCULATE (",
              "        [Stock Value],",
              "        'd_date'[Date] = CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "62dc8d41-2024-44a5-8051-c2eeabfb096d"
          },
          {
            "name": "Stock Value (Yesterday)",
            "description": "This measure is a derivative of Stock Value.",
            "displayFolder": "Stock Value",
            "expression": [
              "VAR YesterdayDate =",
              "    TODAY () - 1",
              "RETURN",
              "    CALCULATE (",
              "        [Stock Value],",
              "        'd_date'[Date] = YesterdayDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "241eeab3-3492-47ff-95a7-5957fb011c31"
          },
          {
            "name": "Stock Value (MTD)",
            "description": "This measure is a derivative of Stock Value.",
            "displayFolder": "Stock Value",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR StartdateMonth =",
              "    DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 )",
              "RETURN",
              "    CALCULATE (",
              "        [Stock Value],",
              "        'd_date'[Date] >= StartdateMonth",
              "            && 'd_date'[Date] <= CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "ca21da28-8b0b-4d7e-9416-f88952a3b1fe"
          },
          {
            "name": "Stock Value (PMTD)",
            "description": "This measure is a derivative of Stock Value.",
            "displayFolder": "Stock Value",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR DaysInMonthSoFar =",
              "    DAY ( CurrentDate )",
              "VAR StartOfPriorMonth =",
              "    EDATE ( DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 ), -1 )",
              "VAR EndOfPriorMonth = StartOfPriorMonth + DaysInMonthSoFar - 1",
              "RETURN",
              "    CALCULATE (",
              "        [Stock Value],",
              "        'd_date'[Date] >= StartOfPriorMonth",
              "            && 'd_date'[Date] <= EndOfPriorMonth,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "b3304c9b-6fc2-4266-b16f-405126cdbb36"
          },
          {
            "name": "Stock Value (YTD)",
            "description": "This measure is a derivative of Stock Value.",
            "displayFolder": "Stock Value",
            "expression": "[Stock Value]",
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "9780a478-bd42-4e29-a552-ed0bb702d48f"
          },
          {
            "name": "Stock Value (PYTD)",
            "description": "This measure is a derivative of Stock Value.",
            "displayFolder": "Stock Value",
            "expression": [
              "CALCULATE (",
              "    [Stock Value],",
              "    REMOVEFILTERS ( d_date ),",
              "    FILTER (",
              "        DATEADD ( d_date[Date], -1, YEAR ),",
              "        d_date[Date]",
              "            <= DATE ( YEAR ( TODAY () - 1 ), MONTH ( TODAY () ), DAY ( TODAY () ) )",
              "    )",
              ")"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "9ab99f9a-415a-458a-9129-9678e437e329"
          },
          {
            "name": "Stock Volume (Today)",
            "description": "This measure is a derivative of Stock Volume.",
            "displayFolder": "Stock Volume",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "RETURN",
              "    CALCULATE (",
              "        [Stock Volume],",
              "        'd_date'[Date] = CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "d3017545-6bbc-4370-a7fb-a476439fca9b"
          },
          {
            "name": "Stock Volume (Yesterday)",
            "description": "This measure is a derivative of Stock Volume.",
            "displayFolder": "Stock Volume",
            "expression": [
              "VAR YesterdayDate =",
              "    TODAY () - 1",
              "RETURN",
              "    CALCULATE (",
              "        [Stock Volume],",
              "        'd_date'[Date] = YesterdayDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "c4596d3f-fb7d-4dfe-911f-ce754f3646c4"
          },
          {
            "name": "Stock Volume (MTD)",
            "description": "This measure is a derivative of Stock Volume.",
            "displayFolder": "Stock Volume",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR StartdateMonth =",
              "    DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 )",
              "RETURN",
              "    CALCULATE (",
              "        [Stock Volume],",
              "        'd_date'[Date] >= StartdateMonth",
              "            && 'd_date'[Date] <= CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "a0d9f3d2-9959-42c2-9a5d-aff8c05d7222"
          },
          {
            "name": "Stock Volume (PMTD)",
            "description": "This measure is a derivative of Stock Volume.",
            "displayFolder": "Stock Volume",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR DaysInMonthSoFar =",
              "    DAY ( CurrentDate )",
              "VAR StartOfPriorMonth =",
              "    EDATE ( DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 ), -1 )",
              "VAR EndOfPriorMonth = StartOfPriorMonth + DaysInMonthSoFar - 1",
              "RETURN",
              "    CALCULATE (",
              "        [Stock Volume],",
              "        'd_date'[Date] >= StartOfPriorMonth",
              "            && 'd_date'[Date] <= EndOfPriorMonth,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "d48e17a3-2328-4a2a-9bbe-c7d88c9ffc36"
          },
          {
            "name": "Stock Volume (YTD)",
            "description": "This measure is a derivative of Stock Volume.",
            "displayFolder": "Stock Volume",
            "expression": "[Stock Volume]",
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "7f6aa24c-6a9c-4a6c-9621-76446809f0aa"
          },
          {
            "name": "Stock Volume (PYTD)",
            "description": "This measure is a derivative of Stock Volume.",
            "displayFolder": "Stock Volume",
            "expression": [
              "CALCULATE (",
              "    [Stock Volume],",
              "    REMOVEFILTERS ( d_date ),",
              "    FILTER (",
              "        DATEADD ( d_date[Date], -1, YEAR ),",
              "        d_date[Date]",
              "            <= DATE ( YEAR ( TODAY () - 1 ), MONTH ( TODAY () ), DAY ( TODAY () ) )",
              "    )",
              ")"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "20e93068-bd59-4968-9d9f-5db811fc8ba4"
          },
          {
            "name": "Stock Value (Today vs Yesterday)",
            "displayFolder": "Stock Value",
            "expression": [
              "IF (",
              "    ISBLANK ( [Stock Value (Yesterday)] ),",
              "    BLANK (),",
              "    DIVIDE (",
              "        [Stock Value (Today)] - [Stock Value (Yesterday)],",
              "        [Stock Value (Yesterday)],",
              "        0",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "79144cc6-e399-4b4e-b5e3-40926686072b"
          },
          {
            "name": "Stock Value (Today vs Yesterday) ARROW",
            "description": "This measure is a derivative of Stock Value.",
            "displayFolder": "Stock Value",
            "expression": [
              "IF (",
              "    [Stock Value (Today vs Yesterday)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF ( [Stock Value (Today vs Yesterday)] = 0, UNICHAR ( 45 ), UNICHAR ( 8595 ) )",
              ")"
            ],
            "lineageTag": "0e2cfa5c-008f-4de8-bd05-107678fd5b15"
          },
          {
            "name": "Stock Value (MTD vs PMTD)",
            "displayFolder": "Stock Value",
            "expression": [
              "IF (",
              "    ISBLANK ( [Stock Value (PMTD)] ),",
              "    BLANK (),",
              "    DIVIDE ( [Stock Value (MTD)] - [Stock Value (PMTD)], [Stock Value (PMTD)], 0 )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "b77141f5-9f56-4fd0-ad1f-7fbbaf425bfb"
          },
          {
            "name": "Stock Value (MTD vs PMTD) ARROW",
            "description": "This measure is a derivative of Stock Value.",
            "displayFolder": "Stock Value",
            "expression": [
              "IF (",
              "    [Stock Value (MTD vs PMTD)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF ( [Stock Value (MTD vs PMTD)] = 0, UNICHAR ( 45 ), UNICHAR ( 8595 ) )",
              ")"
            ],
            "lineageTag": "b32f68e4-e057-4926-81fa-21924a510d5b"
          },
          {
            "name": "Stock Value (YTD vs PYTD)",
            "displayFolder": "Stock Value",
            "expression": [
              "IF (",
              "    ISBLANK ( [Stock Value (PYTD)] ),",
              "    BLANK (),",
              "    DIVIDE ( [Stock Value (YTD)] - [Stock Value (PYTD)], [Stock Value (PYTD)], 0 )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "50780d17-1637-4880-b3ec-faf11e2fa829"
          },
          {
            "name": "Stock Value (YTD vs PYTD) ARROW",
            "description": "This measure is a derivative of Stock Value.",
            "displayFolder": "Stock Value",
            "expression": [
              "IF (",
              "    [Stock Value (YTD vs PYTD)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF ( [Stock Value (YTD vs PYTD)] = 0, UNICHAR ( 45 ), UNICHAR ( 8595 ) )",
              ")"
            ],
            "lineageTag": "7052047b-f3bc-467f-a3ce-ca002fae6e26"
          },
          {
            "name": "Stock Volume (Today vs Yesterday)",
            "displayFolder": "Stock Volume",
            "expression": [
              "IF (",
              "    ISBLANK ( [Stock Volume (Yesterday)] ),",
              "    BLANK (),",
              "    DIVIDE (",
              "        [Stock Volume (Today)] - [Stock Volume (Yesterday)],",
              "        [Stock Volume (Yesterday)],",
              "        0",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "a0e6f4a1-d92e-4428-91ea-50e761f5c52c"
          },
          {
            "name": "Stock Volume (Today vs Yesterday) ARROW",
            "description": "This measure is a derivative of Stock Volume.",
            "displayFolder": "Stock Volume",
            "expression": [
              "IF (",
              "    [Stock Volume (Today vs Yesterday)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF ( [Stock Volume (Today vs Yesterday)] = 0, UNICHAR ( 45 ), UNICHAR ( 8595 ) )",
              ")"
            ],
            "lineageTag": "58b211e7-8b9b-4c43-b373-53baabc1b4df"
          },
          {
            "name": "Stock Volume (MTD vs PMTD)",
            "displayFolder": "Stock Volume",
            "expression": [
              "IF (",
              "    ISBLANK ( [Stock Volume (PMTD)] ),",
              "    BLANK (),",
              "    DIVIDE (",
              "        [Stock Volume (MTD)] - [Stock Volume (PMTD)],",
              "        [Stock Volume (PMTD)],",
              "        0",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "81e94b0b-0bf2-47d0-8416-cf759b306902"
          },
          {
            "name": "Stock Volume (MTD vs PMTD) ARROW",
            "description": "This measure is a derivative of Stock Volume.",
            "displayFolder": "Stock Volume",
            "expression": [
              "IF (",
              "    [Stock Volume (MTD vs PMTD)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF ( [Stock Volume (MTD vs PMTD)] = 0, UNICHAR ( 45 ), UNICHAR ( 8595 ) )",
              ")"
            ],
            "lineageTag": "99fd363a-5c76-4848-93b7-3dbba914ca06"
          },
          {
            "name": "Stock Volume (YTD vs PYTD)",
            "displayFolder": "Stock Volume",
            "expression": [
              "IF (",
              "    ISBLANK ( [Stock Volume (PYTD)] ),",
              "    BLANK (),",
              "    DIVIDE (",
              "        [Stock Volume (YTD)] - [Stock Volume (PYTD)],",
              "        [Stock Volume (PYTD)],",
              "        0",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "be4282f7-0144-416d-8d61-d909896a70cb"
          },
          {
            "name": "Stock Volume (YTD vs PYTD) ARROW",
            "description": "This measure is a derivative of Stock Volume.",
            "displayFolder": "Stock Volume",
            "expression": [
              "IF (",
              "    [Stock Volume (YTD vs PYTD)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF ( [Stock Volume (YTD vs PYTD)] = 0, UNICHAR ( 45 ), UNICHAR ( 8595 ) )",
              ")"
            ],
            "lineageTag": "a4ba82fd-57e4-4609-bc34-76b413cafee7"
          },
          {
            "name": "Volume T (S)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": "CALCULATE(DIVIDE(SUM(f_inventorysnapshot[Volume]), 1000), FILTER(d_unit, d_unit[Unit] <> \"EACH\"))",
            "lineageTag": "f410a168-681e-471b-9e7d-6f560b698788"
          },
          {
            "name": "Stock Quantity (Today)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": [
              "VAR CurrentDate = TODAY ()",
              "RETURN",
              "    CALCULATE (SUM([Quantity]), 'd_date'[Date] = CurrentDate )"
            ],
            "lineageTag": "0fff166d-e37a-4b86-9d38-0f7cbe236f2b"
          },
          {
            "name": "Quantity (excl. 0)",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE(",
              "    SUM(f_inventorysnapshot[Quantity]),",
              "    FILTER(",
              "        f_inventorysnapshot,",
              "        f_inventorysnapshot[Quantity] <> 0",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "e48f647e-4009-4e8c-b091-049f2e5f0e71"
          },
          {
            "name": "Total Current Stock",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": "SUM(f_inventorysnapshot[PhysicalStock])",
            "lineageTag": "9ac066b4-c854-4a78-b8b4-1aecc0768aab"
          },
          {
            "name": "Total On Order",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": "SUM(f_inventorysnapshot[OnOrder])",
            "lineageTag": "6402cc9e-7703-46e7-8af2-158c59e00a9f"
          },
          {
            "name": "Consignment Free Stock",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": "[Total Current Stock] - [Total On Order]",
            "lineageTag": "f284b1b3-3e8c-4006-82a0-d474c11af678"
          }
        ],
        "partitions": [
          {
            "name": "curated_f_inventorysnapshot",
            "mode": "directLake",
            "source": {
              "entityName": "curated_f_inventorysnapshot",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_f_inventorysnapshot]"
      },
      {
        "name": "d_tank",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "TankID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "418b8a0c-19b4-4a1c-a9df-8705d93b2b0a",
            "sourceColumn": "TankID",
            "sourceLineageTag": "TankID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Tank",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07b18ae1-70ed-439e-a548-2ebba0600aa1",
            "sourceColumn": "Tank",
            "sourceLineageTag": "Tank",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Capacity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c198c096-f0b3-44f5-a5d3-2c5102fd2fe2",
            "sourceColumn": "Capacity",
            "sourceLineageTag": "Capacity",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "f1c81b70-ac9a-4344-81aa-194501477bb8",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          },
          {
            "name": "TankNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b496c45c-c8dd-43c9-a1f6-9d73039c03a2",
            "sourceColumn": "TankNaturalID",
            "sourceLineageTag": "TankNaturalID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "19e6c7c7-728a-46df-bcdf-ba304827775b",
        "partitions": [
          {
            "name": "curated_d_tank",
            "mode": "directLake",
            "source": {
              "entityName": "curated_d_tank",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_tank]"
      },
      {
        "name": "d_customer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "36ef3360-ceed-4c1c-8a3c-b88e59eb5111",
            "sourceColumn": "CustomerID",
            "sourceLineageTag": "CustomerID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c9be51ad-338d-49d7-8697-676579f2e1b2",
            "sourceColumn": "CustomerCode",
            "sourceLineageTag": "CustomerCode",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a33f9516-a3dc-4b02-ad80-4a1b257272b9",
            "sourceColumn": "Customer",
            "sourceLineageTag": "Customer",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Sector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "060936d8-ba53-4f02-89f6-e645c67559d0",
            "sourceColumn": "Sector",
            "sourceLineageTag": "Sector",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Sub Sector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1235e84-5d1f-42bc-adf5-babaae37152b",
            "sourceColumn": "SubSector",
            "sourceLineageTag": "SubSector",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d96cc90-7db3-4e98-86b3-cf14bfbc613f",
            "sourceColumn": "CustomerGroup",
            "sourceLineageTag": "CustomerGroup",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessUnitNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "lineageTag": "b2b40629-2f30-4d02-b390-895f2347cfd6",
            "sourceColumn": "BusinessUnitNaturalID",
            "sourceLineageTag": "BusinessUnitNaturalID",
            "summarizeBy": "count"
          },
          {
            "name": "CustomerNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d88225ba-9bed-4fee-8037-ff6b1a02980d",
            "sourceColumn": "CustomerNaturalID",
            "sourceLineageTag": "CustomerNaturalID",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "7208a9dc-b926-4a05-b6d2-700a58696c5a",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          },
          {
            "name": "IsHistory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "e6c83b7f-18ea-4ff0-a83a-ee2b7f84fa37",
            "sourceColumn": "IsHistory",
            "sourceLineageTag": "IsHistory",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bf9aa604-cee4-43ac-a117-8e03e492c9b6",
        "partitions": [
          {
            "name": "curated_d_customer",
            "mode": "directLake",
            "source": {
              "entityName": "curated_d_customer",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_customer]"
      },
      {
        "name": "d_warehouse",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "WarehouseID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef4200e9-a391-499b-a29e-2acfc670505b",
            "sourceColumn": "WarehouseID",
            "sourceLineageTag": "WarehouseID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_OperationalSiteID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "54e1b838-52cb-4a8e-99c3-560a422846a5",
            "sourceColumn": "FK_OperationalSiteID",
            "sourceLineageTag": "FK_OperationalSiteID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Warehouse",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a3d874e-4e2b-4b8a-b0ed-4e323520a496",
            "sourceColumn": "Warehouse",
            "sourceLineageTag": "Warehouse",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "554a6e91-e6f7-4a2f-862c-0192bef6238e",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          },
          {
            "name": "IsHistory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "bc4ed7a2-840f-4c24-b962-76a269210697",
            "sourceColumn": "IsHistory",
            "sourceLineageTag": "IsHistory",
            "summarizeBy": "none"
          },
          {
            "name": "WarehouseNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "da5a4e9f-52ca-4e10-ac7d-13d88e503567",
            "sourceColumn": "WarehouseNaturalID",
            "sourceLineageTag": "WarehouseNaturalID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4a857172-491a-4140-ad97-ab7a7eea27f0",
        "partitions": [
          {
            "name": "curated_d_warehouse",
            "mode": "directLake",
            "source": {
              "entityName": "curated_d_warehouse",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_warehouse]"
      },
      {
        "name": "d_purchaseorderstatus",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PurchaseOrderStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a156742-50eb-4eec-964d-20633638504c",
            "sourceColumn": "PurchaseOrderStatusID",
            "sourceLineageTag": "PurchaseOrderStatusID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Purchase Order Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e0a034d-e270-473c-9f21-f9631fa8eda9",
            "sourceColumn": "PurchaseOrderStatus",
            "sourceLineageTag": "PurchaseOrderStatus",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "270eba2f-cc1f-4f77-a643-72c08842467a",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          },
          {
            "name": "PurchaseOrderStatusNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "lineageTag": "4cf6cfb3-b974-4abe-ad3d-a27273205957",
            "sourceColumn": "PurchaseOrderStatusNaturalID",
            "sourceLineageTag": "PurchaseOrderStatusNaturalID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "79add743-70fd-42ff-aac8-d8a07f5419de",
        "partitions": [
          {
            "name": "curated_d_purchaseorderstatus",
            "mode": "directLake",
            "source": {
              "entityName": "curated_d_purchaseorderstatus",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_purchaseorderstatus]"
      },
      {
        "name": "d_unit",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "UnitID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fff14457-443f-4646-8e6c-9f34f9225eeb",
            "sourceColumn": "UnitID",
            "sourceLineageTag": "UnitID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f25156a-b5d0-4677-9b60-467df3b7de47",
            "sourceColumn": "Unit",
            "sourceLineageTag": "Unit",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Class",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "62870697-7184-44a3-9299-13df8e04e073",
            "sourceColumn": "UnitClass",
            "sourceLineageTag": "UnitClass",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "85b5db99-8f76-4952-b471-9e777957a858",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          },
          {
            "name": "UnitNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4a13ac0d-cf71-40ae-b1f6-26394be21d66",
            "sourceColumn": "UnitNaturalID",
            "sourceLineageTag": "UnitNaturalID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e04a71c8-b48f-4015-bf42-ff24670e14ea",
        "partitions": [
          {
            "name": "curated_d_unit",
            "mode": "directLake",
            "source": {
              "entityName": "curated_d_unit",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_unit]"
      },
      {
        "name": "d_businessunit",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "BusinessUnitID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2211c1b-4568-4003-b9f8-6bd1a6cf5cdb",
            "sourceColumn": "BusinessUnitID",
            "sourceLineageTag": "BusinessUnitID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Business Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f9861339-5fa5-4f35-934e-391ed62569c8",
            "sourceColumn": "BusinessUnit",
            "sourceLineageTag": "BusinessUnit",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Business Unit Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "050056e9-ab78-4e2d-a045-96b75ef2b238",
            "sourceColumn": "BusinessUnitCode",
            "sourceLineageTag": "BusinessUnitCode",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessUnitNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "lineageTag": "ba583828-98f5-4623-af05-ce508bbb94c6",
            "sourceColumn": "BusinessUnitNaturalID",
            "sourceLineageTag": "BusinessUnitNaturalID",
            "summarizeBy": "count"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "773bfa25-d0c9-444d-8e87-b73a252d4d50",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "02ccd361-b0fe-45aa-8ab4-5a517eb668c9",
        "partitions": [
          {
            "name": "curated_d_businessunit",
            "mode": "directLake",
            "source": {
              "entityName": "curated_d_businessunit",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_businessunit]"
      },
      {
        "name": "f_tankreadings",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Opening Tank Reading",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7d436759-47c4-4dd8-9f43-33ef1b2ca7a6",
            "sourceColumn": "OpeningTankReading",
            "sourceLineageTag": "OpeningTankReading",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Closing Tank Reading",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "04fcdecd-9981-4b60-a3b3-d5b0ae51be6e",
            "sourceColumn": "ClosingTankReading",
            "sourceLineageTag": "ClosingTankReading",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Opening Stock Reading",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1959acc7-48bb-4653-b235-adb338ee7386",
            "sourceColumn": "OpeningStockReading",
            "sourceLineageTag": "OpeningStockReading",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Closing Stock Reading",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "15c705c6-e10c-431c-984a-59a248aecd10",
            "sourceColumn": "ClosingStockReading",
            "sourceLineageTag": "ClosingStockReading",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "FK_ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "dd1447b3-0a13-469a-9b2d-62e225bfcb62",
            "sourceColumn": "FK_ProductID",
            "sourceLineageTag": "FK_ProductID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c2dd7e21-c126-4e30-92a5-d57f43a7e61e",
            "sourceColumn": "FK_DateID",
            "sourceLineageTag": "FK_DateID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_TankID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "8c715150-20a4-4f98-812d-2e8a3f4b8263",
            "sourceColumn": "FK_TankID",
            "sourceLineageTag": "FK_TankID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "End Of Day Variance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "216161c1-e115-4440-b284-e1df09517efe",
            "sourceColumn": "EndOfDayVariance",
            "sourceLineageTag": "EndOfDayVariance",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "TankReadingNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c8319df-3c64-438f-8e48-c7ff492021b1",
            "sourceColumn": "TankReadingNaturalID",
            "sourceLineageTag": "TankReadingNaturalID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4ded9f42-e552-4c09-9551-71567787f537",
        "measures": [
          {
            "name": "No. Variances",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE (",
              "    COUNTROWS ( F_TankReadings ),",
              "    F_TankReadings[End of Day Variance] <> 0",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "ff92510c-44aa-4292-90ba-ac6ec064174f"
          },
          {
            "name": "Total Tank Capacity %",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE ( [Total Volume Held], SUM ( d_tank[Capacity] ) )",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "fe8bb2f4-9c0c-484c-b70c-4e05e56c826a"
          },
          {
            "name": "Total Tank Variance",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE (",
              "    SUMX ( f_tankreadings, ABS ( f_tankreadings[End of Day Variance] ) )",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "bc8493d8-7a4b-4846-abd7-d56d478a5065"
          },
          {
            "name": "Total Volume Held",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM ( f_tankreadings[Closing Tank Reading] )",
            "formatString": "#,0.00",
            "lineageTag": "9cac0c10-0e69-45c6-bbb4-ebb7779d5a14"
          },
          {
            "name": "Total Tank Variance (Today)",
            "description": "This measure is a derivative of Total Tank Variance.",
            "displayFolder": "Total Tank Variance",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "RETURN",
              "    CALCULATE (",
              "        [Total Tank Variance],",
              "        'd_date'[Date] = CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "50799493-b9a5-4ea9-8b75-d1fabfd64fb6"
          },
          {
            "name": "Total Tank Variance (Yesterday)",
            "description": "This measure is a derivative of Total Tank Variance.",
            "displayFolder": "Total Tank Variance",
            "expression": [
              "VAR YesterdayDate =",
              "    TODAY () - 1",
              "RETURN",
              "    CALCULATE (",
              "        [Total Tank Variance],",
              "        'd_date'[Date] = YesterdayDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "392b7acb-b0ca-4f87-bb48-3a40cf43ee53"
          },
          {
            "name": "Total Tank Capacity % (Today)",
            "description": "This measure is a derivative of Total Tank Capacity %.",
            "displayFolder": "Total Tank Capacity %",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "RETURN",
              "    CALCULATE (",
              "        [Total Tank Capacity %],",
              "        'd_date'[Date] = CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "208b4c99-ab21-436a-9a9e-95aaa9131330"
          },
          {
            "name": "Total Tank Capacity % (Yesterday)",
            "description": "This measure is a derivative of Total Tank Capacity %.",
            "displayFolder": "Total Tank Capacity %",
            "expression": [
              "VAR YesterdayDate =",
              "    TODAY () - 1",
              "RETURN",
              "    CALCULATE (",
              "        [Total Tank Capacity %],",
              "        'd_date'[Date] = YesterdayDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "cfca0c2e-018d-42c0-ace1-0a1fc64b103e"
          },
          {
            "name": "No. Variances (Today)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "This measure is a derivative of No. Variances.",
            "displayFolder": "No. Variances",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "RETURN",
              "    CALCULATE (",
              "        [No. Variances],",
              "        'd_date'[Date] = CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "8ae2f6ab-5167-475e-be15-40618d8d5fb9"
          },
          {
            "name": "No. Variances (Yesterday)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "This measure is a derivative of No. Variances.",
            "displayFolder": "No. Variances",
            "expression": [
              "VAR YesterdayDate =",
              "    TODAY () - 1",
              "RETURN",
              "    CALCULATE (",
              "        [No. Variances],",
              "        'd_date'[Date] = YesterdayDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "914e0b8d-495a-45a1-aeae-25be73cc17db"
          },
          {
            "name": "Total Volume Held (Today)",
            "description": "This measure is a derivative of Total Volume Held.",
            "displayFolder": "Total Volume Held",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "RETURN",
              "    CALCULATE (",
              "        [Total Volume Held],",
              "        'd_date'[Date] = CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "1d1b67a5-1374-44de-bc26-89507820c5b1"
          },
          {
            "name": "Total Volume Held (Yesterday)",
            "description": "This measure is a derivative of Total Volume Held.",
            "displayFolder": "Total Volume Held",
            "expression": [
              "VAR YesterdayDate =",
              "    TODAY () - 1",
              "RETURN",
              "    CALCULATE (",
              "        [Total Volume Held],",
              "        'd_date'[Date] = YesterdayDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "91eb2403-6065-49f1-8a99-bdab2366973b"
          },
          {
            "name": "Total Tank Variance (Today vs Yesterday)",
            "displayFolder": "Total Tank Variance",
            "expression": [
              "IF (",
              "    ISBLANK ( [Total Tank Variance (Yesterday)] ),",
              "    BLANK (),",
              "    IF (",
              "        ISBLANK ( [Total Tank Variance (Today)] ),",
              "        BLANK (),",
              "        DIVIDE (",
              "            [Total Tank Variance (Today)] - [Total Tank Variance (Yesterday)],",
              "            [Total Tank Variance (Yesterday)],",
              "            0",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "81a43e6a-1d4b-4b82-bf2e-be5601e3383a"
          },
          {
            "name": "Total Tank Variance (Today vs Yesterday) ARROW",
            "description": "This measure is a derivative of Total Tank Variance.",
            "displayFolder": "Total Tank Variance",
            "expression": [
              "IF (",
              "    [Total Tank Variance (Today vs Yesterday)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF (",
              "        [Total Tank Variance (Today vs Yesterday)] = 0,",
              "        UNICHAR ( 45 ),",
              "        IF (",
              "            [Total Tank Variance (Today vs Yesterday)] = BLANK (),",
              "            UNICHAR ( 45 ),",
              "            UNICHAR ( 8595 )",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "67365b20-6202-4f2d-b750-616d39a9611f"
          },
          {
            "name": "Total Tank Capacity % (Today vs Yesterday)",
            "displayFolder": "Total Tank Capacity %",
            "expression": [
              "IF (",
              "    ISBLANK ( [Total Tank Capacity % (Yesterday)] ),",
              "    BLANK (),",
              "    IF (",
              "        ISBLANK ( [Total Tank Capacity % (Today)] ),",
              "        BLANK (),",
              "        DIVIDE (",
              "            [Total Tank Capacity % (Today)] - [Total Tank Capacity % (Yesterday)],",
              "            [Total Tank Capacity % (Yesterday)],",
              "            0",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "adcfe1a5-8434-459a-b4ec-f13fc85b009b"
          },
          {
            "name": "Total Tank Capacity % (Today vs Yesterday) ARROW",
            "description": "This measure is a derivative of Total Tank Capacity %.",
            "displayFolder": "Total Tank Capacity %",
            "expression": [
              "IF (",
              "    [Total Tank Capacity % (Today vs Yesterday)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF (",
              "        [Total Tank Capacity % (Today vs Yesterday)] = 0,",
              "        UNICHAR ( 45 ),",
              "        IF (",
              "            [Total Tank Capacity % (Today vs Yesterday)] = BLANK (),",
              "            UNICHAR ( 45 ),",
              "            UNICHAR ( 8595 )",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "4f54aec4-d6f2-475e-a154-8ecdb3046c3d"
          },
          {
            "name": "No. Variances (Today vs Yesterday)",
            "displayFolder": "No. Variances",
            "expression": [
              "IF (",
              "    ISBLANK ( [No. Variances (Yesterday)] ),",
              "    BLANK (),",
              "    IF (",
              "        ISBLANK ( [No. Variances (Today)] ),",
              "        BLANK (),",
              "        DIVIDE (",
              "            [No. Variances (Today)] - [No. Variances (Yesterday)],",
              "            [No. Variances (Yesterday)],",
              "            0",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "ac9f638a-3cdc-45d6-b001-9fd3408d770c"
          },
          {
            "name": "No. Variances (Today vs Yesterday) ARROW",
            "description": "This measure is a derivative of No. Variances.",
            "displayFolder": "No. Variances",
            "expression": [
              "IF (",
              "    [No. Variances (Today vs Yesterday)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF (",
              "        [No. Variances (Today vs Yesterday)] = 0,",
              "        UNICHAR ( 45 ),",
              "        IF (",
              "            [No. Variances (Today vs Yesterday)] = BLANK (),",
              "            UNICHAR ( 45 ),",
              "            UNICHAR ( 8595 )",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "66bafd0c-d31f-4133-a5e3-da47cf8cf904"
          },
          {
            "name": "Total Volume Held (Today vs Yesterday)",
            "displayFolder": "Total Volume Held",
            "expression": [
              "IF (",
              "    ISBLANK ( [Total Volume Held (Yesterday)] ),",
              "    BLANK (),",
              "    IF (",
              "        ISBLANK ( [Total Volume Held (Today)] ),",
              "        BLANK (),",
              "        DIVIDE (",
              "            [Total Volume Held (Today)] - [Total Volume Held (Yesterday)],",
              "            [Total Volume Held (Yesterday)],",
              "            0",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "4b60daaf-02ec-4217-b3d4-8720bb1fdfbf"
          },
          {
            "name": "Total Volume Held (Today vs Yesterday) ARROW",
            "description": "This measure is a derivative of Total Volume Held.",
            "displayFolder": "Total Volume Held",
            "expression": [
              "IF (",
              "    [Total Volume Held (Today vs Yesterday)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF (",
              "        [Total Volume Held (Today vs Yesterday)] = 0,",
              "        UNICHAR ( 45 ),",
              "        IF (",
              "            [Total Volume Held (Today vs Yesterday)] = BLANK (),",
              "            UNICHAR ( 45 ),",
              "            UNICHAR ( 8595 )",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "fa12c9c5-e3e6-474a-89c9-021c7828b76a"
          }
        ],
        "partitions": [
          {
            "name": "curated_f_tankreadings",
            "mode": "directLake",
            "source": {
              "entityName": "curated_f_tankreadings",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_f_tankreadings]"
      },
      {
        "name": "f_salesorders",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SalesOrderID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b8643f6d-4d88-4d50-bb36-81488753bf22",
            "sourceColumn": "SalesOrderID",
            "sourceLineageTag": "SalesOrderID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Line Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6b9e4f2d-eeb7-4895-9afb-2ac0f89fba6d",
            "sourceColumn": "LineNumber",
            "sourceLineageTag": "LineNumber",
            "sourceProviderType": "bigint",
            "summarizeBy": "sum"
          },
          {
            "name": "FK_DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a65976fa-bba2-427d-b1d4-0a06ab98e252",
            "sourceColumn": "FK_DateID",
            "sourceLineageTag": "FK_DateID",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "FK_WarehouseID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1ef16567-bf1a-4767-9b90-7e20b4027dfa",
            "sourceColumn": "FK_WarehouseID",
            "sourceLineageTag": "FK_WarehouseID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_LegalEntityID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a5884836-b805-474f-8beb-832df8439e54",
            "sourceColumn": "FK_LegalEntityID",
            "sourceLineageTag": "FK_LegalEntityID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_SalesOrderStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ed2d841a-83ad-47d5-8627-0dd4f626d0ee",
            "sourceColumn": "FK_SalesOrderStatusID",
            "sourceLineageTag": "FK_SalesOrderStatusID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_DocumentStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c1d57b6b-2853-4880-b2c2-9ea192a0e6b9",
            "sourceColumn": "FK_DocumentStatusID",
            "sourceLineageTag": "FK_DocumentStatusID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_DeliveryAddressID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "33ea3f69-7fa3-4848-a1ef-2944356b147f",
            "sourceColumn": "FK_DeliveryAddressID",
            "sourceLineageTag": "FK_DeliveryAddressID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_UnitID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "332774d9-e555-4dd3-8f07-c9f6243c0c91",
            "sourceColumn": "FK_UnitID",
            "sourceLineageTag": "FK_UnitID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "e99ef39d-51bd-4969-b79d-54f1759a770f",
            "sourceColumn": "FK_ProductID",
            "sourceLineageTag": "FK_ProductID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b400451d-2e6d-49a2-8fcc-af1e84a5d423",
            "sourceColumn": "FK_CustomerID",
            "sourceLineageTag": "FK_CustomerID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_SalesTeamID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0c713fb9-31aa-4246-a3ef-d533c34890bb",
            "sourceColumn": "FK_SalesTeamID",
            "sourceLineageTag": "FK_SalesTeamID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Total Amount_ G B P",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "b38c04fd-c150-4169-bb39-909432177b4a",
            "sourceColumn": "TotalAmount_GBP",
            "sourceLineageTag": "TotalAmount_GBP",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Amount_ E U R",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "1705add0-efd3-412e-abac-25633b5fe151",
            "sourceColumn": "TotalAmount_EUR",
            "sourceLineageTag": "TotalAmount_EUR",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Amount_ U S D",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "52df8f26-7d0c-4ff6-84dc-083b3bcc597f",
            "sourceColumn": "TotalAmount_USD",
            "sourceLineageTag": "TotalAmount_USD",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantity Ordered",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "bd0a5881-aab4-4e99-8194-088065be0b23",
            "sourceColumn": "QuantityOrdered",
            "sourceLineageTag": "QuantityOrdered",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantity Fulfilled",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "24577477-070f-4132-93d3-9178e65f80ae",
            "sourceColumn": "QuantityFulfilled",
            "sourceLineageTag": "QuantityFulfilled",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Margin_ G B P",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "da3a8674-9cdc-4dc6-87e0-90c565a7c95b",
            "sourceColumn": "TotalMargin_GBP",
            "sourceLineageTag": "TotalMargin_GBP",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Margin_ E U R",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "3a5f5fa9-66f2-426e-9379-61a3e81329cc",
            "sourceColumn": "TotalMargin_EUR",
            "sourceLineageTag": "TotalMargin_EUR",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Margin_ U S D",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "2a90ec68-acd5-4c8e-a294-63db629e1cbf",
            "sourceColumn": "TotalMargin_USD",
            "sourceLineageTag": "TotalMargin_USD",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross Weight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "349fef3f-6a6a-4d2e-ac8a-d271db023868",
            "sourceColumn": "GrossWeight",
            "sourceLineageTag": "GrossWeight",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Net Weight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "190b7c4f-535b-4fd0-ae42-e984bb08f639",
            "sourceColumn": "NetWeight",
            "sourceLineageTag": "NetWeight",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Pallets Required",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "0ae5cb61-a57c-4132-9463-d0ce209acb75",
            "sourceColumn": "PalletsRequired",
            "sourceLineageTag": "PalletsRequired",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "Is Full Load",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "9cd9d57f-8df5-4781-b87a-deed1b6c867a",
            "sourceColumn": "IsFullLoad",
            "sourceLineageTag": "IsFullLoad",
            "sourceProviderType": "bit",
            "summarizeBy": "none"
          },
          {
            "name": "FK_BusinessUnitID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b0818e98-849e-4ca4-8c53-d09622f7e32c",
            "sourceColumn": "FK_BusinessUnitID",
            "sourceLineageTag": "FK_BusinessUnitID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_SalesAreaID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "63d563dc-6f3c-4277-85e3-191a775089b0",
            "sourceColumn": "FK_SalesAreaID",
            "sourceLineageTag": "FK_SalesAreaID",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "bdd342d5-26aa-4ca6-9997-4fa03cbff6cf",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrderLineNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a271dc3-efbf-485d-a487-ff05be86c58b",
            "sourceColumn": "SalesOrderLineNaturalID",
            "sourceLineageTag": "SalesOrderLineNaturalID",
            "summarizeBy": "none"
          },
          {
            "name": "FK_ShippingDateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "0e60fde8-6639-4002-a22f-761a4f40bf6f",
            "sourceColumn": "FK_ShippingDateID",
            "sourceLineageTag": "FK_ShippingDateID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Net Weight KG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "e7993049-6296-4213-948b-bfd243da220f",
            "sourceColumn": "NetWeightKG",
            "sourceLineageTag": "NetWeightKG",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "In Credit Control",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "21211e40-8a72-457d-a755-99267feb69db",
            "sourceColumn": "InCreditControl",
            "sourceLineageTag": "InCreditControl",
            "sourceProviderType": "real",
            "summarizeBy": "none"
          },
          {
            "name": "VolumeKG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "37d1a0f7-2f0c-4e68-aa7c-61fe419472d9",
            "sourceColumn": "VolumeKG",
            "sourceLineageTag": "VolumeKG",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "MBSSalesUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc28030f-c6f4-4a28-b5a3-7851b70088c9",
            "sourceColumn": "MBSSalesUnit",
            "sourceLineageTag": "MBSSalesUnit",
            "sourceProviderType": "real",
            "summarizeBy": "none"
          },
          {
            "name": "MBSSalesPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "lineageTag": "310a52a9-c1d8-4d2f-b366-a61f1b5eb1f9",
            "sourceColumn": "MBSSalesPrice",
            "sourceLineageTag": "MBSSalesUnit",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "303e7746-70bf-4c00-9022-888079897c76",
            "sourceColumn": "Volume",
            "sourceLineageTag": "Volume",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "ModifiedOn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "lineageTag": "499e0be8-48ad-422e-8640-1007cf54d11e",
            "sourceColumn": "ModifiedOn",
            "sourceLineageTag": "ModifiedOn",
            "sourceProviderType": "real",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c69e8d5a-13d5-4257-9497-880afaf50193",
        "measures": [
          {
            "name": "Average Order Margin",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'S_Currency'[Currency] ),",
              "    \"GBP\", AVERAGE ( f_salesorders[Total Margin_ G B P] ),",
              "    \"EUR\", AVERAGE ( f_salesorders[Total Margin_ E U R] ),",
              "    \"USD\", AVERAGE ( f_salesorders[Total Margin_ U S D] )",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "4702e609-9f9e-400a-b5fd-83bc356fe42e"
          },
          {
            "name": "Average Order Value",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'S_Currency'[Currency] ),",
              "    \"GBP\", AVERAGE ( f_salesorders[Total Amount_ G B P] ),",
              "    \"EUR\", AVERAGE ( f_salesorders[Total Amount_ E U R] ),",
              "    \"USD\", AVERAGE ( f_salesorders[Total Amount_ U S D] )",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "cde35631-2cca-40cd-a491-fab1ef991b08"
          },
          {
            "name": "Average Order Volume",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(AVERAGE ( f_salesorders[Volume] ), FILTER(d_unit, d_unit[Unit] <> \"EACH\"))",
            "formatString": "#,0.00",
            "lineageTag": "51fdd79a-e9b2-49a0-ad25-f3adcd29133d"
          },
          {
            "name": "Forward Order Amount",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE ( [Order Value], d_shippingdate[Date] > TODAY () + 14 )",
            "formatString": "#,0.00",
            "lineageTag": "87948430-ad8c-4b37-86fd-e3aa21a793d2"
          },
          {
            "name": "No. Orders",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DISTINCTCOUNT ( f_salesorders[SalesOrderID] )",
            "formatString": "#,0",
            "lineageTag": "b9993e62-3f4c-408e-9290-9c9a6ef03500"
          },
          {
            "name": "Order Margin",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'S_Currency'[Currency], \"None\" ),",
              "    \"GBP\", SUM ( f_salesorders[Total Margin_ G B P] ),",
              "    \"EUR\", SUM ( f_salesorders[Total Margin_ E U R] ),",
              "    \"USD\", SUM ( f_salesorders[Total Margin_ U S D] )",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "4da8ee8a-9db9-408f-86e7-66ea40d04b8c"
          },
          {
            "name": "Order Volume",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE(SUM ( f_salesorders[Volume] ), FILTER(d_unit, d_unit[Unit] <> \"EACH\"))",
              ""
            ],
            "formatString": "#,0.00",
            "lineageTag": "7670f73e-52aa-4783-ad9b-26a319638fd3"
          },
          {
            "name": "Order Value",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'S_Currency'[Currency], \"None\" ),",
              "    \"GBP\", SUM ( f_salesorders[Total Amount_ G B P] ),",
              "    \"EUR\", SUM ( f_salesorders[Total Amount_ E U R] ),",
              "    \"USD\", SUM ( F_salesorders[Total Amount_ U S D] )",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "a43b04d0-5c17-44fd-b7fa-3fc350e94144"
          },
          {
            "name": "No. Customers By Country (Orders)",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE (",
              "    DISTINCTCOUNT ( f_salesorders[FK_CustomerID] ),",
              "    ALLEXCEPT ( d_postaladdress, d_postaladdress[Country] )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "319fcaab-8c6f-46e8-b8dc-5286d718517d"
          },
          {
            "name": "No. Orders By Product",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE (",
              "    DISTINCTCOUNT ( f_salesorders[SalesOrderID] ),",
              "    ALLEXCEPT ( d_product, d_product[Product] )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "0f0ed2c9-5afc-42d5-b371-360074474aa8"
          },
          {
            "name": "No. Customers By Product (Orders)",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE (",
              "    DISTINCTCOUNT ( f_salesorders[FK_CustomerID] ),",
              "    ALLEXCEPT ( d_product, d_product[Product] )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "d91fcefb-119d-4eb4-a948-3fbb00600b06"
          },
          {
            "name": "Order Quantity",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM (f_salesorders[Quantity Ordered])",
            "formatString": "#,0",
            "lineageTag": "508db6fe-dadc-498b-9dac-2d5616a59665"
          },
          {
            "name": "Forward Order Quantity",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE ( SUM ( [Quantity Ordered] ), d_shippingdate[Date] > TODAY () + 14 )",
            "formatString": "#,0",
            "lineageTag": "1ebc25f6-a320-4745-b4d7-7b2d45de90cc"
          },
          {
            "name": "Sum of Gross Weight",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM ( f_salesorders[Gross Weight] )",
            "formatString": "#,0.0",
            "lineageTag": "d1bdbca6-d869-4c26-b00a-acbb5009ed9a"
          },
          {
            "name": "Sum of Net Weight",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM ( f_salesorders[Net Weight] )",
            "formatString": "#,0.0",
            "lineageTag": "9886a13f-c900-49c1-bf35-c9f477b98809"
          },
          {
            "name": "Sum of Net Weight Kg",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM ( f_salesorders[Net Weight KG] )",
            "formatString": "#,0.0",
            "lineageTag": "261cdc66-b8ce-4e32-ac68-4b3820d3ccad"
          },
          {
            "name": "Price Per KG Unit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": "DIVIDE ( [Order Value], [Order Volume] )",
            "lineageTag": "5b17f0c3-4c1a-458c-9bab-ea13c15f15bd"
          },
          {
            "name": "Order Volume T (Today)",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE ( [Order Volume (Today)], 1000 )",
            "formatString": "#,0.00",
            "lineageTag": "9bb7cd5f-08a7-4e05-abb7-e9f66369a654"
          },
          {
            "name": "Order Volume T (MTD)",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE ( [Order Volume (MTD)], 1000 )",
            "formatString": "#,0.00",
            "lineageTag": "067dbcd8-359a-4800-b278-ffccf568e5e2"
          },
          {
            "name": "Volume T (SO)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": "CALCULATE(DIVIDE(SUM(f_salesorders[Volume]), 1000), FILTER(d_unit, d_unit[Unit] <> \"EACH\"))",
            "lineageTag": "47f655ad-9cde-49e3-8441-ef11411af1fa"
          },
          {
            "name": "Sales Quantity Backorder",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": "CALCULATE(SUM(f_salesorders[Quantity Ordered]), d_salesorderstatus[Sales Order Status] = \"Backorder\")",
            "lineageTag": "03d2e23f-ff17-48e3-a876-10eefef06e27"
          },
          {
            "name": "SO+Inv Volume (MTD)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": "f_salesorders[Order Volume (MTD)] + f_salesinvoices[Sales Volume (MTD)]",
            "lineageTag": "f135d86d-f4ac-4d22-9c49-0f5a147b450d"
          },
          {
            "name": "SO+Inv Value (MTD)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": "f_salesorders[Order Value (MTD)] + f_salesinvoices[Sales Invoiced (MTD)]",
            "lineageTag": "8f53509f-cb90-433d-aedb-3406f9d0e423"
          },
          {
            "name": "SO+Inv Margin (MTD)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": "f_salesorders[Order Margin (MTD)] + f_salesinvoices[Sales Margin (MTD)]",
            "lineageTag": "fce31299-3900-4081-a2cb-609a0823c972"
          },
          {
            "name": "O/S Sales Orders Qty",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": "CALCULATE(SUM(f_salesorders[Quantity Ordered]), d_salesorderstatus[Sales Order Status] <> \"Invoiced\", d_salesorderstatus[Sales Order Status] <> \"Canceled\")",
            "lineageTag": "3e0766c8-374d-4ece-a900-dbaa82fd2315"
          },
          {
            "name": "O/S Sales Orders Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": "CALCULATE(f_salesorders[Order Value], d_salesorderstatus[Sales Order Status] <> \"Invoiced\", d_salesorderstatus[Sales Order Status] <> \"Canceled\")",
            "lineageTag": "190f0a4d-3258-4fab-826c-da7875acbd0c"
          },
          {
            "name": "O/S Sales Orders Margin",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": "CALCULATE(f_salesorders[Order Margin], d_salesorderstatus[Sales Order Status] <> \"Invoiced\", d_salesorderstatus[Sales Order Status] <> \"Canceled\")",
            "lineageTag": "306aff18-ca71-4788-86db-7ca050c75f0b"
          },
          {
            "name": "O/S Sales Orders Volume",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": "CALCULATE(f_salesorders[Order Volume], d_salesorderstatus[Sales Order Status] <> \"Invoiced\", d_salesorderstatus[Sales Order Status] <> \"Canceled\")",
            "lineageTag": "bd22f509-474b-4ef9-9e30-5a80d0e3edf2"
          },
          {
            "name": "O/S % Budget Value",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE([O/S Sales Orders Value],f_budgets[Sales Budget])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "5ce1611e-de6d-4eb8-87da-28cd15652151"
          },
          {
            "name": "O/S % Budget Margin",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE([O/S Sales Orders Margin],f_budgets[Budget Margin])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "4329ca97-333b-4923-9b00-58831af15bab"
          },
          {
            "name": "O/S % Budget Volume",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "DIVIDE([O/S Sales Orders Volume],f_budgets[Budget Volume])",
            "formatString": "0%;-0%;0%",
            "lineageTag": "bafbccca-55c0-4708-b9b9-7817dbec04ca"
          },
          {
            "name": "Order Margin (Today)",
            "description": "This measure is a derivative of Order Margin.",
            "displayFolder": "Order Margin",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "RETURN",
              "    CALCULATE (",
              "        [Order Margin],",
              "        'd_date'[Date] = CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "94c28184-45f7-4fa0-9a03-015ef950df33"
          },
          {
            "name": "Order Margin (Yesterday)",
            "description": "This measure is a derivative of Order Margin.",
            "displayFolder": "Order Margin",
            "expression": [
              "VAR YesterdayDate =",
              "    TODAY () - 1",
              "RETURN",
              "    CALCULATE (",
              "        [Order Margin],",
              "        'd_date'[Date] = YesterdayDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "efcd326c-fa73-4b20-bc2e-dc9629aa2765"
          },
          {
            "name": "Order Margin (MTD)",
            "description": "This measure is a derivative of Order Margin.",
            "displayFolder": "Order Margin",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR StartdateMonth =",
              "    DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 )",
              "RETURN",
              "    CALCULATE (",
              "        [Order Margin],",
              "        'd_date'[Date] >= StartdateMonth",
              "            && 'd_date'[Date] <= CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "20cd2a6f-554e-4a19-80ac-a0c00248d32d"
          },
          {
            "name": "Order Margin (PMTD)",
            "description": "This measure is a derivative of Order Margin.",
            "displayFolder": "Order Margin",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR DaysInMonthSoFar =",
              "    DAY ( CurrentDate )",
              "VAR StartOfPriorMonth =",
              "    EDATE ( DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 ), -1 )",
              "VAR EndOfPriorMonth = StartOfPriorMonth + DaysInMonthSoFar - 1",
              "RETURN",
              "    CALCULATE (",
              "        [Order Margin],",
              "        'd_date'[Date] >= StartOfPriorMonth",
              "            && 'd_date'[Date] <= EndOfPriorMonth,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "b1b73972-56e2-4260-9478-d8f723825774"
          },
          {
            "name": "Order Margin (YTD)",
            "description": "This measure is a derivative of Order Margin.",
            "displayFolder": "Order Margin",
            "expression": "[Order Margin]",
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "fe016c11-9021-4eb1-990c-7f5a5a8ed53d"
          },
          {
            "name": "Order Margin (PYTD)",
            "description": "This measure is a derivative of Order Margin.",
            "displayFolder": "Order Margin",
            "expression": [
              "CALCULATE (",
              "    [Order Margin],",
              "    REMOVEFILTERS ( d_date ),",
              "    FILTER (",
              "        DATEADD ( d_date[Date], -1, YEAR ),",
              "        d_date[Date]",
              "            <= DATE ( YEAR ( TODAY () - 1 ), MONTH ( TODAY () ), DAY ( TODAY () ) )",
              "    )",
              ")"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "5b72b03d-9bda-4626-9b02-e9604e9b6392"
          },
          {
            "name": "Order Volume (Today)",
            "description": "This measure is a derivative of Order Volume.",
            "displayFolder": "Order Volume",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "RETURN",
              "    CALCULATE (",
              "        [Order Volume],",
              "        'd_date'[Date] = CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "f5909d30-742a-41fb-94be-93ee508e9419"
          },
          {
            "name": "Order Volume (MTD)",
            "description": "This measure is a derivative of Order Volume.",
            "displayFolder": "Order Volume",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR StartdateMonth =",
              "    DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 )",
              "RETURN",
              "    CALCULATE (",
              "        [Order Volume],",
              "        'd_date'[Date] >= StartdateMonth",
              "            && 'd_date'[Date] <= CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "9e8a9a15-b193-4697-bcec-b0c96e4579eb"
          },
          {
            "name": "Order Volume (YTD)",
            "description": "This measure is a derivative of Order Volume.",
            "displayFolder": "Order Volume",
            "expression": "[Order Volume]",
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "28f05f5a-96d4-41a9-9a9c-a1b04baa0811"
          },
          {
            "name": "Order Volume (PYTD)",
            "description": "This measure is a derivative of Order Volume.",
            "displayFolder": "Order Volume",
            "expression": [
              "CALCULATE (",
              "    [Order Volume],",
              "    REMOVEFILTERS ( d_date ),",
              "    FILTER (",
              "        DATEADD ( d_date[Date], -1, YEAR ),",
              "        d_date[Date]",
              "            <= DATE ( YEAR ( TODAY () - 1 ), MONTH ( TODAY () ), DAY ( TODAY () ) )",
              "    )",
              ")"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "c268efe1-6b5f-4e0e-b5a1-0530c0c557e9"
          },
          {
            "name": "No. Orders (Today)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "This measure is a derivative of No. Orders.",
            "displayFolder": "No. Orders",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "RETURN",
              "    CALCULATE (",
              "        [No. Orders],",
              "        'd_date'[Date] = CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "b65cd5f9-cad1-44e3-ae72-b38300203116"
          },
          {
            "name": "No. Orders (MTD)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "This measure is a derivative of No. Orders.",
            "displayFolder": "No. Orders",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR StartdateMonth =",
              "    DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 )",
              "RETURN",
              "    CALCULATE (",
              "        [No. Orders],",
              "        'd_date'[Date] >= StartdateMonth",
              "            && 'd_date'[Date] <= CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "08ebed06-3872-4a89-bcfb-4ffde3916e64"
          },
          {
            "name": "Forward Order Amount (Next Month)",
            "description": "This measure is a derivative of Forward Order Amount.",
            "displayFolder": "Forward Order Amount",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR StartOfNextMonth =",
              "    EOMONTH ( CurrentDate, 0 ) + 1",
              "VAR EndOfNextMonth =",
              "    EOMONTH ( CurrentDate, 1 )",
              "RETURN",
              "    CALCULATE (",
              "        [Forward Order Amount],",
              "        'd_date'[Date] >= StartOfNextMonth",
              "            && 'd_date'[Date] <= EndOfNextMonth,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "e5722f59-a9c0-40a7-b0db-e583074d2c9f"
          },
          {
            "name": "Order Margin (Today vs Yesterday)",
            "displayFolder": "Order Margin",
            "expression": [
              "IF (",
              "    ISBLANK ( [Order Margin (Yesterday)] ),",
              "    BLANK (),",
              "    IF (",
              "        ISBLANK ( [Order Margin (Today)] ),",
              "        BLANK (),",
              "        DIVIDE (",
              "            [Order Margin (Today)] - [Order Margin (Yesterday)],",
              "            [Order Margin (Yesterday)],",
              "            0",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "6fa0dd75-f6bb-4b03-a01c-2cfd3d6cb078"
          },
          {
            "name": "Order Margin (Today vs Yesterday) ARROW",
            "description": "This measure is a derivative of Order Margin.",
            "displayFolder": "Order Margin",
            "expression": [
              "IF (",
              "    [Order Margin (Today vs Yesterday)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF (",
              "        [Order Margin (Today vs Yesterday)] = 0,",
              "        UNICHAR ( 45 ),",
              "        IF (",
              "            [Order Margin (Today vs Yesterday)] = BLANK (),",
              "            UNICHAR ( 45 ),",
              "            UNICHAR ( 8595 )",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "122f722f-0de3-42bc-85a4-09e867a36116"
          },
          {
            "name": "Order Margin (MTD vs PMTD)",
            "displayFolder": "Order Margin",
            "expression": [
              "IF (",
              "    ISBLANK ( [Order Margin (PMTD)] ),",
              "    BLANK (),",
              "    IF (",
              "        ISBLANK ( [Order Margin (MTD)] ),",
              "        BLANK (),",
              "        DIVIDE (",
              "            [Order Margin (MTD)] - [Order Margin (PMTD)],",
              "            [Order Margin (PMTD)],",
              "            0",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "5fee4819-96c3-437c-9020-47c45f440e47"
          },
          {
            "name": "Order Margin (MTD vs PMTD) ARROW",
            "description": "This measure is a derivative of Order Margin.",
            "displayFolder": "Order Margin",
            "expression": [
              "IF (",
              "    [Order Margin (MTD vs PMTD)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF (",
              "        [Order Margin (MTD vs PMTD)] = 0,",
              "        UNICHAR ( 45 ),",
              "        IF ( [Order Margin (MTD vs PMTD)] = BLANK (), UNICHAR ( 45 ), UNICHAR ( 8595 ) )",
              "    )",
              ")"
            ],
            "lineageTag": "f442ee80-0605-403c-87fb-503b1f1b91c8"
          },
          {
            "name": "Order Margin (YTD vs PYTD)",
            "displayFolder": "Order Margin",
            "expression": [
              "IF (",
              "    ISBLANK ( [Order Margin (PYTD)] ),",
              "    BLANK (),",
              "    IF (",
              "        ISBLANK ( [Order Margin (MTD)] ),",
              "        BLANK (),",
              "        DIVIDE (",
              "            [Order Margin (YTD)] - [Order Margin (PYTD)],",
              "            [Order Margin (PYTD)],",
              "            0",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "b28fc24c-040c-447e-ab7f-c40260796e2f"
          },
          {
            "name": "Order Margin (YTD vs PYTD) ARROW",
            "description": "This measure is a derivative of Order Margin.",
            "displayFolder": "Order Margin",
            "expression": [
              "IF (",
              "    [Order Margin (YTD vs PYTD)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF (",
              "        [Order Margin (YTD vs PYTD)] = 0,",
              "        UNICHAR ( 45 ),",
              "        IF ( [Order Margin (YTD vs PYTD)] = BLANK (), UNICHAR ( 45 ), UNICHAR ( 8595 ) )",
              "    )",
              ")"
            ],
            "lineageTag": "baf1fcd2-3eb0-44d5-88ca-2d04d53878f9"
          },
          {
            "name": "Order Value (Today)",
            "description": "This measure is a derivative of Order Value.",
            "displayFolder": "Order Value",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "RETURN",
              "    CALCULATE (",
              "        [Order Value],",
              "        'd_date'[Date] = CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "d2652fdd-dbbc-4569-9607-b3e675ab6bf0"
          },
          {
            "name": "Order Value (Yesterday)",
            "description": "This measure is a derivative of Order Value.",
            "displayFolder": "Order Value",
            "expression": [
              "VAR YesterdayDate =",
              "    TODAY () - 1",
              "RETURN",
              "    CALCULATE (",
              "        [Order Value],",
              "        'd_date'[Date] = YesterdayDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "1a0f78e0-5f57-4d7d-81ad-06b384a5e27e"
          },
          {
            "name": "Order Value (MTD)",
            "description": "This measure is a derivative of Order Value.",
            "displayFolder": "Order Value",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR StartdateMonth =",
              "    DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 )",
              "RETURN",
              "    CALCULATE (",
              "        [Order Value],",
              "        'd_date'[Date] >= StartdateMonth",
              "            && 'd_date'[Date] <= CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "8bc52806-7ab4-400b-b78b-b36ffcd4906b"
          },
          {
            "name": "Order Value (PMTD)",
            "description": "This measure is a derivative of Order Value.",
            "displayFolder": "Order Value",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR DaysInMonthSoFar =",
              "    DAY ( CurrentDate )",
              "VAR StartOfPriorMonth =",
              "    EDATE ( DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 ), -1 )",
              "VAR EndOfPriorMonth = StartOfPriorMonth + DaysInMonthSoFar - 1",
              "RETURN",
              "    CALCULATE (",
              "        [Order Value],",
              "        'd_date'[Date] >= StartOfPriorMonth",
              "            && 'd_date'[Date] <= EndOfPriorMonth,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "26c2f468-521f-435c-9eb0-8a7569fb632e"
          },
          {
            "name": "Order Value (YTD)",
            "description": "This measure is a derivative of Order Value.",
            "displayFolder": "Order Value",
            "expression": "[Order Value]",
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "7f9e8526-9ef0-434a-bc86-5d79a28de592"
          },
          {
            "name": "Order Value (PYTD)",
            "description": "This measure is a derivative of Order Value.",
            "displayFolder": "Order Value",
            "expression": [
              "CALCULATE (",
              "    [Order Value],",
              "    REMOVEFILTERS ( d_date ),",
              "    FILTER (",
              "        DATEADD ( d_date[Date], -1, YEAR ),",
              "        d_date[Date]",
              "            <= DATE ( YEAR ( TODAY () - 1 ), MONTH ( TODAY () ), DAY ( TODAY () ) )",
              "    )",
              ")"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "29d9f697-7ad9-49dd-8c15-ff3f8c801194"
          },
          {
            "name": "Order Value (Today vs Yesterday)",
            "displayFolder": "Order Value",
            "expression": [
              "IF (",
              "    ISBLANK ( [Order Value (Yesterday)] ),",
              "    BLANK (),",
              "    IF (",
              "        ISBLANK ( [Order Value (Today)] ),",
              "        BLANK (),",
              "        DIVIDE (",
              "            [Order Value (Today)] - [Order Value (Yesterday)],",
              "            [Order Value (Yesterday)],",
              "            0",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "78feb05a-9549-468e-b254-46d34089565d"
          },
          {
            "name": "Order Value (Today vs Yesterday) ARROW",
            "description": "This measure is a derivative of Order Value.",
            "displayFolder": "Order Value",
            "expression": [
              "IF (",
              "    [Order Value (Today vs Yesterday)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF (",
              "        [Order Value (Today vs Yesterday)] = 0,",
              "        UNICHAR ( 45 ),",
              "        IF (",
              "            [Order Value (Today vs Yesterday)] = BLANK (),",
              "            UNICHAR ( 45 ),",
              "            UNICHAR ( 8595 )",
              "        )",
              "    )",
              ")"
            ],
            "lineageTag": "8bb94a8e-baf4-4d63-8965-4f28b041ed83"
          },
          {
            "name": "Order Value (MTD vs PMTD)",
            "displayFolder": "Order Value",
            "expression": [
              "IF (",
              "    ISBLANK ( [Order Value (PMTD)] ),",
              "    BLANK (),",
              "    IF (",
              "        ISBLANK ( [Order Value (MTD)] ),",
              "        BLANK (),",
              "        DIVIDE ( [Order Value (MTD)] - [Order Value (PMTD)], [Order Value (PMTD)], 0 )",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "165cdc02-09f1-4a59-97dd-ba020daca6f1"
          },
          {
            "name": "Order Value (MTD vs PMTD) ARROW",
            "description": "This measure is a derivative of Order Value.",
            "displayFolder": "Order Value",
            "expression": [
              "IF (",
              "    [Order Value (MTD vs PMTD)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF (",
              "        [Order Value (MTD vs PMTD)] = 0,",
              "        UNICHAR ( 45 ),",
              "        IF ( [Order Value (MTD vs PMTD)] = BLANK (), UNICHAR ( 45 ), UNICHAR ( 8595 ) )",
              "    )",
              ")"
            ],
            "lineageTag": "761ae0be-aa81-442d-9cf3-6062bf1ed210"
          },
          {
            "name": "Order Value (YTD vs PYTD)",
            "displayFolder": "Order Value",
            "expression": [
              "IF (",
              "    ISBLANK ( [Order Value (PYTD)] ),",
              "    BLANK (),",
              "    IF (",
              "        ISBLANK ( [Order Value (MTD)] ),",
              "        BLANK (),",
              "        DIVIDE ( [Order Value (YTD)] - [Order Value (PYTD)], [Order Value (PYTD)], 0 )",
              "    )",
              ")"
            ],
            "formatString": "#0.0%#",
            "lineageTag": "92334164-4661-41b4-ae88-b367af8718fb"
          },
          {
            "name": "Order Value (YTD vs PYTD) ARROW",
            "description": "This measure is a derivative of Order Value.",
            "displayFolder": "Order Value",
            "expression": [
              "IF (",
              "    [Order Value (YTD vs PYTD)] > 0,",
              "    UNICHAR ( 8593 ),",
              "    IF (",
              "        [Order Value (YTD vs PYTD)] = 0,",
              "        UNICHAR ( 45 ),",
              "        IF ( [Order Value (YTD vs PYTD)] = BLANK (), UNICHAR ( 45 ), UNICHAR ( 8595 ) )",
              "    )",
              ")"
            ],
            "lineageTag": "d4e739e6-936b-47e8-9d28-fe51134a0d8e"
          }
        ],
        "partitions": [
          {
            "name": "curated_f_salesorders",
            "mode": "directLake",
            "source": {
              "entityName": "curated_f_salesorders",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_f_salesorders]"
      },
      {
        "name": "d_documentstatus",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DocumentStatusID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7dd57a0-ccc6-4543-a5ac-d7a48ace54a9",
            "sourceColumn": "DocumentStatusID",
            "sourceLineageTag": "DocumentStatusID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Document Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f784994-e544-4759-accc-1c7f448af1d7",
            "sourceColumn": "DocumentStatus",
            "sourceLineageTag": "DocumentStatus",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "DocumentStatusNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "lineageTag": "3a8a0a12-8ef5-4ee3-a722-3a8a136dfc09",
            "sourceColumn": "DocumentStatusNaturalID",
            "sourceLineageTag": "DocumentStatusNaturalID",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "7b1f6666-0672-4b8d-bff2-33044aa2bc69",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c70bd712-46b2-4adc-a7a6-2a10e333f4d6",
        "partitions": [
          {
            "name": "curated_d_documentstatus",
            "mode": "directLake",
            "source": {
              "entityName": "curated_d_documentstatus",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_documentstatus]"
      },
      {
        "name": "d_product",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47922607-0db1-4369-8bd3-9f194c5d1698",
            "sourceColumn": "ProductID",
            "sourceLineageTag": "ProductID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d3df1af-2472-4dae-bcc8-ab6a1472d6e4",
            "sourceColumn": "Product",
            "sourceLineageTag": "Product",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Product Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96619676-58b0-4d6d-a7f8-6a03318d3ed1",
            "sourceColumn": "ProductType",
            "sourceLineageTag": "ProductType",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Net Weight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "23c02a90-f990-4c45-b092-f455da4b5394",
            "sourceColumn": "NetWeight",
            "sourceLineageTag": "NetWeight",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Tare Weight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2300c78a-851f-452d-89e9-c3c5cd9fbebe",
            "sourceColumn": "TareWeight",
            "sourceLineageTag": "TareWeight",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Product Per Pallet",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "59def290-551e-4df8-9738-3c1def52a414",
            "sourceColumn": "ProductPerPallet",
            "sourceLineageTag": "ProductPerPallet",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "ItemID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d58552b9-79d4-40af-a90c-ecdcc9b0ebf4",
            "sourceColumn": "ItemID",
            "sourceLineageTag": "ItemID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessUnitNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "lineageTag": "4c18bb73-23d8-4949-af38-d4326dff2e98",
            "sourceColumn": "BusinessUnitNaturalID",
            "sourceLineageTag": "BusinessUnitNaturalID",
            "summarizeBy": "count"
          },
          {
            "name": "CustomerNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eef72efd-62e2-446b-bf02-c96adbbabd36",
            "sourceColumn": "CustomerNaturalID",
            "sourceLineageTag": "CustomerNaturalID",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "7697187c-0abd-4d16-b3b4-2c748f085dec",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          },
          {
            "name": "IsHistory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "50cb120f-2857-4d15-ba0a-f214ad4535cd",
            "sourceColumn": "IsHistory",
            "sourceLineageTag": "IsHistory",
            "summarizeBy": "none"
          },
          {
            "name": "ProductBigInt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "lineageTag": "0176e566-8605-4a36-b283-03b82824562c",
            "sourceColumn": "ProductBigInt",
            "sourceLineageTag": "ProductBigInt",
            "summarizeBy": "sum"
          },
          {
            "name": "ProductNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5dfed69f-2259-4592-b482-46ac0a22e460",
            "sourceColumn": "ProductNaturalID",
            "sourceLineageTag": "ProductNaturalID",
            "summarizeBy": "none"
          },
          {
            "name": "SupplierNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca66ea2a-70c1-444d-87fc-fda2a9209a7c",
            "sourceColumn": "SupplierNaturalID",
            "sourceLineageTag": "SupplierNaturalID",
            "summarizeBy": "none"
          },
          {
            "name": "UnitNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7779c0ce-51ca-4c7e-a0ec-dcbe77650465",
            "sourceColumn": "UnitNaturalID",
            "sourceLineageTag": "UnitNaturalID",
            "summarizeBy": "none"
          },
          {
            "name": "ConsignmentFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "4fc33381-6e5c-429f-83a9-349c188e22cc",
            "sourceColumn": "ConsignmentFlag",
            "sourceLineageTag": "ConsignmentFlag",
            "summarizeBy": "none"
          },
          {
            "name": "ProductOwner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a906e0df-e2b5-4955-8653-2bae23bc7efa",
            "sourceColumn": "ProductOwner",
            "sourceLineageTag": "ProductOwner",
            "summarizeBy": "none"
          },
          {
            "name": "PackType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c9311b4c-7f62-4eb1-982a-777a2df53c8f",
            "sourceColumn": "PackType",
            "sourceLineageTag": "PackType",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b4b10719-4ace-4786-8179-aaca1d58b6cf",
        "partitions": [
          {
            "name": "curated_d_product",
            "mode": "directLake",
            "source": {
              "entityName": "curated_d_product",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_product]"
      },
      {
        "name": "f_comahsnapshot",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "FK_DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3f4499b9-bca9-4df6-8dfb-0a90f0169c90",
            "sourceColumn": "FK_DateID",
            "sourceLineageTag": "FK_DateID",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "FK_OperationalSiteID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5fd97804-71f6-448d-a795-7156ce00ae65",
            "sourceColumn": "FK_OperationalSiteID",
            "sourceLineageTag": "FK_OperationalSiteID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_LegalEntityID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "223a964e-70b1-40f8-99d2-996df4377d98",
            "sourceColumn": "FK_LegalEntityID",
            "sourceLineageTag": "FK_LegalEntityID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_ComahCategoryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "51f34d61-3369-474b-92a4-e275ec21f388",
            "sourceColumn": "FK_ComahCategoryID",
            "sourceLineageTag": "FK_ComahCategoryID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_ComahSubCategoryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "ee1cf178-2dbf-4146-a948-70fd01d29f86",
            "sourceColumn": "FK_ComahSubCategoryID",
            "sourceLineageTag": "FK_ComahSubCategoryID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_ComahSubstanceID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "68aed2b4-4af8-4a54-9154-b4e9cd81e8f1",
            "sourceColumn": "FK_ComahSubstanceID",
            "sourceLineageTag": "FK_ComahSubstanceID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "10394de2-c06d-41e3-b854-ee7e93dda59e",
            "sourceColumn": "FK_ProductID",
            "sourceLineageTag": "FK_ProductID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Total Weight In Tonne",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "b395d813-ec78-4451-9a0b-4e4b50b9a0f3",
            "sourceColumn": "TotalWeightinTonne",
            "sourceLineageTag": "TotalWeightinTonne",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "ComahNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4c72bae-bda8-43bf-89a0-1e4a9840246c",
            "sourceColumn": "ComahNaturalID",
            "sourceLineageTag": "ComahNaturalID",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "7b994dc3-41df-416e-8169-15fcba965c0a",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0b9df470-07c8-4c99-b3a8-d731c329a5e0",
        "measures": [
          {
            "name": "Lower Tier Score",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": [
              "DIVIDE (",
              "    SUM ( f_comahsnapshot[Total Weight In Tonne] ),",
              "    SUM ( f_comahlimits[Lower Limit] )",
              ")"
            ],
            "lineageTag": "9e680e2b-0db6-4cb1-9854-ab092f2c8c96"
          },
          {
            "name": "Upper Tier Score",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": [
              "DIVIDE (",
              "    SUM ( f_comahsnapshot[Total Weight In Tonne] ),",
              "    SUM ( f_comahlimits[Upper Limit] )",
              ")"
            ],
            "lineageTag": "3104901b-ca92-492b-b6a2-67573e19a191"
          },
          {
            "name": "Lower Tier vs Limit",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "( 1 - [Lower Tier Score] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0da1363d-a141-4249-ab5a-f662e338f4d7"
          },
          {
            "name": "Upper Tier vs Limit",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "( 1 - [Upper Tier Score] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "15a3ecc0-b9e3-4ae9-b72c-a5a13ae24950"
          },
          {
            "name": "Lower Score vs Limit ARROW",
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": [
              "IF (",
              "    [Lower Tier vs Limit] > 0,",
              "    UNICHAR ( 8595 ),",
              "    IF ( [Lower Tier vs Limit] < 0, UNICHAR ( 8593 ), UNICHAR ( 45 ) )",
              ")"
            ],
            "lineageTag": "a4802a93-007a-4d21-a3f2-89f31a6b2f79"
          },
          {
            "name": "Upper Score vs Limit ARROW",
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "expression": [
              "IF (",
              "    [Upper Tier vs Limit] > 0,",
              "    UNICHAR ( 8595 ),",
              "    IF ( [Upper Tier vs Limit] < 0, UNICHAR ( 8593 ), UNICHAR ( 45 ) )",
              ")"
            ],
            "lineageTag": "8c392764-d630-4ac1-aa66-770e819a4e01"
          }
        ],
        "partitions": [
          {
            "name": "curated_f_comahsnapshot",
            "mode": "directLake",
            "source": {
              "entityName": "curated_f_comahsnapshot",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_f_comahsnapshot]"
      },
      {
        "name": "d_comahsubstance",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ComahSubstanceID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b0659be4-8a5b-4801-841e-708b480b76f3",
            "sourceColumn": "ComahSubstanceID",
            "sourceLineageTag": "ComahSubstanceID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Comah Substance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5fea364a-3730-45b8-ab31-cf5d00fbe566",
            "sourceColumn": "ComahSubstance",
            "sourceLineageTag": "ComahSubstance",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "11a7bbe8-273e-4972-8e79-f412f77b106f",
        "partitions": [
          {
            "name": "curated_d_comahsubstance",
            "mode": "directLake",
            "source": {
              "entityName": "curated_d_comahsubstance",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_comahsubstance]"
      },
      {
        "name": "d_postaladdress",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PostalAddressID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44566edc-6478-4e1b-ab77-48f1b53738a4",
            "sourceColumn": "PostalAddressID",
            "sourceLineageTag": "PostalAddressID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "edd9e4dc-ddd9-43e1-bd03-396e6e9bf139",
            "sourceColumn": "Address",
            "sourceLineageTag": "Address",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89dd4127-bd72-47bf-a4d5-f9d042a4040e",
            "sourceColumn": "City",
            "sourceLineageTag": "City",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1295564c-f209-4438-abf3-8504ddb71da8",
            "sourceColumn": "Country",
            "sourceLineageTag": "Country",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "e657a77f-f4dc-4f99-ad7d-e93579c9a4a5",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          },
          {
            "name": "IsHistory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "d7327840-afaa-4af7-b610-b3062a2bf673",
            "sourceColumn": "IsHistory",
            "sourceLineageTag": "IsHistory",
            "summarizeBy": "none"
          },
          {
            "name": "PostalAddressNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "540a4307-cf57-4150-b6f1-2e967d81f0b5",
            "sourceColumn": "PostalAddressNaturalID",
            "sourceLineageTag": "PostalAddressNaturalID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a2584c14-f09c-4900-87f9-7a1d8a87dc76",
        "partitions": [
          {
            "name": "curated_d_postaladdress",
            "mode": "directLake",
            "source": {
              "entityName": "curated_d_postaladdress",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_postaladdress]"
      },
      {
        "name": "S_Currency",
        "columns": [
          {
            "name": "Currency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "150d6c5c-01c3-4cfe-adf0-b3830178d93a",
            "sourceColumn": "[Currency]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "description": "Table for storing currency values",
        "lineageTag": "94d2d81a-dca7-414e-bed8-3ee9ce90d54a",
        "measures": [
          {
            "name": "Selected Currency",
            "expression": "SELECTEDVALUE ( 'S_Currency'[Currency], \"Transactional\" )",
            "lineageTag": "30b0fc24-c901-4d53-9eaa-37342eac58cf"
          },
          {
            "name": "Currency Format String",
            "expression": [
              "VAR baseFormatSTRINGing = \"#,0.00\"",
              "VAR formatstring =",
              "    SELECTEDVALUE ( D_Currency[Currency Symbol], \"\" ) & baseFormatSTRINGing",
              "RETURN",
              "    formatstring"
            ],
            "lineageTag": "5e222d56-97aa-432f-aa1c-5810fa2b9cdc"
          }
        ],
        "partitions": [
          {
            "name": "S_Currency",
            "mode": "import",
            "source": {
              "expression": "DATATABLE ( \"Currency\", STRING, { { \"GBP\" }, { \"EUR\" }, { \"USD\" } } )",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "FP_All",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ac441b1db2774cc3943153c6c847630a"
          }
        ],
        "columns": [
          {
            "name": "FP_All Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "e017a2a5-087c-42fc-9206-a73851d45c4a",
            "sortByColumn": "FP_All Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "FP_All Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "d687c7ca-a007-4408-b015-1a7e7d1235cc",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "FP_All",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "1b9aa4eb-d474-41a9-96b6-389f6d5a13f8",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "FP_All Fields"
                }
              ]
            },
            "sortByColumn": "FP_All Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Metric",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(TRUE(),",
              "CONTAINSSTRING(FP_All[FP_All],\"Sales Invoiced\"), \"Sales Invoiced\",",
              "CONTAINSSTRING(FP_All[FP_All],\"Sales Margin\"), \"Invoiced Margin\",",
              "CONTAINSSTRING(FP_All[FP_All],\"Sales Volume\"), \"Invoiced Volume\",",
              "CONTAINSSTRING(FP_All[FP_All],\"Order Value\"), \"Order Value\",",
              "CONTAINSSTRING(FP_All[FP_All],\"Order Margin\"), \"Order Margin\",",
              "CONTAINSSTRING(FP_All[FP_All],\"Order Volume\"), \"Order Volume\",",
              "CONTAINSSTRING(FP_All[FP_All],\"Stock Value\"), \"Stock Value\",",
              "CONTAINSSTRING(FP_All[FP_All],\"Stock Volume\"), \"Stock Volume\",",
              "BLANK())"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "03ff3f00-9ac5-4b0f-86f6-b222f3137665",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Table",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "SWITCH(TRUE(),",
              "CONTAINSSTRING(FP_All[FP_All],\"Sales Invoiced\"), \"Sales Invoices\",",
              "CONTAINSSTRING(FP_All[FP_All],\"Sales Margin\"), \"Sales Invoices\",",
              "CONTAINSSTRING(FP_All[FP_All],\"Sales Volume\"), \"Sales Invoices\",",
              "CONTAINSSTRING(FP_All[FP_All],\"Order Value\"), \"Sales Orders\",",
              "CONTAINSSTRING(FP_All[FP_All],\"Order Margin\"), \"Sales Orders\",",
              "CONTAINSSTRING(FP_All[FP_All],\"Order Volume\"), \"Sales Orders\",",
              "CONTAINSSTRING(FP_All[FP_All],\"Stock Value\"), \"Stock\",",
              "CONTAINSSTRING(FP_All[FP_All],\"Stock Volume\"), \"Stock\",",
              "BLANK())"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "1089f07b-52f0-46af-b544-02706c4a66fb",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "7f31638a-23cf-493a-a50a-307041842a47",
        "partitions": [
          {
            "name": "FP_All",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Sales Invoiced (YTD)\", NAMEOF('F_SalesInvoices'[Sales Invoiced (YTD)]), 0),",
                "    (\"Sales Invoiced (PYTD)\", NAMEOF('f_salesinvoices'[Sales Invoiced (PYTD)]), 1),",
                "    (\"Sales Margin (YTD)\", NAMEOF('F_SalesInvoices'[Sales Margin (YTD)]), 2),",
                "    (\"Sales Margin (PYTD)\", NAMEOF('f_salesinvoices'[Sales Margin (PYTD)]), 3),",
                "    (\"Sales Volume (YTD)\", NAMEOF('F_SalesInvoices'[Sales Volume (YTD)]), 4),",
                "    (\"Sales Volume (PYTD)\", NAMEOF('f_salesinvoices'[Sales Volume (PYTD)]), 5),",
                "    (\"Order Value (YTD)\", NAMEOF('F_SalesOrders'[Order Value (YTD)]), 6),",
                "    (\"Order Value (PYTD)\", NAMEOF('F_SalesOrders'[Order Value (PYTD)]), 7),",
                "    (\"Order Margin (YTD)\", NAMEOF('F_SalesOrders'[Order Margin (YTD)]), 8),",
                "    (\"Order Margin (PYTD)\", NAMEOF('F_SalesOrders'[Order Margin (PYTD)]), 9),",
                "    (\"Order Volume (YTD)\", NAMEOF('F_SalesOrders'[Order Volume (YTD)]), 10),",
                "    (\"Order Volume (PYTD)\", NAMEOF('F_SalesOrders'[Order Volume (PYTD)]), 11),",
                "    (\"Stock Value (YTD)\", NAMEOF('F_InventorySnapshot'[Stock Value (YTD)]), 12),",
                "    (\"Stock Value (PYTD)\", NAMEOF('F_InventorySnapshot'[Stock Value (PYTD)]), 13),",
                "    (\"Stock Volume (YTD)\", NAMEOF('F_InventorySnapshot'[Stock Volume (YTD)]), 14),",
                "    (\"Stock Volume (PYTD)\", NAMEOF('F_InventorySnapshot'[Stock Volume (PYTD)]), 15)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "f_budgets",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "f85751e8-5f80-46a2-8a81-01f98e802bf1",
            "sourceColumn": "Cost",
            "sourceLineageTag": "Cost",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "FK_DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "17e78d56-056c-4d8a-9390-2c5abe5690bf",
            "sourceColumn": "FK_DateID",
            "sourceLineageTag": "FK_DateID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_BusinessUnitID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a9d6f6bc-db66-4585-a713-225eb9239978",
            "sourceColumn": "FK_BusinessUnitID",
            "sourceLineageTag": "FK_BusinessUnitID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_LegalEntityID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4dea324b-dc25-40c3-9741-d7f8a453fb2e",
            "sourceColumn": "FK_LegalEntityID",
            "sourceLineageTag": "FK_LegalEntityID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_SalesAreaID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "1b6c5913-9a5e-4ff6-a432-3478737ce3f4",
            "sourceColumn": "FK_SalesAreaID",
            "sourceLineageTag": "FK_SalesAreaID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Gross Margin Percentage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1b115ace-faa9-4cbc-ae03-90959015fb65",
            "sourceColumn": "GrossMarginPercentage",
            "sourceLineageTag": "GrossMarginPercentage",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross Margin_ E U R",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "279705be-efb9-42f1-b7ab-64082feb3d1a",
            "sourceColumn": "GrossMargin_EUR",
            "sourceLineageTag": "GrossMargin_EUR",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross Margin_ G B P",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "18004e15-fe30-4795-90cd-1a0eeb612ed5",
            "sourceColumn": "GrossMargin_GBP",
            "sourceLineageTag": "GrossMargin_GBP",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross Margin_ U S D",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c59c9ca6-61b6-487b-89d1-27009e8c84d9",
            "sourceColumn": "GrossMargin_USD",
            "sourceLineageTag": "GrossMargin_USD",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales_ E U R",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "38ce5817-77b7-4606-81b8-3b9b89038cc1",
            "sourceColumn": "Sales_EUR",
            "sourceLineageTag": "Sales_EUR",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales_ G B P",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e241ce8e-3bbd-4727-a6ff-31c4fb13fd92",
            "sourceColumn": "Sales_GBP",
            "sourceLineageTag": "Sales_GBP",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales_ U S D",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b7a4caee-2313-4a6e-84cb-d86f05fbb0f2",
            "sourceColumn": "Sales_USD",
            "sourceLineageTag": "Sales_USD",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Volume",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "faeab16a-449d-4e1c-99f4-d360fc24d934",
            "sourceColumn": "Volume",
            "sourceLineageTag": "Volume",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "BudgetNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d130399-8402-4ac2-b2c7-7f64f1d238b2",
            "sourceColumn": "BudgetNaturalID",
            "sourceLineageTag": "BudgetNaturalID",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "efe7d5a5-9a47-49d3-8998-07238468f686",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "aac3b5a9-4593-48ae-b965-3b068a080f59",
        "measures": [
          {
            "name": "Budget Margin",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'S_Currency'[Currency], \"None\" ),",
              "    \"GBP\", SUM ( 'f_budgets'[Gross Margin_ G B P] ),",
              "    \"EUR\", SUM ( 'f_budgets'[Gross Margin_ E U R] ),",
              "    \"USD\", SUM ( 'f_budgets'[Gross Margin_ U S D] )",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "b0bdb24b-eff0-4cdf-aacb-a8da1b59f20d"
          },
          {
            "name": "Cost Budget",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              },
              {
                "property": "FormatStringDefinition"
              }
            ],
            "expression": "SUM ( 'f_budgets'[Cost] )",
            "formatString": "#,0.00",
            "lineageTag": "cde317b2-d5b5-4379-98f6-544dad3ab861"
          },
          {
            "name": "Budget Volume",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "SUM ( f_budgets[Volume] )",
            "formatString": "#,0.00",
            "lineageTag": "49f0a86a-c667-487d-8214-10bfd828cb5f"
          },
          {
            "name": "Budget Margin % (MTD)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "This is a derivative of Budget Margin %.",
            "displayFolder": "Budget Margin %",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR StartdateMonth =",
              "    DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 )",
              "RETURN",
              "    CALCULATE (",
              "        [Budget Margin %],",
              "        'd_date'[Date] >= StartdateMonth",
              "            && 'd_date'[Date] <= CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatString": "#,0.00",
            "lineageTag": "d969b237-18f1-4905-98fb-66d044d2acbf"
          },
          {
            "name": "Budget Volume KG (MTD)",
            "changedProperties": [
              {
                "property": "DisplayFolder"
              },
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Budget Volume",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR StartdateMonth =",
              "    DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 )",
              "RETURN",
              "    CALCULATE ((",
              "        [Budget Volume] * 1000),",
              "        'd_date'[Date] >= StartdateMonth",
              "            && 'd_date'[Date] <= CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatString": "#,0.00",
            "lineageTag": "6ebdbfb7-aee1-40f6-96b9-05d92a39ec64"
          },
          {
            "name": "Budget Volume (YTD)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "This is a derivative of Budget Volume.",
            "displayFolder": "Budget Volume",
            "expression": "[Budget Volume] * 1000",
            "formatString": "#,0.00",
            "lineageTag": "db157cf0-b6f0-492b-90e6-07f59ce0ca96"
          },
          {
            "name": "Budget Volume (MTD)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "This is a derivative of Budget Volume.",
            "displayFolder": "Budget Volume",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR StartdateMonth =",
              "    DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 )",
              "RETURN",
              "    CALCULATE (",
              "        [Budget Volume],",
              "        'd_date'[Date] >= StartdateMonth",
              "            && 'd_date'[Date] <= CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatString": "#,0.00",
            "lineageTag": "3b0fc6b7-8710-4b00-bebe-8a0223a232e7"
          },
          {
            "name": "Cost Budget (MTD)",
            "description": "This measure is a derivative of Cost Budget.",
            "displayFolder": "Cost Budget",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR StartdateMonth =",
              "    DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 )",
              "RETURN",
              "    CALCULATE (",
              "        [Cost Budget],",
              "        'd_date'[Date] >= StartdateMonth",
              "            && 'd_date'[Date] <= CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatStringDefinition": {
              "expression": "[Currency Format String]"
            },
            "lineageTag": "502c7e92-3698-480b-90ee-4792d5be9f28"
          },
          {
            "name": "Budget Margin (YTD)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "This is a derivative of Budget Margin.",
            "displayFolder": "Budget Margin",
            "expression": "[Budget Margin]",
            "formatString": "#,0.00",
            "lineageTag": "a7052e18-03d1-4eff-beda-1aafe31eeff6"
          },
          {
            "name": "Budget Margin (MTD)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "This is a derivative of Budget Margin.",
            "displayFolder": "Budget Margin",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR StartdateMonth =",
              "    DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 )",
              "RETURN",
              "    CALCULATE (",
              "        [Budget Margin],",
              "        'd_date'[Date] >= StartdateMonth",
              "            && 'd_date'[Date] <= CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatString": "#,0.00",
            "lineageTag": "cbdcc41c-7027-492a-afa8-7088aa74b019"
          },
          {
            "name": "Sales Budget (YTD)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "This is a derivative of Sales Budget.",
            "displayFolder": "Sales Budget",
            "expression": "[Sales Budget]",
            "formatString": "#,0.00",
            "lineageTag": "24a33b98-8aa3-406c-8a61-282285138e3a"
          },
          {
            "name": "Sales Budget (MTD)",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": "This is a derivative of Sales Budget.",
            "displayFolder": "Sales Budget",
            "expression": [
              "VAR CurrentDate =",
              "    TODAY ()",
              "VAR StartdateMonth =",
              "    DATE ( YEAR ( CurrentDate ), MONTH ( CurrentDate ), 1 )",
              "RETURN",
              "    CALCULATE (",
              "        [Sales Budget],",
              "        'd_date'[Date] >= StartdateMonth",
              "            && 'd_date'[Date] <= CurrentDate,",
              "        ALLSELECTED ( 'd_date'[Year], 'd_date'[Financial Year] )",
              "    )"
            ],
            "formatString": "#,0.00",
            "lineageTag": "b414b60d-4a47-48f1-a09d-95756fa9b398"
          },
          {
            "name": "Budget Margin %",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": "AVERAGE ( f_budgets[Gross Margin Percentage] )",
            "formatString": "#,0.00",
            "lineageTag": "818965ad-7372-480b-b52c-6cc1a2391506"
          },
          {
            "name": "Sales Budget",
            "changedProperties": [
              {
                "property": "Name"
              },
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "SWITCH (",
              "    SELECTEDVALUE ( 'S_Currency'[Currency], \"None\" ),",
              "    \"GBP\", SUM ( 'f_budgets'[Sales_ G B P] ),",
              "    \"EUR\", SUM ( 'f_budgets'[Sales_ E U R] ),",
              "    \"USD\", SUM ( 'f_budgets'[Sales_ U S D] )",
              ")"
            ],
            "formatString": "#,0.00",
            "lineageTag": "d4b9d687-1432-4908-a135-70aa5a485735"
          }
        ],
        "partitions": [
          {
            "name": "curated_f_budgets",
            "mode": "directLake",
            "source": {
              "entityName": "curated_f_budgets",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_f_budget]"
      },
      {
        "name": "d_invoiceaddress",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PostalAddressID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f810402-5b36-458d-aa5a-cc3d2d25e13e",
            "sourceColumn": "PostalAddressID",
            "sourceLineageTag": "PostalAddressID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c9d646fe-4c63-4dff-ada1-763980135809",
            "sourceColumn": "Address",
            "sourceLineageTag": "Address",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2fc4d5a4-c60a-421f-ae56-c9a9e066b425",
            "sourceColumn": "City",
            "sourceLineageTag": "City",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a944c365-cfb6-4c9b-9c13-032f86e5dd09",
            "sourceColumn": "Country",
            "sourceLineageTag": "Country",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "2c9773a8-752e-417b-a3b1-10180328ec8e",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          },
          {
            "name": "IsHistory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "7a425d18-0f72-4333-961a-7b188d8a514d",
            "sourceColumn": "IsHistory",
            "sourceLineageTag": "IsHistory",
            "summarizeBy": "none"
          },
          {
            "name": "PostalAddressNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43782ffe-1dca-4e3c-b1bc-4a2fd0ca4da5",
            "sourceColumn": "PostalAddressNaturalID",
            "sourceLineageTag": "PostalAddressNaturalID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1f8024ad-dfc1-435c-821d-e7fbb282f652",
        "partitions": [
          {
            "name": "curated_d_postaladdress",
            "mode": "directLake",
            "source": {
              "entityName": "curated_d_postaladdress",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_postaladdress]"
      },
      {
        "name": "d_fromcurrency",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "CurrencyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "058ca8b4-be08-435d-b2bd-f82266c68f28",
            "sourceColumn": "CurrencyID",
            "sourceLineageTag": "CurrencyID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Currency Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "26f3616f-a496-4b92-a640-b81aa4c4184a",
            "sourceColumn": "CurrencyName",
            "sourceLineageTag": "CurrencyName",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Currency Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "638517f7-42d7-4bec-ac29-8bcccfca29c1",
            "sourceColumn": "CurrencyCode",
            "sourceLineageTag": "CurrencyCode",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Currency Symbol",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "61a777be-fe5b-4f88-8358-021a3acaffe7",
            "sourceColumn": "CurrencySymbol",
            "sourceLineageTag": "CurrencySymbol",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "CurrencyNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e464619-9db4-4880-ac79-22dc1e765bc9",
            "sourceColumn": "CurrencyNaturalID",
            "sourceLineageTag": "CurrencyNaturalID",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "f8c84ed9-c8bf-45e6-86cc-99826f8e7d5c",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8c23442a-51fe-499f-ab8f-236be0a18515",
        "partitions": [
          {
            "name": "curated_d_currency",
            "mode": "directLake",
            "source": {
              "entityName": "curated_d_currency",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_currency]"
      },
      {
        "name": "f_pricelist",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "FK_DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8a309119-961f-4726-8693-e6cc7782888d",
            "sourceColumn": "FK_DateID",
            "sourceLineageTag": "FK_DateID",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "FK_WarehouseID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9a560839-41fa-4eb8-9d4d-d1459e84adb8",
            "sourceColumn": "FK_WarehouseID",
            "sourceLineageTag": "FK_WarehouseID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_LegalEntityID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "6949cb55-f91f-43c8-9d19-5b1aa5d0b4a2",
            "sourceColumn": "FK_LegalEntityID",
            "sourceLineageTag": "FK_LegalEntityID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_UnitID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "c9c4e08b-6125-4e0b-8d48-5c14b0469764",
            "sourceColumn": "FK_UnitID",
            "sourceLineageTag": "FK_UnitID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5fa09d08-78fb-4706-83d8-f0803956f4d4",
            "sourceColumn": "FK_ProductID",
            "sourceLineageTag": "FK_ProductID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "523c5665-f10c-49a1-a414-bda41f803c7b",
            "sourceColumn": "FK_CustomerID",
            "sourceLineageTag": "FK_CustomerID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_CurrencyID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "657ec3d2-4c9f-454d-87f2-2f81d6d39806",
            "sourceColumn": "FK_CurrencyID",
            "sourceLineageTag": "FK_CurrencyID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_OperationalSiteID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "00dae06c-a45e-43da-ba7b-506122d9051e",
            "sourceColumn": "FK_OperationalSiteID",
            "sourceLineageTag": "FK_OperationalSiteID",
            "sourceProviderType": "real",
            "summarizeBy": "none"
          },
          {
            "name": "PriceListID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "lineageTag": "a096aa19-590a-4cef-b018-c5b82d0e8e78",
            "sourceColumn": "PriceListID",
            "sourceLineageTag": "PriceListID",
            "sourceProviderType": "real",
            "summarizeBy": "none"
          },
          {
            "name": "AttributeBasedPricingID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "lineageTag": "c311a966-11e9-4b24-82a9-147c57586168",
            "sourceColumn": "AttributeBasedPricingID",
            "sourceLineageTag": "AttributeBasedPricingID",
            "sourceProviderType": "real",
            "summarizeBy": "none"
          },
          {
            "name": "From",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "b07888c6-64c7-424f-a889-52b21684815f",
            "sourceColumn": "From",
            "sourceLineageTag": "From",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "To",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "lineageTag": "87b25192-05ce-48eb-9dce-4a993b4765bf",
            "sourceColumn": "To",
            "sourceLineageTag": "To",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "29ff4061-4f8c-4939-a190-3640b8ab8996",
            "sourceColumn": "Amount",
            "sourceLineageTag": "Amount",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "fromdate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "dcf374cf-eaeb-4e1b-9acd-d22fe78f6c87",
            "sourceColumn": "fromdate",
            "sourceLineageTag": "fromdate",
            "sourceProviderType": "real",
            "summarizeBy": "none"
          },
          {
            "name": "todate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "70c81f2d-366b-448d-aa3a-2de860f0b7bc",
            "sourceColumn": "todate",
            "sourceLineageTag": "todate",
            "sourceProviderType": "real",
            "summarizeBy": "none"
          },
          {
            "name": "LeadTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "93222d29-d19c-485b-92df-cff65f38df11",
            "sourceColumn": "LeadTime",
            "sourceLineageTag": "LeadTime",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "DisregardLeadTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "lineageTag": "b321add6-dd60-47ec-888d-c74cb9deef44",
            "sourceColumn": "DisregardLeadTime",
            "sourceLineageTag": "DisregardLeadTime",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "PriceUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "a38e82ca-a534-474e-96a9-c00dfb131b4b",
            "sourceColumn": "PriceUnit",
            "sourceLineageTag": "PriceUnit",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "PriceCharges",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "0.00",
            "lineageTag": "4140ad41-aac1-4c4c-9960-2eefd57edbe9",
            "sourceColumn": "PriceCharges",
            "sourceLineageTag": "PriceCharges",
            "sourceProviderType": "bit",
            "summarizeBy": "sum"
          },
          {
            "name": "GenericCurrency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "formatString": "0.00",
            "lineageTag": "4601d47d-e876-49e6-a5e1-e2cc18fd90a8",
            "sourceColumn": "GenericCurrency",
            "sourceLineageTag": "GenericCurrency",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FindNext",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cc2578cf-a37e-4bc2-9533-fceafc1fd3ca",
            "sourceColumn": "FindNext",
            "sourceLineageTag": "FindNext",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "sum"
          },
          {
            "name": "LineNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "lineageTag": "b68eee5b-cbbb-4123-bf09-f67fff161006",
            "sourceColumn": "LineNumber",
            "sourceLineageTag": "LineNumber",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "IsActive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "boolean",
            "formatString": "0",
            "lineageTag": "7b4cd11b-78db-40c7-98de-c92b141c49d4",
            "sourceColumn": "IsActive",
            "sourceLineageTag": "IsActive",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Color",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "lineageTag": "cadbfe4d-7769-4bcf-9612-4e2c4cbb890b",
            "sourceColumn": "Color",
            "sourceLineageTag": "Color",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Version",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ee24dbe-f895-4e71-bdbd-f060ba26d4ed",
            "sourceColumn": "Version",
            "sourceLineageTag": "Version",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Configuration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "lineageTag": "e7c29d77-9dad-4804-afe6-5dcdbc66b0ba",
            "sourceColumn": "Configuration",
            "sourceLineageTag": "Configuration",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Size",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "lineageTag": "ffc1d854-5979-4ab8-ba46-6bbcbd621e1a",
            "sourceColumn": "Size",
            "sourceLineageTag": "Size",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Style",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "lineageTag": "59bdb670-365d-41c6-86f6-dc2a3e078c2f",
            "sourceColumn": "Style",
            "sourceLineageTag": "Style",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "SecondaryUOM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "formatString": "0",
            "lineageTag": "96e3b588-b0fd-4622-9216-1848e5f97f93",
            "sourceColumn": "SecondaryUOM",
            "sourceLineageTag": "SecondaryUOM",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "PricePerSecondaryUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              },
              {
                "property": "SummarizeBy"
              }
            ],
            "dataType": "double",
            "formatString": "0.0000",
            "lineageTag": "62f56fd6-bdf7-4563-b2d6-50e67f7a1bb7",
            "sourceColumn": "PricePerSecondaryUnit",
            "sourceLineageTag": "PricePerSecondaryUnit",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_SupplierID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b4d37a11-ab95-4123-a4ff-87265ca51455",
            "sourceColumn": "FK_SupplierID",
            "sourceLineageTag": "FK_SupplierID",
            "sourceProviderType": "real",
            "summarizeBy": "none"
          },
          {
            "name": "AccountRelation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c0f74d6-ad69-4ea5-b80e-d09e7955c951",
            "sourceColumn": "AccountRelation",
            "sourceLineageTag": "AccountRelation",
            "summarizeBy": "none"
          },
          {
            "name": "FK_BusinessUnitID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "cbb94622-8817-4d3f-a36a-dd7374dfda6b",
            "sourceColumn": "FK_BusinessUnitID",
            "sourceLineageTag": "FK_BusinessUnitID",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "6ab90ce6-8546-4a45-917b-b2278a6dfc8f",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          },
          {
            "name": "PriceListNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c438552c-34d6-4442-9faf-2d30cff55ec2",
            "sourceColumn": "PriceListNaturalID",
            "sourceLineageTag": "PriceListNaturalID",
            "summarizeBy": "none"
          },
          {
            "name": "FK_SalesAreaID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7a06e447-1671-4574-80bf-a659fa4a9bc5",
            "sourceColumn": "FK_SalesAreaID",
            "sourceLineageTag": "FK_SalesAreaID",
            "summarizeBy": "none"
          },
          {
            "name": "FK_SalesTeamID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "9e027303-c49f-4cea-b0e6-af230380420b",
            "sourceColumn": "FK_SalesTeamID",
            "sourceLineageTag": "FK_SalesTeamID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "31efc7c5-acbe-4953-af89-f7f96b87db5e",
        "partitions": [
          {
            "name": "curated_f_pricelist",
            "mode": "directLake",
            "source": {
              "entityName": "curated_f_pricelist",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_f_salesorders]"
      },
      {
        "name": "b_userlegalentity",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "FK_UserID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "52156811-a1cb-4a75-9823-ea1f964b6a78",
            "sourceColumn": "FK_UserID",
            "sourceLineageTag": "FK_UserID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_LegalEntityID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "b7cbe108-d89f-407f-8248-a6983e84bb7e",
            "sourceColumn": "FK_LegalEntityID",
            "sourceLineageTag": "FK_LegalEntityID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "591378f1-554f-4583-8736-5eaf71810fb3",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          },
          {
            "name": "UserLegalEntityNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "92714bd0-b440-4505-ae84-219e8c59e08c",
            "sourceColumn": "UserLegalEntityNaturalID",
            "sourceLineageTag": "UserLegalEntityNaturalID",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "a004136c-bc47-4fc0-aeff-2da4f402dd55",
        "partitions": [
          {
            "name": "curated_b_userlegalentity",
            "mode": "directLake",
            "source": {
              "entityName": "curated_b_userlegalentity",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_b_userlegalentity]"
      },
      {
        "name": "d_salesteam",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "81affb76-0a91-4152-a188-58cb7fd0e62b",
            "sourceColumn": "Email",
            "sourceLineageTag": "Email",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "UserID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2578507a-d1a2-466d-87e1-6c68bfcfb9d7",
            "sourceColumn": "UserID",
            "sourceLineageTag": "UserID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Full Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e1fe801-7797-4716-84fc-3302534a0be0",
            "sourceColumn": "FullName",
            "sourceLineageTag": "FullName",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Account Manager Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "ae78d2aa-c143-4a82-9c91-ea4d72e35205",
            "sourceColumn": "AccountManagerFlag",
            "sourceLineageTag": "AccountManagerFlag",
            "sourceProviderType": "bit",
            "summarizeBy": "none"
          },
          {
            "name": "Reports To",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6ec46f0-39a8-443e-8b3e-a8fe1c476d4d",
            "sourceColumn": "ReportsTo",
            "sourceLineageTag": "ReportsTo",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Reports To Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db9edc34-3eb4-4d4d-89a6-c664727d2b87",
            "sourceColumn": "ReportsToEmail",
            "sourceLineageTag": "ReportsToEmail",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Director",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2cb2d58-8f77-4141-9932-b7f2a822a8e7",
            "sourceColumn": "Director",
            "sourceLineageTag": "Director",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Director Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "138484c5-7291-4ff1-afbd-0d214edb0466",
            "sourceColumn": "DirectorEmail",
            "sourceLineageTag": "DirectorEmail",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "b98cb65c-cb6a-4acf-8ad0-9c03cc64de6e",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          },
          {
            "name": "UserNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8123cdd9-6f11-4c34-895b-50cd2a7eb7cb",
            "sourceColumn": "UserNaturalID",
            "sourceLineageTag": "UserNaturalID",
            "summarizeBy": "none"
          },
          {
            "name": "WorkerNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a0d7b71-f85e-4c82-a0a1-58c24da7cb15",
            "sourceColumn": "WorkerNaturalID",
            "sourceLineageTag": "WorkerNaturalID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cceb609c-1dfe-454a-90d5-66c9cc443796",
        "partitions": [
          {
            "name": "curated_d_user",
            "mode": "directLake",
            "source": {
              "entityName": "curated_d_user",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_user]"
      },
      {
        "name": "l_user",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Full Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a0119f6b-27ea-4ea6-909d-7d7cfd8aac95",
            "sourceColumn": "FullName",
            "sourceLineageTag": "FullName",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6c109966-494e-4a51-92e8-1c6e627e7429",
            "sourceColumn": "Email",
            "sourceLineageTag": "Email",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Account Manager Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "e59d02ce-c043-41ff-86bc-45cb50801080",
            "sourceColumn": "AccountManagerFlag",
            "sourceLineageTag": "AccountManagerFlag",
            "sourceProviderType": "bit",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "275eaf8e-bc88-450f-b4f3-b264aa3e4e03",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "summarizeBy": "none"
          },
          {
            "name": "PositionNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "lineageTag": "f5597662-9f1d-4494-9feb-dc94ebc14d83",
            "sourceColumn": "PositionNaturalID",
            "sourceLineageTag": "PositionNaturalID",
            "summarizeBy": "count"
          },
          {
            "name": "UserNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47525f74-c655-45ac-86a1-9720824c39c5",
            "sourceColumn": "UserNaturalID",
            "sourceLineageTag": "UserNaturalID",
            "summarizeBy": "none"
          },
          {
            "name": "WorkerNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c5c0e90f-cb07-49c9-b027-3d2b87136750",
            "sourceColumn": "WorkerNaturalID",
            "sourceLineageTag": "WorkerNaturalID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f2fb297c-39f5-4870-ad38-5652c8cfbf2c",
        "partitions": [
          {
            "name": "curated_l_user",
            "mode": "directLake",
            "source": {
              "entityName": "curated_l_user",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_l_user]"
      },
      {
        "name": "d_shippingdate",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "efc7a23e-99b4-4a88-a24b-16a01f23fd31",
            "sourceColumn": "DateID",
            "sourceLineageTag": "DateID",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "fc3c80de-6dd5-480e-ac14-37b7ddf16a01",
            "sourceColumn": "Date",
            "sourceLineageTag": "Date",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43390239-ce51-4fa4-a3b8-6e28d43af500",
            "sourceColumn": "Day",
            "sourceLineageTag": "Day",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Day Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8de16a8-de61-401a-966d-423729ee1706",
            "sourceColumn": "DayShort",
            "sourceLineageTag": "DayShort",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Day Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "48c482f4-a707-4697-b6eb-68feaece557c",
            "sourceColumn": "DayNumber",
            "sourceLineageTag": "DayNumber",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Weekday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c17aa6a3-4729-429f-be3e-1b834a527ac2",
            "sourceColumn": "Weekday",
            "sourceLineageTag": "Weekday",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "045e6d77-f499-4a76-aac6-466cea329261",
            "sourceColumn": "Week",
            "sourceLineageTag": "Week",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Week Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "58dc6878-aa11-4510-8066-be38a69d3e1f",
            "sourceColumn": "WeekNumber",
            "sourceLineageTag": "WeekNumber",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75d91bd3-a64f-4e48-96c3-b9656a5de1f6",
            "sortByColumn": "Month Number",
            "sourceColumn": "Month",
            "sourceLineageTag": "Month",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Month Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0aeaf65e-1bf3-4f8b-b9f7-997224754d9c",
            "sourceColumn": "MonthShort",
            "sourceLineageTag": "MonthShort",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0d7bcdd0-1b99-4992-91ad-20f1a85a10b6",
            "sourceColumn": "MonthNumber",
            "sourceLineageTag": "MonthNumber",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Month Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "71589027-415d-4be8-bc41-9dba8f9fcb79",
            "sourceColumn": "MonthDay",
            "sourceLineageTag": "MonthDay",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "379bc5bf-1b99-4e2e-9761-fe9928651cff",
            "sourceColumn": "Quarter",
            "sourceLineageTag": "Quarter",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2147ee9d-3767-423a-a232-237912a897cf",
            "sourceColumn": "QuarterNumber",
            "sourceLineageTag": "QuarterNumber",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "354cb3b5-68c1-463c-b391-2104665b765e",
            "sourceColumn": "Year",
            "sourceLineageTag": "Year",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Year Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02567cf5-ab8a-424f-aca4-1590fb2b7af8",
            "sourceColumn": "YearQuarter",
            "sourceLineageTag": "YearQuarter",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Year Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d9bf140-3f4c-42c9-9272-18dd853b0896",
            "sourceColumn": "YearMonthName",
            "sourceLineageTag": "YearMonthName",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Year Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "677157c9-9b35-4aca-bac2-23d632e5ed0a",
            "sourceColumn": "YearMonth",
            "sourceLineageTag": "YearMonth",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "First Of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "bfea4903-db71-42fc-88eb-4adc03d1c989",
            "sourceColumn": "FirstOfMonth",
            "sourceLineageTag": "FirstOfMonth",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "First Of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "3de7434a-cdb5-4958-a109-3b61afad8b58",
            "sourceColumn": "FirstOfWeek",
            "sourceLineageTag": "FirstOfWeek",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "be2db442-6805-4551-9d7a-f3a5524dbe9d",
            "sourceColumn": "Period",
            "sourceLineageTag": "Period",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Financial Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3b18a440-bcd3-4549-9b83-a148a0739718",
            "sourceColumn": "FinancialYear",
            "sourceLineageTag": "FinancialYear",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Financial Year Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "39b8eba4-3528-46f8-b04d-f35c850e4b1d",
            "sourceColumn": "FinancialYearPeriod",
            "sourceLineageTag": "FinancialYearPeriod",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Financial Year Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af2a0166-da4e-49c9-9d5d-2ec2fb4b4d84",
            "sourceColumn": "FinancialYearMonthName",
            "sourceLineageTag": "FinancialYearMonthName",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Financial Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0611b8de-c43f-47cc-901a-369e565c95d6",
            "sourceColumn": "FinancialQuarter",
            "sourceLineageTag": "FinancialQuarter",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Financial Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "72c33a22-3c12-4d05-93c2-bc374b4a54e4",
            "sourceColumn": "FinancialQuarterNumber",
            "sourceLineageTag": "FinancialQuarterNumber",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Financial Year Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb03c992-4ede-4a6b-90a1-8fba9c38b2b1",
            "sourceColumn": "FinancialYearQuarter",
            "sourceLineageTag": "FinancialYearQuarter",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "DateNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "lineageTag": "effdc591-7b7a-4ebe-997e-caab25fe7a28",
            "sourceColumn": "DateNaturalID",
            "sourceLineageTag": "DateNaturalID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "36bb6437-bf6a-44f1-a47e-c831c2e109c9",
        "partitions": [
          {
            "name": "curated_d_date",
            "mode": "directLake",
            "source": {
              "entityName": "curated_d_date",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_date]"
      },
      {
        "name": "f_comahlimits",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ComahLimitsNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "formatString": "0",
            "lineageTag": "3b6a0d39-508f-4c45-93d4-2a05e61e5ec7",
            "sourceColumn": "ComahLimitsNaturalID",
            "sourceLineageTag": "ComahLimitsNaturalID",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "FK_LimitsComahSubstanceID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "deb4f1bb-68af-4046-abba-abb2a9432073",
            "sourceColumn": "FK_ComahSubstanceID",
            "sourceLineageTag": "FK_ComahSubstanceID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_LimitsComahSubcategoryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "6bddeaa9-d1c5-4f9b-ba02-facceae1ba88",
            "sourceColumn": "FK_ComahSubCategoryID",
            "sourceLineageTag": "FK_ComahSubCategoryID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "Upper Limit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "lineageTag": "ffe938a2-06d7-4252-ba83-39b7c5de89e8",
            "sourceColumn": "UpperLimit",
            "sourceLineageTag": "UpperLimit",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "sum"
          },
          {
            "name": "Lower Limit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "lineageTag": "224b6dc9-9755-4e09-ae15-6d021ce09f26",
            "sourceColumn": "LowerLimit",
            "sourceLineageTag": "LowerLimit",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "5a487e95-ac68-4e96-9028-890d96fdf5a7",
        "partitions": [
          {
            "name": "curated_f_comahlimits",
            "mode": "directLake",
            "source": {
              "entityName": "curated_f_comahlimits",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_f_comahsnapshot]"
      },
      {
        "name": "d_comahsubcategory",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ComahSubCategoryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "29f64024-9ecd-45f0-9d0c-dc0a016ae8a4",
            "sourceColumn": "ComahSubCategoryID",
            "sourceLineageTag": "ComahSubCategoryID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "ComahSubCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d3e9b4d-7ab4-453f-8c4b-1c41ae9ad897",
            "sourceColumn": "ComahSubCategory",
            "sourceLineageTag": "ComahSubCategory",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7df62a32-9041-4421-876f-20c321710cdf",
        "partitions": [
          {
            "name": "curated_d_comahsubcategory",
            "mode": "directLake",
            "source": {
              "entityName": "curated_d_comahsubcategory",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_comahcategory]"
      },
      {
        "name": "f_consignmentstock",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ConsignmentStockNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aee27b9e-1703-4507-8f72-3f454c60766b",
            "sourceColumn": "ConsignmentStockNaturalID",
            "sourceLineageTag": "ConsignmentStockNaturalID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c2137ea-62b6-46a9-9101-6f9ef25d2432",
            "sourceColumn": "FK_ProductID",
            "sourceLineageTag": "FK_ProductID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "LeadTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "dataType": "int64",
            "lineageTag": "f54ad0aa-24d9-4244-ae1a-92585916d2f8",
            "sourceColumn": "LeadTime",
            "sourceLineageTag": "LeadTime",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "sum"
          },
          {
            "name": "HighestQty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "dataType": "double",
            "lineageTag": "fc9c29e6-8a05-48ea-a887-9126f89d7794",
            "sourceColumn": "HighestQty",
            "sourceLineageTag": "HighestQty",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "sum"
          },
          {
            "name": "LowestQty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "dataType": "double",
            "lineageTag": "c0564a16-52b3-48fb-bf38-24ee1f4e4f8f",
            "sourceColumn": "LowestQty",
            "sourceLineageTag": "LowestQty",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "36dfa8d8-0243-4684-81c0-c3e5da775d70",
        "partitions": [
          {
            "name": "curated_f_consignmentstock",
            "mode": "directLake",
            "source": {
              "entityName": "curated_f_consignmentstock",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_comahcategory]"
      },
      {
        "name": "b_externalitem",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ExternalItemNaturalID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2975a0f9-8c36-4d26-a649-efcd4c3ddcb9",
            "sourceColumn": "ExternalItemNaturalID",
            "sourceLineageTag": "ExternalItemNaturalID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "ExternalItemID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c709340-dd65-413a-8cba-391baa4516db",
            "sourceColumn": "ExternalItemID",
            "sourceLineageTag": "ExternalItemID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "ExternalItemDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ea1f60b-436f-4f49-a52f-8385a8ba3bee",
            "sourceColumn": "ExternalItemDescription",
            "sourceLineageTag": "ExternalItemDescription",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_LegalEntityID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a5459606-c910-4c0a-a564-e6f684459d80",
            "sourceColumn": "FK_LegalEntityID",
            "sourceLineageTag": "FK_LegalEntityID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4a1f401a-66eb-4aff-a49f-0f06c1de30f1",
            "sourceColumn": "FK_ProductID",
            "sourceLineageTag": "FK_ProductID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_SupplierID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4d2be71d-ec46-44a7-a935-8e7dcabc9f7b",
            "sourceColumn": "FK_SupplierID",
            "sourceLineageTag": "FK_SupplierID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "FK_CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "50ec7bfe-544f-415c-b66c-e8c6898dd908",
            "sourceColumn": "FK_CustomerID",
            "sourceLineageTag": "FK_CustomerID",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          },
          {
            "name": "IsDelete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "Name"
              }
            ],
            "dataType": "boolean",
            "lineageTag": "a42ed19c-9610-4790-a49e-182b258b1935",
            "sourceColumn": "IsDelete",
            "sourceLineageTag": "IsDelete",
            "sourceProviderType": "varchar(8000)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "99ae780e-d871-4b56-be56-0d48c69ca8d7",
        "partitions": [
          {
            "name": "curated_b_externalitem",
            "mode": "directLake",
            "source": {
              "entityName": "curated_b_externalitem",
              "expressionSource": "DatabaseQuery",
              "schemaName": "dbo",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "[dbo].[curated_d_comahcategory]"
      }
    ]
  }
}